### ISSUE TITLE
用get方法取值時發生stackoverflowexception

### ISSUE THREAD

**Issue by yuessir** [dotnetcore/EasyCaching#105]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1. 
2. 用get方法取值時發生stackoverflowexception

### Related code

```
provider.Get（）
```

**Expected behavior:** [What you expected to happen]

Debug模式運行網站前期會先把setting values 到memory，
接著運行中斷，發生exception
請問有可能什麼原因？

## Specifications

- Provider    : InMemory 0.5.4
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : win10

**Comment by catcherwong** [comment]
@yuessir Thanks for your interest in this project.

Can you please provide more information for this problem? And the version of InMemory caching provider is v0.2.0?

**Comment by yuessir** [comment]
你好 @catcherwong 
我traced code到

`
public T GetValue<T>()
            {
                object val = Value;
                var t = typeof(T);

                if (t == TypeHelper.BoolType || t == TypeHelper.StringType || t == TypeHelper.CharType || t == TypeHelper.DateTimeType || t.IsNumeric())
                    return (T)Convert.ChangeType(val, t);

                if (t == TypeHelper.NullableBoolType || t == TypeHelper.NullableCharType || t == TypeHelper.NullableDateTimeType || t.IsNullableNumeric())
                    return val == null ? default(T) : (T)Convert.ChangeType(val, Nullable.GetUnderlyingType(t));

                return (T)val;
            }
`
在 t.IsNullableNumeric()發生exception
這個
由於我在使用 @catcherwong 您的框架在開發我們公司的內tool
故不清楚到底是哪裡有問題才此前來開issue求救 因為問題複雜我選擇中文來提問

下面附上發生錯誤代碼(我盡所能提供一切信息)

**Comment by yuessir** [comment]
![Uploading 20190413_222551.jpg…]()

**Comment by LabelZhou** [comment]
@yuessir Can you provide a minimal sample code?

**Comment by catcherwong** [comment]
@yuessir  I notice that your type is `System.RuntimeType` , what data you store in cache?

**Comment by yuessir** [comment]
@LabelZhou 感謝您願意協助 但因項目架構複雜,發生exception的項目是插件, 依賴代碼庫太多不好剝離呈現 我盡量試試
@catcherwong `Fun<T>` T is `new Dictionary<string,IList<MySettingForCaching>>()`
MySettingForCaching class is **serializable**.

**Comment by catcherwong** [comment]
@yuessir 

I had try the following code, it runs well.

```cs
        [Fact]
        public void Issues105_StackOverflowException_Test()
        {
            var cacheKey = Guid.NewGuid().ToString();

            var cacheValue = new Dictionary<string, IList<MySettingForCaching>>()
            {
                { "ss", new List<MySettingForCaching>{ new MySettingForCaching { Name = "aa" } } }
            };

            _provider.Set(cacheKey, cacheValue, TimeSpan.FromMilliseconds(200));
            var res = _provider.Get<Dictionary<string, IList<MySettingForCaching>>>(cacheKey);

            var first = res.Value.First();

            Assert.Equal("ss", first.Key);
            Assert.Equal(1, first.Value.Count);
        }

        [Serializable]
        public class MySettingForCaching
        { 
            public string Name { get; set; }
        }
```

**Comment by yuessir** [comment]
Yeah ,this unit test is definitely true. I will do investigate my code :(, and repo the case again,
 thanks for the double checking. 👍

**Comment by catcherwong** [comment]
OK , if you have more questions for this, reopen this issue or open a new issue 😄

**Comment by yuessir** [comment]
Interceptor with null value will  resulted in the problem?

**Comment by catcherwong** [comment]
No, It may be my fault to reference the wrong issue. I feel so sorry for this mistake.
