### ISSUE TITLE
方法返回null值，报错，这种怎么处理？

### ISSUE THREAD

**Issue by dengkai1991** [dotnetcore/EasyCaching#106]

**Comment by catcherwong** [comment]
@dengkai1991  Thanks for your interest in this project.

What do you mean for a method return null and the application throw exception?

**Comment by dengkai1991** [comment]
> @dengkai1991 Thanks for your interest in this project.
> 
> What do you mean for a method return null and the application throw exception?

是的，因为cacheable写在服务接口上，存在null的情况，我遇到是的返回List<string>是null，然后报cache value not null

**Comment by catcherwong** [comment]
@dengkai1991  Sorry for this bug, I hava find out the problem, and I will fix it ASAP!

**Comment by catcherwong** [comment]
@dengkai1991 v0.5.4.2-beta2 fixed this bug.

**Comment by dengkai1991** [comment]
Thanks发自我的iPhone------------------ 原始邮件 ------------------发件人: Catcher Wong  <notifications@github.com>发送时间: 2019年4月15日 22:59收件人: dotnetcore/EasyCaching <EasyCaching@noreply.github.com>抄送: dengkai <dengkai1991@gmail.com>, Mention <mention@noreply.github.com>主题: 回复：[dotnetcore/EasyCaching] 方法返回null值，报错，这种怎么处理？ (#106)@dengkai1991 v0.5.4.2-beta2 fixed this bug.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dotnetcore/EasyCaching","title":"dotnetcore/EasyCaching","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/dotnetcore/EasyCaching"}},"updates":{"snippets":[{"icon":"PERSON","message":"@catcherwong in #106: @dengkai1991 v0.5.4.2-beta2 fixed this bug."}],"action":{"name":"View Issue","url":"https://github.com/dotnetcore/EasyCaching/issues/106#issuecomment-483288076"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dotnetcore/EasyCaching/issues/106#issuecomment-483288076",
"url": "https://github.com/dotnetcore/EasyCaching/issues/106#issuecomment-483288076",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by catcherwong** [comment]
I will close this issue, if you have any other issues about this problem, reopen this issue or open a new issue 😄
