### ISSUE TITLE
HybridCachingProvider can be downgraded to use LocalCacheProvider

### ISSUE THREAD

**Issue by geffzhang** [dotnetcore/EasyCaching#114]
## Description
HybridCachingProvider can be downgraded to use LocalCacheProvider when DistributedCache is abnormal, ensuring the availability of the cache service

**Comment by catcherwong** [comment]
@geffzhang Thanks for your interest in this project.

This is an awesome suggestion, I will consider how to deal with this problem ASAP.

**Comment by catcherwong** [comment]
Release `EasyCaching.HybridCache` v0.5.6.1 for this issue.
