### ISSUE TITLE
关于缓存AOP

### ISSUE THREAD

**Issue by 812169562** [dotnetcore/EasyCaching#116]
我现在用的DI是Autofac，但是再使用AOP时候，好像无效。return 
 services.ConfigureAspectCoreInterceptor(options => options.CacheProviderName = EasyCachingConstValue.DefaultInMemoryName) Bulid了，这样就不得行，希望大佬指正一下可以增门使用.顺便再问一句AOP目前只支持InMemory吗？

**Comment by catcherwong** [comment]
@812169562  Thanks for your interest in this project.

Can you please provide more information on your problem?

**Comment by 812169562** [comment]
我现在注入部分是这样写的：
   public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddEasyCaching(options =>
            {
                options.UseInMemory();
            });
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        

-     **services.ConfigureAspectCoreInterceptor(options => options.CacheProviderName = EasyCachingConstValue.DefaultInMemoryName);**

            DefaultIocConfig.ContainerBuilder.RegisterType<AspectCoreService>().As<IAspectCoreService>().AsImplementedInterfaces().InstancePerLifetimeScope();
            DefaultIocConfig.ContainerBuilder.Populate(services);
            DefaultIocConfig.Container = DefaultIocConfig.ContainerBuilder.Build();
            return DefaultIocConfig.Container.Resolve<IServiceProvider>();
        }

DefaultIocConfig.Container 是Autofac 的注入容器，但是-     **services.ConfigureAspectCoreInterceptor(options => options.CacheProviderName = EasyCachingConstValue.DefaultInMemoryName);** 这个地方我看到源码里面也bulid了，是必须需要返回。可我此处只能返回DefaultIocConfig.Container.Resolve<IServiceProvider>(); 不然这样我就注入也正确

**Comment by yrinleung** [comment]
@812169562 
可以参考EasyCaching.Extensions的实现[EasyCaching.Interceptor.AspectCore.Autofac](https://github.com/yrinleung/EasyCaching.Extensions/blob/master/src/EasyCaching.Interceptor.AspectCore.Autofac/AspectCoreInterceptorAutofacExtensions.cs)
或者直接引用[YrinLeung.EasyCaching.Interceptor.AspectCore.Autofac](https://www.nuget.org/packages/YrinLeung.EasyCaching.Interceptor.AspectCore.Autofac/)

**Comment by catcherwong** [comment]
@812169562 

You can follow the suggestion provided by @yrinleung

**Comment by 812169562** [comment]
好的，谢谢，我也准备打算自己实现，看来已经有人做了！非常不错的项目！
