### ISSUE TITLE
进程间缓存无法获取

### ISSUE THREAD

**Issue by dreamMoli** [dotnetcore/EasyCaching#118]
在使用inmemory模式时，当我在a.cs里面缓存的数据，无法在b.cs里面获取，这是为啥？

**Comment by catcherwong** [comment]
@dreamMoli  Thanks for your interest in this project.

Can you please provide more information on your problem?

**Comment by dreamMoli** [comment]
as follows，in"AuthorizedHandlingExtensions.cs" ,i can't read the "id" value.
startup.cs: 
services.AddEasyCaching(option =>
            {
                option.UseInMemory(options => 
                {
                     options.DBConfig = new InMemoryCachingOptions
                     {
                         ExpirationScanFrequency = 60,
                         SizeLimit = 100 
                     };
                     options.MaxRdSecond = 0;
                     options.EnableLogging = false;
                     options.LockMs = 5000;
                     options.SleepMs = 300;
                 }, "m1");
            });
services.AddTokenService(); // Initializes some cache
app.UseEasyCaching();


app.UseAuthorizedHandling();//read cache

AuthorizedHandlingExtensions.cs
private readonly IEasyCachingProviderFactory _cache;
public AuthorizedHandlingMiddleware(RequestDelegate _next,ILogger<AuthorizedHandlingMiddleware> logger,IEasyCachingProviderFactory cache)
        {
this.next = _next;
            this._logger = logger;
            this._cache = cache;
        }
public async Task Invoke(Microsoft.AspNetCore.Http.HttpContext context)
{
var a = provider_1.Get<string>("id");
await next(context);
}

TokenServiceExtensions.cs
public static IServiceCollection AddTokenService(this IServiceCollection serviceCollection)
        {
           provider_1.Set("id","test");
            return serviceCollection;
        }

**Comment by catcherwong** [comment]
If you want to use `IEasyCachingProviderFactory`, you should get the provider at first. But based on your code, I can not find it.

You can try the following code.

```cs
private readonly IEasyCachingProvider _cache;
public AuthorizedHandlingMiddleware(RequestDelegate _next,ILogger logger,IEasyCachingProviderFactory factory)
{
    this.next = _next;
    this._logger = logger;
    // provider name should be same as before
    this._cache = factory.GetCachingProvider("m1");
}
```

**Comment by dreamMoli** [comment]
i‘m sorry, i did it，but still not read the "id" value，in another "class"

**Comment by catcherwong** [comment]
Could you please provide a simple demo for your issue?

**Comment by dreamMoli** [comment]
In fact, I would like to ask is the Distributed cache，Does EasyCaching support？

**Comment by catcherwong** [comment]
Both local cache and distributed cache are supported in EasyCaching.

**Comment by dreamMoli** [comment]
Could you please provide a simple demo for me ?

**Comment by catcherwong** [comment]
https://github.com/dotnetcore/EasyCaching/tree/master/sample/EasyCaching.Demo.Providers

**Comment by dreamMoli** [comment]
thanks,in Controller, i can read the cache. 
in my demo
i want to record the cache in this place. "static IServiceCollection AddTokenService(this IServiceCollection serviceCollection)"

and read the cache in middleware. so i found,in" IServiceCollection" the cache invalid.
Please advise me，thank you!

**Comment by catcherwong** [comment]
Both middleware and controller are the same! 


```cs
        private readonly RequestDelegate _next;
        private readonly ILogger _logger;
        private readonly IEasyCachingProviderFactory _providerFactory;

        public MyMiddleware(RequestDelegate next, ILoggerFactory loggerFactory, IEasyCachingProviderFactory providerFactory)
        {
            this._next = next;
            this._logger = loggerFactory.CreateLogger<AuthMiddleware>();        
            this._providerFactory = providerFactory;
        }

        public async Task Invoke(HttpContext context)
        {
               var provider = _providerFactory.GetCachingProvider("m1");
               var res = await provider.GetAsync<string>(cacheKey);

               await _next(context);       
        }
```

If you want to use it with `IServiceCollection`,  following below code

```cs
            IServiceCollection services = new ServiceCollection();
            services.AddEasyCaching(x => x.UseInMemory(options => options.MaxRdSecond = 0));
            IServiceProvider serviceProvider = services.BuildServiceProvider();
            var providerFactory = serviceProvider.GetService<IEasyCachingProviderFactory>();
            var provider = providerFactory.GetCachingProvider("m1");
            var res = await provider.GetAsync<string>(cacheKey);
```

**Comment by dreamMoli** [comment]
Could you please provide a demo about IServiceCollection demo for me ? because i used the code，but still  invalid.

**Comment by catcherwong** [comment]
There is no demo for this, you can follow the unit tests of EasyCaching.

**Comment by dreamMoli** [comment]
ok
