### ISSUE TITLE
EasyCachingApplicationBuliderExtensions UseCaching method in the proposal

### ISSUE THREAD

**Issue by hanfeige** [dotnetcore/EasyCaching#121]
### Steps to Reproduce
This method extends the IApplicationBuilder, for the sake of the extension, quoting the redundant assembly. Microsoft AspNetCore. Http. Abstractions, but after watching the source think it is not necessary.
### Related code
        public static IApplicationBuilder UseEasyCaching(this IApplicationBuilder app)
        {
            ArgumentCheck.NotNull(app, nameof(app));

            var options = app.ApplicationServices.GetService(typeof(EasyCachingOptions));

            if (options != null && options is EasyCachingOptions)
            {
                foreach (var serviceExtension in ((EasyCachingOptions)options).Extensions)
                {
                    serviceExtension.WithServices(app);
                }
            }

            return app;
        }
### Sqlite Code

        /// <summary>
        /// Withs the services.
        /// </summary>
        /// <param name="app">App.</param>
        public void WithServices(IApplicationBuilder app)
        {
            var dbProviders = app.ApplicationServices.GetServices<ISQLiteDatabaseProvider>();

            foreach (var dbProvider in dbProviders)
            {
                var conn = dbProvider.GetConnection();

                if (conn.State == System.Data.ConnectionState.Closed)
                {
                    conn.Open();
                }

                conn.Execute(ConstSQL.CREATESQL);
            }
        }
### Other Code
               /// <summary>
        /// Withs the services.
        /// </summary>
        /// <param name="services">Services.</param>
        public void WithServices(IApplicationBuilder app)
        {
            // Method intentionally left empty.
        }
### Advice
If this method is simply to app. ApplicationServices. GetServices, suggest use IServiceCollection instead

**Comment by hanfeige** [comment]
早知道写中文了，有道翻译半天；
正在搭建自己的项目架构，用到了easyCaching，但发现其UseCaching的扩展方法导致引入了额外的程序包（Microsoft.AspNetCore.Http.Abstractions），这完全是可以避免的，因为WithServices方法仅仅是从容器中获取对象而已，接口参数定义为IServiceCollection就能解决，同时也能更好的集成其他第三方的DI容器

**Comment by catcherwong** [comment]
@hanfeige  Thanks for your interest in this project.

Fewer dependencies is a really good issue, but it seems we can't remove `Microsoft.AspNetCore.Http.Abstractions` at this time.

`UseEasyCaching` is mainly for initialization(SQLite and memcached) that we usually put it in `Configure` method. It seems that we can't use `IServiceCollection` in this method.

**Comment by hanfeige** [comment]
> @hanfeige Thanks for your interest in this project.
> 
> Fewer dependencies is a really good issue, but it seems we can't remove `Microsoft.AspNetCore.Http.Abstractions` at this time.
> 
> `UseEasyCaching` is mainly for initialization(SQLite and memcached) that we usually put it in `Configure` method. It seems that we can't use `IServiceCollection` in this method.

How to use Sqlite to use EasyCaching in console program?

**Comment by catcherwong** [comment]
If we want to use EasyCaching in a console application, we will choose `Generic Host`  😂

**Comment by hanfeige** [comment]
> If we want to use EasyCaching in a console application, we will choose `Generic Host` 😂

Is there any sample code？

**Comment by catcherwong** [comment]
Sorry for the above suggestion when using SQLite in console application. It also need some more step. Just like the UTs to create the table at first.

https://github.com/dotnetcore/EasyCaching/blob/1a7f2a7c25dbc8748adac9095be258cbd956272f/test/EasyCaching.UnitTests/CachingTests/SQLiteCachingTest.cs#L33-L43

I think this should be changed if there have some good ideas.
