### ISSUE TITLE
The purpose of InMemory addonly?

### ISSUE THREAD

**Issue by nicoxiang** [dotnetcore/EasyCaching#123]
## Description

Hi, i found code below when i read the code, then I'm wondering under what circumstances should we use InMemory addonly method? 

### Related code

https://github.com/dotnetcore/EasyCaching/blob/master/src/EasyCaching.InMemory/Internal/InMemoryCaching.cs#L142-L151

**Comment by catcherwong** [comment]
@nicoxiang  Thanks for your interest in this project.

`addonly` mainly used for `TrySet/TrySetAsync`.

**Comment by nicoxiang** [comment]
@catcherwong It's not so clear to me, the method name is <code>Add</code>, but used for <code>TrySet/TrySetAsync</code>

**Comment by catcherwong** [comment]
First of all, `InMemoryCaching.cs` is an implementation to handle memory cache which is similar to [MemoryCache.cs](https://github.com/aspnet/Extensions/blob/master/src/Caching/Memory/src/MemoryCache.cs).

In `InMemoryCaching.cs`,  there are two methods to add a cache. One is `Add`, the other is `Set`. The action of them is different!

`Add` means that if a key exists, it will **not overwrite** its value, if not, it will add a new one.

`Set` means that if a key exists, it will **overwrite** its value, if not, it will add a new one.

**Comment by nicoxiang** [comment]
@catcherwong Can i understand like,  <code>Add</code> means add a **new** one or update a **expired** one?

**Comment by catcherwong** [comment]
@nicoxiang  

I apologize for the late reply to you very much!

What you describe is the `Set` method.

This is similar to command [setnx](https://redis.io/commands/setnx) of redis.

Also similar to `TryAdd` of `ConcurrentDictionary`.

**Comment by nicoxiang** [comment]
@catcherwong But seems that's what <code>Add</code> method is doing right now.

``` C#
if (addOnly)
            {
                //add new key success
                if (!_memory.TryAdd(entry.Key, entry))
                {
                    //fail if old key exists and hasn't expired yet
                    if (!_memory.TryGetValue(entry.Key, out var existingEntry) || existingEntry.ExpiresAt >= SystemClock.UtcNow)
                        return false;
                    //or update a expired one
                    _memory.AddOrUpdate(entry.Key, entry, (k, cacheEntry) => entry);
                }
            }
```

**Comment by catcherwong** [comment]
There are some additional operations for `Add`.

**Comment by nicoxiang** [comment]
Yes, and for me these additional operations are strange :(

**Comment by catcherwong** [comment]
Apologies for the method name to mislead you. 😂

More attention next time I'll name the method!

**Comment by catcherwong** [comment]
I will close this issue, if you have any other issues about this problem, reopen this issue or open a new issue 😄
