### ISSUE TITLE
缓存aop使用实体类作为参数失效

### ISSUE THREAD

**Issue by xueandfeng** [dotnetcore/EasyCaching#124]
https://github.com/dotnetcore/EasyCaching/tree/master/src/EasyCaching.Interceptor.Castle
我使用这个项目的时候，业务接口的参数为实体类的时候，返回缓存的数据都是最初始的一条返回。

**Comment by catcherwong** [comment]
@xueandfeng Thanks for your interest in this project.

I apologize for the late reply to you very much!

If you want to use the model entity as the param for your method, you should make the entity implement `ICachable` to tell how to generate cache key.

https://github.com/dotnetcore/EasyCaching/blob/1a7f2a7c25dbc8748adac9095be258cbd956272f/src/EasyCaching.Core/Interceptor/ParameterCacheKeys.cs#L10-L19
