### ISSUE TITLE
Castle 缓存不生效

### ISSUE THREAD

**Issue by arhularm** [dotnetcore/EasyCaching#128]
以下2段代码 
用AspectCore能正常缓存有效
return services.ConfigureAspectCoreInterceptor(options =>
{
     options.CacheProviderName = "default";
});
用Castle 缓存无效
return services.ConfigureCastleInterceptor(options =>
{
       options.CacheProviderName = "defalut";
 });
版本0.56

**Comment by catcherwong** [comment]
@arhularm  Thanks for your interest in this project.

Could you please provide more information about your question? such as the provider configuration of EasyCaching.

**Comment by catcherwong** [comment]
Closed this issue, if you still have some question, please reopen or open a new issue.

**Comment by DUWENINK** [comment]
this question is always on
