### ISSUE TITLE
关于热key的解决方法

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/EasyCaching#132]
实际开发中，我们常常会需要使用多级缓存。

一种常见的情况是，你有一个分布式式缓存服务器，例如redis，独立的缓存服务器能够让我们的多个系统应用程序都能够共享这些缓存的数据，因为这些缓存项的创建是昂贵的。

和访问数据库相比，分布式缓存速度较快，但是和内存相比，还是不够快。因为分布式缓存使用还需要序列化和网络传输的时间消耗。

这个时候里，做个分级缓存是个好的解决方案，将内存缓存结合分布式缓存使用，使用频率高的数据直接从内存中读取，这将大大提高应用程序的整体性能。

使用内存缓存的读取速度能够达到分布式缓存的100倍，甚至更高。

-----------------------------

比如一个key，访问频率达到一个阈值，就放入memorycache

![{5B066EC2-5C1A-5AE1-4CEC-65440C506DF9}](https://user-images.githubusercontent.com/16286519/61121139-16d9bf80-a4d1-11e9-8ee1-ecbff06f1ddd.jpg)

比如如图的配置，内存中60秒过期，但会同步至redis

如果你60s内一直有访问这个key，就一直从内存加载

EasyCaching 是否可以做一个策略，支持多级缓存的读取，解决热key的效率问题。

**Comment by catcherwong** [comment]
@2881099  Thanks for your interest in this project.

Hybrid caching provider supports multi level caching. 

When getting a key from hybrid caching provider,  it will read from memory caching at first, if it can not get the data from memory,  it will read from distributed caching. 

If it get the data from distributed caching, it also will add the data to the memory caching with 
the expiration of distributed caching or a special value that you can configure.
