### ISSUE TITLE
EasyCaching.CSRedis Use exception for the first time:Connection was not opened

### ISSUE THREAD

**Issue by 491134648** [dotnetcore/EasyCaching#134]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1. 
EasyCaching.CSRedis Use exception for the first time:Connection was not opened,The second reuse is normal, connected to Ali Yun redis, is there a warm-up problem?

2. 

### Related code

```
  return _factory.GetCachingProvider(EasyCachingConstValue.DefaultCSRedisName).Get<PathModel>(pathKey, () =>
                        {
                            PathModel data = _studentService.GetPath(package.SId, package.PNo);
                            return data;
                        }, TimeSpan.FromDays(1))?.Value;
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Provider    : InMemory (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : windows 10 x64

**Comment by catcherwong** [comment]
@491134648  Thanks for your interest in this project.

Based on your description, it seems that your redis server startup after your application.  You can have a check for this one. 😄

**Comment by 491134648** [comment]
My integration code
`public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
            services.UseLog4net();
            services.AddTransient<IMQSubscriber, HeartSubscriber>();
            services.Configure<ServerOptions>(Configuration.GetSection("ServerOptions"));
            //configuration
            services.AddEasyCaching(options =>
            {
                options.UseInMemory(Configuration);
                options.UseCSRedis(Configuration);
                //.WithMessagePack()//with messagepack serialization
            });

            //pushOptions.ServiceIp = Helper.InternalNetworkIpAddress();
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
  
            var builder = new ContainerBuilder();
            builder.Populate(services);
            DI.Current = builder.Build();
            return new AutofacServiceProvider(DI.Current);
        }
 public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseEasyCaching();
            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Hello World!");
            });
        }
`

**Comment by 491134648** [comment]
I am currently using Consumer under the User Service, there will be an initialization error, but after I call edit edited under HomeController, and then back to consumer usage under the User Service is normal, should be an initialization exception
`public class HomeController : Controller
    {
        private readonly IEasyCachingProviderFactory _factory;
        private readonly ILogger _logger;
        public HomeController(IEasyCachingProviderFactory factory,
            ILogger<HomeController> logger)
        {
            this._factory = factory;
            _logger = logger;
        }
}`

**Comment by catcherwong** [comment]
@491134648  Could you please provide a simple demo to reproduce your problem?

**Comment by 491134648** [comment]
`public class DI
    {
        public static IContainer Current { get; set; }
        /// <summary>
        /// 解析指定类型的实例
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <returns></returns>
        public static T GetService<T>()
        {
            return Current.Resolve<T>();
        }
        public static bool IsRegistered<T>()
        {
            return Current.IsRegistered<T>();
        }

        public static bool IsRegistered<T>(string key)
        {
            return Current.IsRegisteredWithKey<T>(key);
        }

        public static bool IsRegistered(Type type)
        {
            return Current.IsRegistered(type);
        }

        public static bool IsRegisteredWithKey(string key, Type type)
        {
            return Current.IsRegisteredWithKey(key, type);
        }

        public static T GetService<T>(string key)
        {

            return Current.ResolveKeyed<T>(key);
        }

        public static object GetService(Type type)
        {
            return Current.Resolve(type);
        }

        public static object GetService(string key, Type type)
        {
            return Current.ResolveKeyed(key, type);
        }
    }`
`
using System;
using Autofac;
using Autofac.Extensions.DependencyInjection;
using EasyCaching.Core;
using EasyCaching.CSRedis;
using EasyCaching.InMemory;
using EasyCaching.Serialization.MessagePack;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using MTCardServer.Services;
using WebApplication10.Services;

namespace WebApplication10
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
            //configuration
            services.AddEasyCaching(options =>
            {
                options.UseInMemory(Configuration);
                //options.UseRedis(Configuration);
                options.UseCSRedis(Configuration)
                .WithMessagePack();
            });
            services.AddHostedService<CheckHisotryService>();
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            var builder = new ContainerBuilder();
            builder.Populate(services);
            DI.Current = builder.Build();
            return new AutofacServiceProvider(DI.Current);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();
            app.UseEasyCaching();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}
`
`public class CheckHisotryService : BackgroundService
    {
        private readonly ILogger _logger;
        private Timer _timer;
        private readonly IEasyCachingProviderFactory _factory;
        private readonly IEasyCachingProvider _redisProvider;
        private readonly IEasyCachingProvider _memoryProvider;
        public CheckHisotryService(ILogger<CheckHisotryService> logger
            , IEasyCachingProviderFactory factory)
        {
            _logger = logger;
            _factory = factory;
            _memoryProvider = _factory.GetCachingProvider(EasyCachingConstValue.DefaultInMemoryName);
            _redisProvider = _factory.GetCachingProvider(EasyCachingConstValue.DefaultCSRedisName);
        }
        protected override Task ExecuteAsync(CancellationToken stoppingToken)
        {
            _timer = new Timer(DoWork, null, TimeSpan.FromSeconds(10), TimeSpan.FromSeconds(60));
            return Task.CompletedTask;
        }

        private void DoWork(object state)
        {
            try
            {
                //IEasyCachingProviderFactory _factory = DI.GetService<IEasyCachingProviderFactory>();
                //IEasyCachingProvider _redisProvider = _factory.GetCachingProvider(EasyCachingConstValue.DefaultCSRedisName);
                _redisProvider.Get<string>($"TEST_{Guid.NewGuid().ToString("n")}");
            }catch(Exception ex)
            {
                throw ex;
            }
           
        }

        public override void Dispose()
        {
            base.Dispose();
            _timer?.Dispose();
        }
    }`

**Comment by catcherwong** [comment]
Hey, I also can not reproduce your problem based on your code above. 😂😂

Here is the sample based on your code that runs well, maybe you can follow it.

https://github.com/catcherwong-archive/2019/tree/master/07/EDemo

**Comment by 491134648** [comment]
Time-out time set long point seems to be on it
