### ISSUE TITLE
升级到0.6之后Autofac出错了。

### ISSUE THREAD

**Issue by qcjxberin** [dotnetcore/EasyCaching#136]
![image](https://user-images.githubusercontent.com/5792218/61993713-4298a000-b0a2-11e9-887d-5583a11535c2.png)

**Comment by catcherwong** [comment]
@qcjxberin  Thanks for your interest in this project.

Could you please provider more information for this problem? I can not understand what happen here.

**Comment by SunGram** [comment]
加WithJson()，抛出类似错误

**Comment by catcherwong** [comment]
@SunGram Thanks for the feedback, I'll take a look ASAP.

**Comment by catcherwong** [comment]
@qcjxberin  I notice that the exception was threw by `Single` method.

https://github.com/dotnetcore/EasyCaching/blob/aec41a2dc5c2702178429d551b9017cf49d326a9/src/EasyCaching.CSRedis/DefaultCSRedisCachingProvider.cs#L54-L73

Is the name of your client or serializer not existed?

**Comment by catcherwong** [comment]
@SunGram 

After version v0.6.0, EasyCaching supports named serializer, as default, the name of provider and serializer should be the same! If not, EasyCaching will use `DefaultBinaryFormatterSerializer` instead!

**Comment by qcjxberin** [comment]
是需要在StartUp配置项里增加什么配置吗？

**Comment by catcherwong** [comment]
Just specify the name of your serializer that same as your provider's name.

```cs
            services.AddEasyCaching(option =>
            {
                option.UseRedis(config =>
                {
                    config.DBConfig.Endpoints.Add(new ServerEndPoint("127.0.0.1", 6379));
                    config.DBConfig.Database = 5;
                }, "myredis")                
                ;

                // three serializers
                option
                    .WithJson("json-name")
                    .WithMessagePack("msgpack-name")
                    .WithMessagePack("myredis") // based on the settings of UseRedis, the serializers that named myredis will be use.
                    ;
            });
```

**Comment by qcjxberin** [comment]
有没有CSRedis的最新使用方法？

**Comment by catcherwong** [comment]
In version v0.6.1

```cs
            services.AddEasyCaching(option =>
            {
                option.UseCSRedis(config =>
                {
                    config.DBConfig.ConnectionStrings = new List<string> { "" };
                    // specify use which serializer 
                    config.SerializerName = "msgpack-name";
                }, "myredis")
                ;

                // serializers
                option
                    .WithMessagePack("msgpack-name")
                    .WithMessagePack("myredis") 
                    ;
            });
```

**Comment by qcjxberin** [comment]
谢谢，我试一试。其他调用的方法还是没有变吧。

**Comment by qcjxberin** [comment]
.WithJson("json-name")  这一个好像找不到引用方法

**Comment by catcherwong** [comment]
```
dotnet add package EasyCaching.Serialization.Json --version 0.6.1
```

**Comment by qcjxberin** [comment]
谢谢
