### ISSUE TITLE
is it posible to use it in console app?

### ISSUE THREAD

**Issue by Sephit** [dotnetcore/EasyCaching#142]
It is implemented with IServiceCollection but how to use it with console app?

**Comment by catcherwong** [comment]
@Sephit Thanks for your interest in this project.

If you want to use EasyCaching in a console app, I suggest you use [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2).

**Comment by Sephit** [comment]
Thanks for the advice but what about WPF or Winforms, do i have to implement the .NET Generic Host too? is there any EasyCaching Factory i can use to avoid that way?

**Comment by catcherwong** [comment]
At this time, it has some dependencies mainly for ASP.NET Core, because too many people develop web apps.

And I will try to remove them and keep it separated. 😂

See #127

**Comment by Sephit** [comment]
There are a lot of software that was made on winforms to desktop platforms and a lot business that still required offline applications or portable apps. Actually, medium and big companies around this part of the globe prefers desktop oriented than web based apps (custom erp, crm, etc related to this kind of apps). It would be awesome to keep it separated or platform independent.

**Comment by catcherwong** [comment]
Yes, you are right! This should be improved.

Do you have any suggestion on the separation?

**Comment by catcherwong** [comment]
v0.8.0 make a separation from ASP.NET Core. EasyCaching can support Console App now .

Following this sample [EasyCaching.Demo.ConsoleApp](https://github.com/dotnetcore/EasyCaching/tree/master/sample/EasyCaching.Demo.ConsoleApp)
