### ISSUE TITLE
GetByPrefix on HybridCache

### ISSUE THREAD

**Issue by RaminMT** [dotnetcore/EasyCaching#143]
Hi, thanks for such nice library it's very useful and also easy to use.
I gonna ask why the HybridCache misses the `GetByPrefix` and `GetByPrefixAsync` methods? and Is it possible to add those methods to HybridCache as it has `RemoveByPrefix`?

**Comment by catcherwong** [comment]
@RaminMT  Thanks for your interest in this project.

> I gonna ask why the HybridCache misses the `GetByPrefix` and `GetByPrefixAsync` methods?

Those two methods are removed in v0.5.0.  At that time, I redesign the API of HybridCache, and keep the API easier! And I do not meet a situation that we will use those two methods. So I remove them.

> Is it possible to add those methods to HybridCache as it has RemoveByPrefix?

Certainly! If someone needs those methods, we may add them to HybridCache.

**Comment by RaminMT** [comment]
Thanks for your reply
I checked the source and saw those two methods
Actually we used to store some data on Redis and sometimes we fetched them all by a key pattern, but now we started to use HybridCache to push our system reliability and stability to newer level but we miss this functionality.
I made my hands dirty a bit to bring a pull request, I'm done but it seems a bit complicated to implementing such a feature, I saw the past implementation but I think it's a bit buggy as it checked Redis while it find a record without value. But in our case we need every single item stored in Redis so maybe that's not a use case for that method
