### ISSUE TITLE
Bus multiple subscriptions when all messages are subscribed to the last subscription event

### ISSUE THREAD

**Issue by 491134648** [dotnetcore/EasyCaching#144]
When I use bus. When Subscribe subscribes to multiple services, all messages by default arrive as the last time they go,
For example: I subscribed to "B12" and "b06" in turn, but when the message came, I went to The Onmessage of B06
`
     pushOptions.ServiceName = "B12";
            string cardName = "B06";
            lifetime.ApplicationStarted.Register(() =>
            {

                bus.Subscribe(pushOptions.ServiceName, a =>
                {
                    
                });
                bus.Subscribe(cardName, a =>
                {
                    
                    if (a.Content.HasValue())
                    {
                        if (a.Channel == cardName)
                        {
                            BusCardEvent b04PackageDto = a.Content.Deserialize<BusCardEvent>();
                            DI.GetService<IMQSubscriber>().Handler(b04PackageDto);
                        }
                        else if(a.Channel== pushOptions.ServiceName)
                        {
                            B04PackageDto b04PackageDto = a.Content.Deserialize<B04PackageDto>();
                            DI.GetService<IMQSubscriber>().Handler(b04PackageDto);
                        }
                       
                    }
                });
                Task.Factory.StartNew(() =>
                {
                    Thread.Sleep(5000);
                    bus.Publish(cardName, new EasyCachingMessage()
                    {
                        
                    });
                    bus.Publish(pushOptions.ServiceName, new EasyCachingMessage()
                    {
                        
                    });
                });
               
            });
`

**Comment by catcherwong** [comment]
@491134648  Thanks for your interest in this project.

Do you use the bus without `HybridCache`?  

The bus of EasyCaching is not a common thing that should not be used independently. 😄
