### ISSUE TITLE
HybirdCacheProvider waiting too long time while redis is unavailable.

### ISSUE THREAD

**Issue by siegrainwong** [dotnetcore/EasyCaching#149]
If I close the Redis service first then launch the application and request a cached api, the response time would be too long, almost 25s or more.

I tried these but seems not working:
1. HybridCachingOptions.DefaultExpirationForTtlFailed
2. Set connectTimeout of csredis connectionstring
3. Set syncTimeout of csredis connectionstring

Have any other idea how to shorten this time?
Thanks.

**Comment by catcherwong** [comment]
@siegrainwong  Thanks for your interest in this project.

I think EasyCaching can not solve this problem if the driver does not support this feature.
