### ISSUE TITLE
V0.6.1 - System.InvalidOperationException: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by jeroenpot** [dotnetcore/EasyCaching#151]
## Description

Since today we get a error in our logs:
 -> EasyCaching.Core.DefaultEasyCachingProviderFactory -> λ:EasyCaching.Core.IEasyCachingProvider[] -> λ:EasyCaching.Core.IEasyCachingProvider. ---> System.InvalidOperationException: Sequence contains more than one matching element
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
at EasyCaching.CSRedis.DefaultCSRedisCachingProvider..ctor(String name, IEnumerable`1 clients, IEnumerable`1 serializers, RedisOptions options, ILoggerFactory loggerFactory)
at EasyCaching.CSRedis.RedisOptionsExtension.<AddServices>b__3_1(IServiceProvider x)
at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)

I saw some fixes, so we upgraded from 0.5.6 to 0.6.1 and implemented the bootstrap changes that are mentioned here:
https://github.com/dotnetcore/EasyCaching/issues/136
That seemed to work, but after a few hours we got the problem back (or another problem)

The strange part is that this has been running stable for quite some time and without any code changes this problem all of a sudden is popping up.

### Steps to Reproduce

I don't have that.. it runs fine for hours and then pops up in our lambda functions, locally i haven't been able to reproduce it, and even on the servers it doesn't always show up.

### Related code
I think the error is here, but i don't understand why there would be more then one client available, since we register only one connections, one time as read, one time as write with a different name. also there is only one serializer registered.

![image](https://user-images.githubusercontent.com/1733387/66212045-781ec280-e6bd-11e9-9c14-941d1064d34e.png)

Changing the code to First instead of Single would fix it, but not sure if that is the best way to go.

```
This is how we register:
services.AddEasyCaching(option =>
			{
				var protobufSerializer = "protobuf-serializer";
				option.WithProtobuf(protobufSerializer);
				option.UseCSRedis(
					config =>
				{
					config.EnableLogging = redisCacheOptions.EnableLogging;
					config.MaxRdSecond = redisCacheOptions.MaxRdSecond;
					config.DBConfig.ConnectionStrings = redisCacheOptions.WritableConnections.Select(CreateConnectionString).ToList();
					config.SerializerName = protobufSerializer;
				}, "RedisWritableConnections");

				var readOnlyConnections = new List<string>();
				readOnlyConnections.AddRange(redisCacheOptions.ReadOnlyConnections.Count > 0
					? redisCacheOptions.ReadOnlyConnections.Select(CreateConnectionString).ToList()
					: redisCacheOptions.WritableConnections.Select(CreateConnectionString).ToList());

				option.UseCSRedis(
					config =>
					{
						config.EnableLogging = redisCacheOptions.EnableLogging;
						config.MaxRdSecond = redisCacheOptions.MaxRdSecond;
						config.DBConfig.ConnectionStrings = readOnlyConnections;
						config.SerializerName = protobufSerializer;
					}, name: "RedisReadOnlyConnections");
			});
```

**Expected behavior:** 
That is gets a client and we can read/write from/to cache

**Actual behavior:** 
It throws an exception. 

## Specifications

- Provider    : CSRedis (version 0.6.1)
- Serializer  : ProtoBuf
- System      : AWS Lambda

**Comment by catcherwong** [comment]
@jeroenpot  Thanks for your interest in this project.

> Sequence contains more than one matching element

It seems that there were more than one client have same name.

> Changing the code to First instead of Single would fix it, but not sure if that is the best way to go.

`Single` could prevent some providers with the same name.  

Based on the related code you show, all things will go well. I am not familiar with AWS Lambda, are there something different with traditional systems? 

Or could you please share a simple sample for this problem so that I can check for it. 😄

**Comment by jeroenpot** [comment]
Sadly no, it only fails currently on our Lambda, but not all the time.. it has run fine for months.. now the problem showed, we updated to 0.6.1 and it ran fine for almost 3 hours, then the problem showed again.. I'm going to build in some logging to see if i can get some more details.

**Comment by jeroenpot** [comment]
This is my logging attempt.. will let you know if it surfaces again and what the outcome is.
![image](https://user-images.githubusercontent.com/1733387/66212583-773a6080-e6be-11e9-8247-cbd29b171652.png)

**Comment by jeroenpot** [comment]
Ok, we have some logging:
"Message":"Failed. There are 4 EasyCachingCSRedisClient registered. Their names are RedisWritableConnections,RedisReadOnlyConnections,RedisWritableConnections,RedisReadOnlyConnectionsThere are 2 IEasyCachingSerializer registered. Their names are protobuf-serializer,protobuf-serializer"

So i have no clue how this can happen, i made a piece of test code that would do a duplicate registration in the dependency inject settings, so to see if i could catch and prevent it from happening, but it already crashes at registering. This execption in the running AWS Lambda has already passed that registration fase, and is resolving the dependency... 

So i'm not sure this is even a problem of this library or not, but i need to find a way around the problem. 

Can you make a code change to change it to First instead of Single
Or can i somehow use a custom implementation of DefaultCSRedisCachingProvider where i do that myself? Any help is highly appreciated

**Comment by catcherwong** [comment]
> Or can i somehow use a custom implementation of DefaultCSRedisCachingProvider where i do that myself?

Yes, you can write and use a custom implementation. 

All of the providers should implement `IEasyCachingProvider` or `EasyCachingAbstractProvider`.

`IEasyCachingProvider` is a base interface, and `EasyCachingAbstractProvider` is an abstract class that contains `DiagnosticListener`.

After adding your own implementation, you should add an options extension class implements `IEasyCachingOptionsExtension` that tells EasyCaching how to register.

> Any help or other suggestions to fix / work around this is highly appreciated

Maybe write a custom provider is better to adapt to your problem.

**Comment by jeroenpot** [comment]
I will try to make a custom implementation. Thank you for the information.

**Comment by catcherwong** [comment]
Close this issue. If you also have some problem, reopen it or open a new one. 😄
