### ISSUE TITLE
.NET CORE 2.2无法安装

### ISSUE THREAD

**Issue by liugt34** [dotnetcore/EasyCaching#155]
![image](https://user-images.githubusercontent.com/8056013/66646972-3c09d580-ec5a-11e9-9c6e-ed2833233323.png)

如图，为啥2.2的框架要引用3.0的dll呢？

**Comment by catcherwong** [comment]
@liugt34 Thanks for your interest in this project.

For .NET Core 2.2, you should use a version **below** 0.8.0.

In version 0.8.0, EasyCaching upgraded the dependencies in order to support .NET Core 3.0
