### ISSUE TITLE
缓存的值不过期，那么set方法如何传值？

### ISSUE THREAD

**Issue by yuandong618** [dotnetcore/EasyCaching#165]
## Description
set方法的过期时间是必传值，形如provider.Set("demo", "123", TimeSpan.FromMinutes(1));
如果想让缓存值一直驻留内存，那么set方法的第三个参数过期时间字段应该如何传值呢？

**Comment by catcherwong** [comment]
@yuandong618 Thanks for your interest in this project.

cc #90
