### ISSUE TITLE
HybirdCachingProvider类中带参数的get方法的一些疑问？

### ISSUE THREAD

**Issue by squarezx** [dotnetcore/EasyCaching#168]
在HybirdCachingProvider类中，方法public async Task<CacheValue<T>> GetAsync<T>(string cacheKey, Func<Task<T>> dataRetriever, TimeSpan expiration)在执行完成后会在分布式缓存中设置对应的缓存而没有在本地缓存中设置，请问这个方法如何使用？后续如何在本地缓存中设置？

**Comment by catcherwong** [comment]
@squarezx Thanks for your interest in this project.

We don't reset the value local cache now. Maybe this should be improved here 😄

**Comment by squarezx** [comment]
ok

**Comment by catcherwong** [comment]
v0.8.1 makes some changes to this issue.
