### ISSUE TITLE
V0.6.1 抛异常：Sequence contains no matching element

### ISSUE THREAD

**Issue by squarezx** [dotnetcore/EasyCaching#169]
## Description

代码中只要添加了 options.WithJson();这行代码，就会抛出异常：Autofac.Core.DependencyResolutionException,System.InvalidOperationException 
   An exception was thrown while activating BasicService.WebApi.Apis.DiagnosisDicController -> BasicService.Application.Services.Implementations.DiagnosisDicService -> EasyCaching.HybridCache.HybridCachingProvider -> EasyCaching.Core.DefaultEasyCachingProviderFactory -> λ:EasyCaching.Core.IEasyCachingProvider[] -> λ:EasyCaching.Core.IEasyCachingProvider.
Sequence contains no matching element

### Related code
            services.AddEasyCaching(options =>
            {
                //使用json进行序列化
                options.WithJson();

                //添加一个内存缓存
                options.UseInMemory(config =>
                {
                    config.DBConfig = new InMemoryCachingOptions
                    {
                        // scan time, default value is 60s
                        ExpirationScanFrequency = 60,
                        // total count of cache items, default value is 10000
                        SizeLimit = 100
                    };
                    // the max random second will be added to cache's expiration, default value is 120
                    config.MaxRdSecond = 120;
                    // whether enable logging, default is false
                    config.EnableLogging = true;
                    // mutex key's alive time(ms), default is 5000
                    config.LockMs = 5000;
                    // when mutex key alive, it will sleep some time, default is 300
                    config.SleepMs = 300;
                }, "BaseServiceInMemory");

                //添加一个Redis缓存
                options.UseCSRedis(config =>
                {
                    config.DBConfig = new CSRedisDBOptions
                    {
                        ConnectionStrings = new List<string>
                        {
                            "172.17.200.73:6379,password=suha@2018"
                        }
                    };
                    config.EnableLogging = true;
                }, "BaseServiceCSRedis");

                //添加一个混合缓存
                options.UseHybrid(config =>
                {
                    config.TopicName = "Caching-BaseService";
                    config.EnableLogging = false;

                    // specify the local cache provider name after v0.5.4
                    config.LocalCacheProviderName = "BaseServiceInMemory";
                    // specify the distributed cache provider name after v0.5.4
                    config.DistributedCacheProviderName = "BaseServiceCSRedis";

                    config.EnableLogging = true;
                })
                .WithRabbitMQBus(config =>
                 {
                     var rabbitConfig = Configuration.GetSection("RabbitOptions");
                     config.HostName = rabbitConfig.GetValue<string>("HostName");
                     config.VirtualHost = "/";
                     config.UserName = rabbitConfig.GetValue<string>("UserName");
                     config.Password = rabbitConfig.GetValue<string>("Password");
                     config.QueueName = "BaseService-Caching";
                 });
            });

**Comment by catcherwong** [comment]
@squarezx  Thanks for your interest in this project.

Can you provide more information for the exception? such as StackTrace.

And `v0.6.1` should specify the `SerializerName` for csredis provider. 

You can follow this link to find more information.

https://github.com/dotnetcore/EasyCaching/wiki/%E7%BC%93%E5%AD%98%E7%9A%84%E5%BA%8F%E5%88%97%E5%8C%96

If it can not solve your problem, can you provide a sample to reproduce it?

**Comment by squarezx** [comment]
问题已解决，谢谢

**Comment by siegrainwong** [comment]
@squarezx 怎么解决的？我也是这个问题。
