### ISSUE TITLE
Redisbus subscribes more to all callback handler action will only go to the last handle action

### ISSUE THREAD

**Issue by 491134648** [dotnetcore/EasyCaching#170]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1. 
 bus.Subscribe(pushOptions.ServiceName, a =>
                {

                });
                bus.Subscribe(cardName, a =>
                {

                    if (a.Content.HasValue())
                    {
                        if (a.Channel == cardName)
                        {
                            BusCardEvent b04PackageDto = a.Content.Deserialize<BusCardEvent>();
                            DI.GetService<IMQSubscriber>().Handler(b04PackageDto);
                        }
                        else if (a.Channel == pushOptions.ServiceName)
                        {
                            B04PackageDto b04PackageDto = a.Content.Deserialize<B04PackageDto>();
                            DI.GetService<IMQSubscriber>().Handler(b04PackageDto);
                        }
                    }
                    else
                    {
                        Console.WriteLine("Subscribe content is empty:" + a.Channel);
                    }
                });
                bus.Publish(pushOptions.ServiceName, new EasyCachingMessage()
                {
                    //Content = pushOptions.ServiceName
                });
2. 
All subscription message notifications will go to the last handler
 bus.Subscribe(cardName, a =>
                {

                    if (a.Content.HasValue())
                    {
                        if (a.Channel == cardName)
                        {
                            BusCardEvent b04PackageDto = a.Content.Deserialize<BusCardEvent>();
                            DI.GetService<IMQSubscriber>().Handler(b04PackageDto);
                        }
                        else if (a.Channel == pushOptions.ServiceName)
                        {
                            B04PackageDto b04PackageDto = a.Content.Deserialize<B04PackageDto>();
                            DI.GetService<IMQSubscriber>().Handler(b04PackageDto);
                        }
                    }
                    else
                    {
                        Console.WriteLine("Subscribe content is empty:" + a.Channel);
                    }
                });

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]
Can i execute different callback handle actions for different actions

**Actual behavior:** [What actually happened]

## Specifications

- Provider    : InMemory (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : CentOS 7.2

**Comment by 491134648** [comment]
You can fix this with the following

1.EasyCachingMessage add channel Property
`
public class EasyCachingMessage
    {        
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>The identifier.</value>
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the cache keys.
        /// </summary>
        /// <value>The cache keys.</value>
        public string[] CacheKeys { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:EasyCaching.Core.Bus.EasyCachingMessage"/> is prefix.
        /// </summary>
        /// <value><c>true</c> if is prefix; otherwise, <c>false</c>.</value>
        public bool IsPrefix { get; set; }
        public string Channel { get; set; }
    }
`
2.EasyCachingAbstractBus add Dictionary  Dictionary<string, Action<EasyCachingMessage>> 
`
protected readonly Dictionary<string, Action<EasyCachingMessage>> onMessageDic = null;
public EasyCachingAbstractBus()
        {
            onMessageDic = new Dictionary<string, Action<EasyCachingMessage>>();
        }
 public void Subscribe(string topic, Action<EasyCachingMessage> action)
        {
            lock (lockObj)
            {
                if (onMessageDic.ContainsKey(topic))
                {
                    onMessageDic[topic] = action;
                }
                else
                {
                    onMessageDic.Add(topic, action);
                }
            }
            _handler = action;
            BaseSubscribe(topic, action);
        }
 public virtual void BaseOnMessage(EasyCachingMessage message)
        {
            var operationId = s_diagnosticListener.WriteSubscribeMessageBefore(new BeforeSubscribeMessageRequestEventData(message));
            Exception e = null;
            try
            {
                if (onMessageDic.ContainsKey(message.Channel))
                {
                    onMessageDic[message.Channel]?.Invoke(message);
                }
                else
                {
                    _handler?.Invoke(message);
                }
               
            }
            catch (Exception ex)
            {
                e = ex;
                throw;
            }
            finally
            {
                if (e != null)
                {
                    s_diagnosticListener.WritePublishMessageError(operationId, e);
                }
                else
                {
                    s_diagnosticListener.WritePublishMessageAfter(operationId);
                }
            }
        }
`
3. Each message implementation increases the channel
redis:
`
 /// <summary>
        /// Subscribes the handle.
        /// </summary>
        /// <param name="channel">Channel.</param>
        /// <param name="value">Value.</param>
        private void OnMessage(RedisChannel channel, RedisValue value)
        {
            var message = _serializer.Deserialize<EasyCachingMessage>(value);
            message.Channel = channel;
            BaseOnMessage(message);
        }
`
csredis:
`
/// <summary>
        /// Subscribe the specified topic and action.
        /// </summary>
        /// <param name="topic">Topic.</param>
        /// <param name="action">Action.</param>
        public override void BaseSubscribe(string topic, Action<EasyCachingMessage> action)
        {
            _client.Subscribe(
                (topic, msg =>
                {
                    OnMessage(msg.Body,msg.Channel);
                })
            );
        }

        /// <summary>
        /// Ons the message.
        /// </summary>
        /// <param name="body">Body.</param>
        /// <param name="channel">channel.</param>
        private void OnMessage(string body,string channel)
        {
            var message = JsonConvert.DeserializeObject<EasyCachingMessage>(body);
            message.Channel = channel;
            BaseOnMessage(message);
        }
`
rabbitmq:
`
  /// <summary>
        /// Ons the message.
        /// </summary>
        /// <param name="sender">Sender.</param>
        /// <param name="e">E.</param>
        private void OnMessage(object sender, BasicDeliverEventArgs e)
        {
            var message = _serializer.Deserialize<EasyCachingMessage>(e.Body);
            message.Channel = e.RoutingKey;
            BaseOnMessage(message);
        }
`

**Comment by catcherwong** [comment]
@491134648 Thanks for your interest in this project.

You can send a PR for your change, and we will have a look ASAP.

**Comment by catcherwong** [comment]
Close this issue. If you also have some problems, reopen it or open a new one. 😄
