### ISSUE TITLE
Question: Stream support?

### ISSUE THREAD

**Issue by gingters** [dotnetcore/EasyCaching#171]
Would it be possible to store potentially large binary contents in the cache using async methods and streams?

Reason being, if you have to completely load streams into a `byte[]` before storing to the cache, or reading a complete `byte[]` from the cache, that has a huge impact of memory usage of your process. 
Example: temporary storage of a web upload (i.e. large PDF) in redis or memcached, for another service to process afterwards, while we don't want our web api to hold the complete upload data in memory at one point in time.

If one could use `.CopyToAsync()` in both directions, then the stream contents could be written to and read from the cache while only a small portion of the data is buffered is in local memory, while the process would be able to process other tasks until the upload operation is completed.

Would that be possible?

**Comment by catcherwong** [comment]
@gingters Thanks for your interest in this project.

We can store the binary contents in the cache using async methods but streams.

`byte[]` seems more universal for the storage rather than `Stream`, and does Redis and Memcached support store stream directly?

**Comment by catcherwong** [comment]
Close this issue. If you also have some problem, reopen it or open a new one. 😄
