### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by Sephit** [dotnetcore/EasyCaching#172]
We the newly introduced console support, could you update the documentation for this new features?

**Comment by catcherwong** [comment]
@Sephit Thanks for your interest in this project.

Sorry for the delay of documentation, I will update the documentation when I am free.

And here is a sample that you can follow in the repo.

https://github.com/dotnetcore/EasyCaching/tree/master/sample/EasyCaching.Demo.ConsoleApp

**Comment by catcherwong** [comment]
Updated.

https://easycaching.readthedocs.io/en/latest/
