### ISSUE TITLE
Aop 缓存怎么删除呢？

### ISSUE THREAD

**Issue by lixiong123** [dotnetcore/EasyCaching#176]
[EasyCachingAble(Expiration = 100)]
        string GetCurrentUtcTime();

如果有依赖，联动，如何删除 GetCurrentUtcTime() 这个方法的缓存呢？

**Comment by catcherwong** [comment]
@lixiong123 Thanks for your interest in this project.

On the one hand, when trigger the operation of delete in one application, you can use `EasyCachingEvict`.

```cs
    [EasyCachingAble(Expiration = 10, CacheKeyPrefix = "YourPrefix")]
    string GetCurrentUtcTime();

    [EasyCachingEvict(IsBefore = true, CacheKeyPrefix = "YourPrefix")]
    void DeleteSomething();
```

When you call `DeleteSomething` it will delete the cached item via the cached item's key.

> NOTE: If you want to delete some cached item with AOP's way, you should combine with `CacheKeyPrefix` due to the default implement of key generator. When you do not specify the `CacheKeyPrefix`, the key will contain the method info.

https://github.com/dotnetcore/EasyCaching/blob/132a38d0772f9cf33a5e91ce5a935e2032932289/src/EasyCaching.Core/Interceptor/DefaultEasyCachingKeyGenerator.cs#L23-L31

On the other hand, if you need to delete the cached item via another application, such as the manager platform, you should understand how the rule of key generator, and delete them by yourself.
