### ISSUE TITLE
ResponseCaching  不起作用

### ISSUE THREAD

**Issue by hellozhang** [dotnetcore/EasyCaching#179]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1. 例子代码也不起作用
2. 

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Provider    : InMemory (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : CentOS 7.2

**Comment by catcherwong** [comment]
@hellozhang Thanks for your interest in this project.

I will take a look ASAP.

**Comment by catcherwong** [comment]
@hellozhang  How do you test the ResponseCaching?
