### ISSUE TITLE
EasyCaching设置了json序列化无效

### ISSUE THREAD

**Issue by ZdMirLong** [dotnetcore/EasyCaching#184]
在StatUp中设置了json序列化器
![image](https://user-images.githubusercontent.com/30926868/71442736-43f9f180-2742-11ea-8223-ba1470f0a02f.png)
 生成缓存时没有序列化
![image](https://user-images.githubusercontent.com/30926868/71442762-55db9480-2742-11ea-8375-471a5383a6dc.png)

**Comment by catcherwong** [comment]
@ZdMirLong  Thanks for your interest in this project.

EasyCaching stores the data with `byte[]`, not a raw string.

**Comment by ZdMirLong** [comment]
![image](https://user-images.githubusercontent.com/30926868/71452306-c0cab100-27be-11ea-849c-539e6dca5c1e.png)

那文档里面的withjson()有什么作用呢?? 如果我要存储原始串还是需要自己序列化吧?

**Comment by catcherwong** [comment]
`WithJson` means that it will use `Newtonsoft.Json` to serialize the data.

If you want to store the raw string data, you can use `IRedisCachingProvider` rather than `IEasyCachingProvider`.
