### ISSUE TITLE
Slow performance when the cached items count reaches cache size limit

### ISSUE THREAD

**Issue by KostaVlev** [dotnetcore/EasyCaching#185]
We have production site that runs on NopCommerce which uses EasyCaching v.0.5.6 and InMemory() cache. The site was performing terrible and kept going down.
After numerous of tests and investigation the problem was narrowed to the EasyCaching library.

Looking into `InMemoryCaching.cs` the problem seem to be in the condition when the cached items count reach cache size limit

https://github.com/dotnetcore/EasyCaching/blob/master/src/EasyCaching.InMemory/Internal/InMemoryCaching.cs#L130

Running the performance test from the project look good but test performs 1000 iterations.

Changing the Set tests to so we can the saved items to the size limit

            

                [Benchmark]
                public void MS()
                {
                    //_msCache.Set("ms-key", "ms-value", System.TimeSpan.FromSeconds(5));
                    for (int i = 0; i < 1000; i++)
                    {
                        _msCache.Set($"ms-key-{i}", $"ms-value-{i}", System.TimeSpan.FromSeconds(5));
                        //_cache.Set($"ec-key-{i}", $"ec-value-{i}", System.TimeSpan.FromSeconds(5));
                    }
                }

                [Benchmark]
                public void EC()
                {
                    //_cache.Set("ec-key", "ec-value", System.TimeSpan.FromSeconds(5));
                    for (int i = 0; i < 1000; i++)
                    {
                        //_msCache.Set($"ms-key-{i}", $"ms-value-{i}", System.TimeSpan.FromSeconds(5));
                        _cache.Set($"ec-key-{i}", $"ec-value-{i}", System.TimeSpan.FromSeconds(5));
                    }
                }
            

Results 

| Method |        Mean |     Error |     StdDev |     StdErr |         Min |          Q1 |      Median |          Q3 |         Max |     Op/s |   Gen 0 |   Gen 1 | Gen 2 | Allocated |
|------- |------------:|----------:|-----------:|-----------:|------------:|------------:|------------:|------------:|------------:|---------:|--------:|--------:|------:|----------:|
|     MS |    698.6 us |  1.196 us |  0.9989 us |  0.2770 us |    696.4 us |    698.0 us |    698.7 us |    699.6 us |    699.9 us | 1,431.43 | 89.8438 | 44.9219 |     - | 553.91 KB |
|     EC | 23,968.8 us | 55.278 us | 51.7068 us | 13.3506 us | 23,858.4 us | 23,939.4 us | 23,980.6 us | 23,998.7 us | 24,052.3 us |    41.72 | 31.2500 |       - |     - | 303.91 KB |

Then I commented out the problem code

            //if (_memory.Count >= _options.SizeLimit)
            //{
            //    // order by last access ticks 
            //    // up to size limit, should remove 
            //    var oldestList = _memory.ToArray()
            //                       .OrderBy(kvp => kvp.Value.LastAccessTicks)
            //                       .ThenBy(kvp => kvp.Value.InstanceNumber)
            //                       .Take(5)
            //                       .Select(kvp => kvp.Key);

            //    RemoveAll(oldestList);
            //}

Running the test again looks like:

| Method |     Mean |    Error |   StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |    Op/s |   Gen 0 |   Gen 1 | Gen 2 | Allocated |
|------- |---------:|---------:|---------:|----------:|---------:|---------:|---------:|---------:|---------:|--------:|--------:|--------:|------:|----------:|
|     MS | 705.4 us | 3.426 us | 3.205 us | 0.8274 us | 700.9 us | 703.2 us | 704.7 us | 707.5 us | 712.6 us | 1,417.6 | 89.8438 | 44.9219 |     - | 553.91 KB |
|     EC | 737.3 us | 4.130 us | 3.863 us | 0.9974 us | 729.8 us | 733.5 us | 738.8 us | 740.1 us | 742.3 us | 1,356.4 | 48.8281 | 15.6250 |     - | 303.91 KB |

Looks like to me the way how finding the oldest cache is implemented is an issue? 

**Edit:**

Running few more test and most likely `_memory.Count` is part that causes the issue.
Just replacing `_memory.Count`  with `_memory.Skip(0).Count()` as suggested in 
https://stackoverflow.com/questions/41298156/how-to-improve-performance-of-concurrentdictionary-count-in-c-sharp

Results 

| Method |       Mean |    Error |   StdDev |   StdErr |        Min |         Q1 |     Median |         Q3 |        Max |    Op/s |   Gen 0 |   Gen 1 | Gen 2 | Allocated |
|------- |-----------:|---------:|---------:|---------:|-----------:|-----------:|-----------:|-----------:|-----------:|--------:|--------:|--------:|------:|----------:|
|     MS |   700.4 us | 6.210 us | 5.505 us | 1.471 us |   694.5 us |   696.4 us |   699.2 us |   702.1 us |   713.1 us | 1,427.7 | 89.8438 | 44.9219 |     - | 553.91 KB |
|     EC | 6,660.4 us | 8.411 us | 7.867 us | 2.031 us | 6,645.7 us | 6,655.5 us | 6,662.2 us | 6,666.2 us | 6,674.4 us |   150.1 | 54.6875 | 15.6250 |     - | 366.41 KB |

**Comment by catcherwong** [comment]
@KostaVlev  Thanks for your interest in this project. 

I retest this problem again. And I modify the iteration from `1000` to `15000`.

Sample code here.

```cs
[MemoryDiagnoser]
    [AllStatisticsColumn]
    public class SetBenchmark
    {
        private readonly MemoryCache _msCacheWithoutLimit = new MemoryCache(new MemoryCacheOptions() { });

        private readonly MemoryCache _msCache = new MemoryCache(new MemoryCacheOptions() { SizeLimit = 10000, CompactionPercentage = 0.9 });

        private readonly InMemoryCaching _cache =
            new InMemoryCaching(EasyCachingConstValue.DefaultInMemoryName, new InMemoryCachingOptions());

        private readonly MemoryCacheEntryOptions _mOptions = new MemoryCacheEntryOptions()                
                .SetSize(1)                
                .SetAbsoluteExpiration(System.TimeSpan.FromSeconds(5));


        [Benchmark]
        public void MS_WithoutLimit()
        {
            for (int i = 0; i < 15000; i++)
            {
                _msCacheWithoutLimit.Set($"ms-key-out-{i}", "ms-value", System.TimeSpan.FromSeconds(5));
            }
        }

        [Benchmark]
        public void MS_WithLimit()
        {
            for (int i = 0; i < 15000; i++)
            {
                _msCache.Set($"ms-key-{i}", "ms-value", _mOptions);
            }
        }

        [Benchmark]
        public void EC()
        {
            for (int i = 0; i < 15000; i++)
            {
                _cache.Set($"ec-key-{i}", "ec-value", System.TimeSpan.FromSeconds(5));
            }
        }
    }
```

And here is the result

``` ini

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.16299.309 (1709/FallCreatorsUpdate/Redstone3)
Intel Xeon CPU E5-2680 v2 2.80GHz, 1 CPU, 20 logical and 10 physical cores
Frequency=2728177 Hz, Resolution=366.5451 ns, Timer=TSC
.NET Core SDK=3.1.100
  [Host]     : .NET Core 2.2.8 (CoreCLR 4.6.28207.03, CoreFX 4.6.28208.02), 64bit RyuJIT
  DefaultJob : .NET Core 2.2.8 (CoreCLR 4.6.28207.03, CoreFX 4.6.28208.02), 64bit RyuJIT


```
|          Method |        Mean |      Error |     StdDev |    StdErr |         Min |          Q1 |      Median |          Q3 |         Max |    Op/s | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|---------------- |------------:|-----------:|-----------:|----------:|------------:|------------:|------------:|------------:|------------:|--------:|------------:|------------:|------------:|--------------------:|
| MS_WithoutLimit |    31.82 ms |  0.6262 ms |  0.7454 ms | 0.1627 ms |    30.47 ms |    31.09 ms |    32.09 ms |    32.36 ms |    33.42 ms | 31.4231 |   1187.5000 |    625.0000 |    125.0000 |             7.13 MB |
|    MS_WithLimit |    90.25 ms |  3.7823 ms | 11.1522 ms | 1.1152 ms |    61.97 ms |    81.81 ms |    91.57 ms |    98.87 ms |   115.19 ms | 11.0799 |   5166.6667 |   2166.6667 |   1333.3333 |             8.82 MB |
|              EC | 3,487.46 ms | 32.1519 ms | 30.0749 ms | 7.7653 ms | 3,391.94 ms | 3,479.34 ms | 3,495.80 ms | 3,508.66 ms | 3,513.88 ms |  0.2867 | 299000.0000 | 299000.0000 | 299000.0000 |          1493.24 MB |


It really performances bad here!

After commented out the problem code.

``` ini

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.16299.309 (1709/FallCreatorsUpdate/Redstone3)
Intel Xeon CPU E5-2680 v2 2.80GHz, 1 CPU, 20 logical and 10 physical cores
Frequency=2728177 Hz, Resolution=366.5451 ns, Timer=TSC
.NET Core SDK=3.1.100
  [Host]     : .NET Core 2.2.8 (CoreCLR 4.6.28207.03, CoreFX 4.6.28208.02), 64bit RyuJIT
  DefaultJob : .NET Core 2.2.8 (CoreCLR 4.6.28207.03, CoreFX 4.6.28208.02), 64bit RyuJIT


```
|          Method |     Mean |     Error |     StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |       Max |  Op/s | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|---------------- |---------:|----------:|-----------:|----------:|---------:|---------:|---------:|---------:|----------:|------:|------------:|------------:|------------:|--------------------:|
| MS_WithoutLimit | 25.17 ms | 0.4941 ms |  0.9637 ms | 0.1406 ms | 23.17 ms | 24.73 ms | 25.10 ms | 25.89 ms |  27.12 ms | 39.73 |   1187.5000 |    625.0000 |    125.0000 |             7.13 MB |
|    MS_WithLimit | 86.96 ms | 3.7346 ms | 10.8348 ms | 1.1001 ms | 64.90 ms | 79.74 ms | 87.66 ms | 93.65 ms | 114.17 ms | 11.50 |   4285.7143 |   1714.2857 |   1142.8571 |             8.82 MB |
|              EC | 16.67 ms | 0.3330 ms |  0.4330 ms | 0.0884 ms | 15.75 ms | 16.36 ms | 16.77 ms | 16.93 ms |  17.65 ms | 59.99 |    500.0000 |    250.0000 |           - |             3.36 MB |


It seems more better than before.

Not only get the count hurt performance, but also find some keys that should remove.

I will take a look ASAP.

**Comment by KostaVlev** [comment]
@catcherwong looking into [MemoryCache.cs](https://github.com/d-saravanan/Caching/blob/e347eee484dce4a88bdc5997dc74c25e75ae73eb/src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs#L342) implemetaion the size limit logic probably should be moved on a separate thered and for monitoring the cache size using [Interlocked](https://github.com/d-saravanan/Caching/blob/e347eee484dce4a88bdc5997dc74c25e75ae73eb/src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs#L324).

There would be some benefits if `Count` `ToArray()` `Keys` and `Values` are replaced with `.Skip(0).Count()` `.Select(item => item.Key)` or `.Select(item => item.Key)` to avoid blocks as suggested in this [article](https://arbel.net/2013/02/03/best-practices-for-using-concurrentdictionary/)

I probably will be able next days to make those changes and see if this will improve performance.

**Comment by catcherwong** [comment]
@KostaVlev 

I made some changes for this issue.

https://github.com/dotnetcore/EasyCaching/blob/8a4f817c4557cbba9ea195fbcc145af2cedcb01e/src/EasyCaching.InMemory/Internal/InMemoryCaching.cs#L137-L164

Something I changed:

1. Support no limit cache size, this should be the fastest performance.
2. If setting a limit size, it will use `Interlocked` to monitor the count.
3. If up to limit, it will not remove the old cached items for each operations. Just for a few operations  to avoid spends to much time here. 
4. Based on the setting limit size to calculate how many cached items should be removed after up to limit.

Here is the newest result.

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.16299.309 (1709/FallCreatorsUpdate/Redstone3)
Intel Xeon CPU E5-2680 v2 2.80GHz, 1 CPU, 20 logical and 10 physical cores
Frequency=2728177 Hz, Resolution=366.5451 ns, Timer=TSC
.NET Core SDK=3.1.100
  [Host]     : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT
  DefaultJob : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT


```
|          Method |     Mean |    Error |    StdDev |   StdErr |      Min |       Q1 |   Median |        Q3 |       Max |  Op/s |     Gen 0 |     Gen 1 |    Gen 2 | Allocated |
|---------------- |---------:|---------:|----------:|---------:|---------:|---------:|---------:|----------:|----------:|------:|----------:|----------:|---------:|----------:|
| MS_WithoutLimit | 18.96 ms | 0.376 ms |  0.678 ms | 0.106 ms | 17.12 ms | 18.46 ms | 18.94 ms |  19.41 ms |  20.16 ms | 52.74 |  562.5000 |  281.2500 |        - |   7.09 MB |
|    MS_WithLimit | 92.67 ms | 6.863 ms | 20.235 ms | 2.024 ms | 56.66 ms | 74.24 ms | 92.42 ms | 106.39 ms | 134.96 ms | 10.79 | 2500.0000 | 1250.0000 | 750.0000 |  31.28 MB |
| EC_WithoutLimit | 14.61 ms | 0.278 ms |  0.331 ms | 0.072 ms | 14.00 ms | 14.39 ms | 14.70 ms |  14.84 ms |  15.05 ms | 68.46 |  265.6250 |  125.0000 |        - |   3.43 MB |
|    EC_WithLimit | 20.75 ms | 0.401 ms |  0.477 ms | 0.104 ms | 19.96 ms | 20.43 ms | 20.70 ms |  21.06 ms |  21.58 ms | 48.19 |  375.0000 |  187.5000 |        - |   4.69 MB |

**Comment by catcherwong** [comment]
Release v0.8.4 for this issue, If also have some problem, reopen it or open a new issue. 😄
