### ISSUE TITLE
大神,看一下

### ISSUE THREAD

**Issue by suichuan** [dotnetcore/EasyCaching#186]
![image](https://user-images.githubusercontent.com/18475552/71613188-e81ae700-2bdf-11ea-8bf8-8e4adca2d8d2.png)
版本 0.61 ,使用csredis,发现设置了失效时间,尽管时间设置很长,也很快就失效了 ,发现代码红线位置可能又问题, 麻烦大神看一下是不是这个问题

**Comment by catcherwong** [comment]
@suichuan Thanks for your interest in this project.

This is a bug here, should use `(int)expiration.Value.TotalSeconds` to replace `expiration.Value.Seconds`.

**Comment by catcherwong** [comment]
release v0.8.4 for this issue.
