### ISSUE TITLE
How to customize CacheKeyPrefix by parameters?

### ISSUE THREAD

**Issue by visten** [dotnetcore/EasyCaching#187]
I want to delete the specified cache through the EasyCachingEvict feature including the IsAll property, and I don't want to fixed writing the CacheKeyPrefix.

```C#
[EasyCachingAble(CacheKeyPrefix = "MyPrefixKey", Expiration = 7200)]
IEnumerable<MyClass> GetSomething(MyParam param);
```
Like this:

```C#
[EasyCachingAble(Expiration = 7200)]
IEnumerable<MyClass> GetSomething(MyParam param);
````

```C#
public class MyParam: ICachable
{
    public int Year { get; set; }

    public string UserId { get; set; }

    public string CacheKey => $"{Year}";

    public string CacheKeyPrefix => $"MyPrefixKey_{UserId}";
}
````

Suppose I have the following cache:
```
MyPrefixKey_User01:2019
MyPrefixKey_User01:2020
MyPrefixKey_User01:2021
MyPrefixKey_User02:2020
MyPrefixKey_User02:2021
```

When my parameters are as follows:
```C#
// param: User=User01
[EasyCachingEvict(IsAll = true)]
void Delete(MyParam param);
````

I can delete all caches with a CachePrefix of "MyPrefixKey_User01" without having to manually call CacheProvider.RemoveByPrefix ("MyPrefixKey_User01") to delete.

**Comment by catcherwong** [comment]
@visten  Thanks for your interest in this project.

EasyCaching doesn't support this feature now. Maybe you can send a PR to done this feature.

**Comment by visten** [comment]
Ok., I will do it.
