### ISSUE TITLE
Question: Does EasyCaching Execute the factory method only once?

### ISSUE THREAD

**Issue by ckarcz** [dotnetcore/EasyCaching#190]
Similar to LazyCache:
https://github.com/alastairtree/LazyCache

Does EasyCaching prevent two concurrent callers executing the factory delegate at the same time?

LazyCache improves this situation by using what they call/created a simple type ```AsyncLazy<T>``` (using ```Lazy<T>``` and ```Task```). This prevents multiple concurrent callers both executing the delegate and causing a heavy process/calculation from being executed **multiple times**. The factory delegate that created the value to cache will be only called once.

If this is not currently a feature, I think adding it would be great.

Thanks,
Chris

**Comment by catcherwong** [comment]
@ckarcz  Thanks for your interest in this project.

> Does EasyCaching prevent two concurrent callers executing the factory delegate at the same time?

I am not sure that if you want to ask `Get/GetAsync(with data retriever)` this API can prevent concurrent callers executing or not? 

If the answer is yes, EasyCaching support this feature.
