### ISSUE TITLE
Understanding cachePrefix

### ISSUE THREAD

**Issue by ameckl** [dotnetcore/EasyCaching#192]
## Description

Hello!

I'm trying to integrate EasyCache into my project and I'm having trouble understanding how AspectCore annotations work.

### Steps to Reproduce

Consider the following code

### Related code
```
interface IUserService {

  [EasyCachingAble(CacheKeyPrefix = "UserById")]
  User GetUserById(string id);

  [EasyCacheEvict?]
  User UpdateUser(User userWithModifications);
}
```
I've seen in the code, that the actual cache key is generated by taking the method name and all parameters of the method. I find this method hard to use since in my example I'm unable to evict the cache for a specific user. 

Would it be possible to have more control on the cache key, and also maybe use parameters of the method to build a dynamic key?

Something like this
```
interface IUserService {

  [EasyCachingAble(CacheKeyPrefix = "UserById:{id}")]
  User GetUserById(string id);

  [EasyCacheEvict(CacheKeyPrefix = "UserById:{userWithModifications.Id}"]
  User UpdateUser(User userWithModifications);
}
```
So whenever the `UpdateUser` method is called the cache with the specific key (having the user's id inside the key) is evicted.

> I know that there are solutions to achieve dynamic cache key, but not when using AspectCore annotations

## Specifications

- Provider    : InMemory (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : Windows 10

**Comment by catcherwong** [comment]
@ameckl Thanks for your interest in this project.

> I've seen in the code, that the actual cache key is generated by taking the method name and all parameters of the method. I find this method hard to use since in my example I'm unable to evict the cache for a specific user.

When specify the `CacheKeyPrefix` , the generated cache key will not contain method name here. #141  explains this one.

> Would it be possible to have more control on the cache key, and also maybe use parameters of the method to build a dynamic key?

Of course, dynamic key seems a good idea here. 

Maybe you can send a PR to done this feature as well.
