### ISSUE TITLE
StringSet方法不支持redis命令SETNX

### ISSUE THREAD

**Issue by Jeacaler** [dotnetcore/EasyCaching#194]
## Description

Redis实现，不支持redis命令SETNX

### Steps to Reproduce

1. 
2. 

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Provider    : InMemory (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : CentOS 7.2

**Comment by catcherwong** [comment]
@Jeacaler  Thanks for your interest in this project.

v0.8.6 support this feature now.

`when` parameter support `nx`, `xx` and ``.

```cs
var res = await _provider.StringSetAsync(
                cacheKey: cacheKey,
                cacheValue: cacheValue,
                expiration: null,
                when: "nx");
```
