### ISSUE TITLE
EasyCaching.Interceptor.Castle 服务注册问题

### ISSUE THREAD

**Issue by lixiong123** [dotnetcore/EasyCaching#196]
/// <summary>
        /// Configures the castle interceptor.
        /// </summary>
        /// <param name="builder">Container Builder.</param>
        /// <param name="isCalling">Is Calling Assembly or Executing Assembly.</param>
        public static void ConfigureCastleInterceptor(this ContainerBuilder builder, bool isCalling = true)
        {                          
            var assembly = isCalling ? Assembly.GetCallingAssembly() : Assembly.GetExecutingAssembly();

            builder.RegisterType<EasyCachingInterceptor>();

            builder.RegisterAssemblyTypes(assembly)
                .Where(t => !t.IsAbstract && t.GetInterfaces().SelectMany(x => x.GetMethods()).Any(
                    y => y.CustomAttributes.Any(data =>
                                    typeof(EasyCachingInterceptorAttribute).GetTypeInfo().IsAssignableFrom(data.AttributeType)
                                )))
                .AsImplementedInterfaces()
                .InstancePerLifetimeScope()
                .EnableInterfaceInterceptors()
                .InterceptedBy(typeof(EasyCachingInterceptor));            
        }

这个方法里面：
 var assembly = isCalling ? Assembly.GetCallingAssembly() : Assembly.GetExecutingAssembly();

对于当前程序集Service注册有效。但是对于别的程序集项目注入的Servcie服务貌似不生效。

简单说明问题：

源代码：samples/EasyCaching.Demo.Interceptors /IAspectCoreService 这个接口在当前程序集下。而我把这个接口放到别的程序集下/项目下  注入不生效，无法注册。

麻烦，看一下，是不是我用的方法不对。谢谢了

**Comment by catcherwong** [comment]
@lixiong123  Thanks for your interest in this project.

There is a bug here! I will use the following code to replace it!

```cs
builder.RegisterType<EasyCachingInterceptor>();
```

I feel so sorry for this bug!

**Comment by catcherwong** [comment]
@lixiong123  v0.8.6.1 fixed this bug, please have a try.
