### ISSUE TITLE
How to use WithRedisBus? any sample?

### ISSUE THREAD

**Issue by ajdwfnhaps** [dotnetcore/EasyCaching#197]
## Description

如何发布自定义消息内容？

![image](https://user-images.githubusercontent.com/11205717/76841887-5e8cc400-6874-11ea-9591-92a1c19461a5.png)
EasyCachingMessage 只有这三个属性吗？
能否提供类似以下的属性，用来发布或订阅我们自定议的消息内容呢？
```
public T Data {get;sest;}
```

### Related code

![image](https://user-images.githubusercontent.com/11205717/76841346-9c3d1d00-6873-11ea-8e73-6771292d4d5f.png)

## Specifications

- Provider    : Redis(version 0.8.6)
- Interceptor : no use
- Serializer  : MessagePack
- System      : Win7

**Comment by catcherwong** [comment]
@ajdwfnhaps Thanks for your interest in this project.

I am so sorry to tell you that the bus of EasyCaching is not a common solution, it was wrote for EasyCaching only!
