### ISSUE TITLE
Async support for GetCount/BaseGetCount

### ISSUE THREAD

**Issue by mjebrahimi** [dotnetcore/EasyCaching#198]
Is it possible to add async support for GetCount/BaseGetCount?
Currently, async method for [BaseGetCount](https://github.com/dotnetcore/EasyCaching/blob/6e47794ca78ad602e087dd27c9ccf1433e8da891/src/EasyCaching.Core/EasyCachingAbstractProvider.cs#L40) and [GetCount](https://github.com/dotnetcore/EasyCaching/blob/6e47794ca78ad602e087dd27c9ccf1433e8da891/src/EasyCaching.Core/EasyCachingAbstractProvider.cs#L397) dose not exists.

**Comment by catcherwong** [comment]
@mjebrahimi  Thanks for your interest in this project.

Yes, we will add it ASAP 😄

**Comment by mjebrahimi** [comment]
I can make it for you.
Are you interested in PR? 😉

**Comment by catcherwong** [comment]
Of course, PR welcome!!!

**Comment by catcherwong** [comment]
v0.8.7 support this feature.
