### ISSUE TITLE
Suggestion : Implementation of EasyCaching for MS.Caching InMemory and IDistributedCache abstractions

### ISSUE THREAD

**Issue by mjebrahimi** [dotnetcore/EasyCaching#203]
Hi @catcherwong 

What do you think about an Implementation of EasyCaching for MS.Caching IMemoryCache and IDistributedCache abstractions?

This way, those who use these abstractions can take advantage of good EasyCaching capabilities such as different providers and different serializers without changing their project codes.

**Comment by mjebrahimi** [comment]
And many other libraries that use IMemoryCache and IDistributedCache abstraction can integrate with this great library.

**Comment by mjebrahimi** [comment]
I checked out this repo but :
[https://github.com/yrinleung/EasyCaching.Extensions](https://github.com/yrinleung/EasyCaching.Extensions#5-microsoftextensionscachingdistributedidistributedcache%E4%BD%BF%E7%94%A8easycaching%E5%AE%9E%E7%8E%B0)

- It has no implementation for IMemoryCache
- Its base code is not good enough as [MS impmenetation](https://github.com/dotnet/extensions/blob/master/src/Caching/StackExchangeRedis/src/RedisCache.cs)
- And it's maintainers seem not to be active (its [package](https://www.nuget.org/packages/YrinLeung.Microsoft.Extensions.Caching.EasyCaching/) still uses the old version of EasyCaching 0.5.4.1 and MS.Ext.Caching.Abstraction 2.2.0)

I think it's better to create and maintain a project for this under the EasyCaching subset.

**Comment by catcherwong** [comment]
This is a good idea!! 😄  

I will consider this one.
