### ISSUE TITLE
aspectcore 升级后容器IServiceContainer 改成了IServiceContext

### ISSUE THREAD

**Issue by yangjie955330** [dotnetcore/EasyCaching#206]
aspectcore 升级后容器IServiceContainer 改成了IServiceContext

ConfigureAspectCoreInterceptor这个扩展方法现在没法用了。还望大佬升级哈

**Comment by catcherwong** [comment]
@yangjie955330  Thanks for your interest in this project.

I will take a look ASAP.

**Comment by catcherwong** [comment]
V0.8.7 of EasyCaching using AspectCore.Core V2.0.0, and not use `IServiceContainer` here.

Take a look on the sample 

https://github.com/dotnetcore/EasyCaching/blob/48dbc893e8931cc5b5d76d8025e06e794937bfde/sample/EasyCaching.Demo.Interceptors/Program.cs#L16-L26

https://github.com/dotnetcore/EasyCaching/blob/48dbc893e8931cc5b5d76d8025e06e794937bfde/sample/EasyCaching.Demo.Interceptors/Startup.cs#L44-L45

Do you meet some problems when using the interceptor?

**Comment by catcherwong** [comment]
No Response , Closed!

If you also have question for this problem, reopen it or open a new one.
