### ISSUE TITLE
请问为啥没实现RedisProvider里的LpushAsync方法？

### ISSUE THREAD

**Issue by xiongdashan** [dotnetcore/EasyCaching#209]
https://github.com/dotnetcore/EasyCaching/blob/6256fa97291219e1d41591aa97f634ad216c38b6/src/EasyCaching.Redis/DefaultRedisCachingProvider.List.cs#L233

**Comment by catcherwong** [comment]
@xiongdashan Thanks for your interest in this project.

RedisProviders only include some features of Redis due to time reason.

If you need this one, you can send a PR for it. 😄

**Comment by xiongdashan** [comment]
Thanks, replaced ``LPushX``
