### ISSUE TITLE
fix bugs for Expiration in DefaultCSRedisCachingProvider

### ISSUE THREAD

**Issue by huoshan12345** [dotnetcore/EasyCaching#211]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1.  Use DefaultCSRedisCachingProvider
2.  call HMSet(string, Dictionary<string, string>, TimeSpan? expiration) with non-null expiration

### Related code

```
// in DefaultCSRedisCachingProvider.Async.cs: 
_cache.Expire(cacheKey, expiration.Value.Seconds);
// TimeSpan.TotalSeconds should be used insead of TimeSpan.Seconds
```
There are four related bugs about Expiration.
I created a PR to fix that. https://github.com/dotnetcore/EasyCaching/pull/210

**Comment by huoshan12345** [comment]
https://github.com/dotnetcore/EasyCaching/pull/210

**Comment by catcherwong** [comment]
@huoshan12345 Thanks for your interest in this project.

Thanks for your help!

**Comment by huoshan12345** [comment]
@catcherwong my pleasure 😊

**Comment by catcherwong** [comment]
release v0.8.8 for this issue. 😄
