### ISSUE TITLE
Unable to use appsettings.json

### ISSUE THREAD

**Issue by QPRocky** [dotnetcore/EasyCaching#212]
Hi, 

this is not really an issue, but I'm trying to load settings from appsettings.json as mentioned in [https://easycaching.readthedocs.io/en/latest/Redis/](https://easycaching.readthedocs.io/en/latest/Redis/)

But I'm getting error when trying to set key:
`{"No connection is active/available to service this operation: SETEX TestKey123; UnableToConnect on localhost:6739/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 2s ago, v: 2.1.28.64774, mc: 1/1/0, mgr: 10 of 10 available, clientName: DESKTOP-0QN6K7H, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=1,Free=32766,Min=12,Max=32767), v: 2.1.28.64774"}`

Most likely issue is "myredisname" as I can't figure out, what it should be

`        services.AddEasyCaching(option =>
        {
            option.UseRedis(Configuration, "myredisname");
        });`

Appsettings is similar than in that redis document (link above)

With this code, its working thou:
`            services.AddEasyCaching(options =>
            {
                options.UseRedis(redisConfig =>
                {
                    redisConfig.DBConfig.Endpoints.Add(new ServerEndPoint("localhost", 6379));
                    redisConfig.DBConfig.AllowAdmin = true;
                }, "redis1");
            });`

Btw, what are differences between EasyCaching.Redis and EasyCaching.CSRedis?

**Comment by catcherwong** [comment]
@QPRocky  Thanks for your interest in this project.

>But I'm getting error when trying to set key:
{"No connection is active/available to service this operation: SETEX TestKey123; UnableToConnect on localhost:6739/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 2s ago, v: 2.1.28.64774, mc: 1/1/0, mgr: 10 of 10 available, clientName: DESKTOP-0QN6K7H, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=1,Free=32766,Min=12,Max=32767), v: 2.1.28.64774"}

I will take a look on this error ASAP.

> Btw, what are differences between EasyCaching.Redis and EasyCaching.CSRedis?

EasyCaching.Redis is based on [StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis), and EasyCaching.CSRedis is based on [csredis](https://github.com/2881099/csredis)

**Comment by catcherwong** [comment]
It seems that there is a bug here.

Reproduced this issue.

![error](https://user-images.githubusercontent.com/8394988/79812852-a2f80c00-83ac-11ea-83ad-8e20483c0bb7.png)

![code](https://user-images.githubusercontent.com/8394988/79812816-8cea4b80-83ac-11ea-8adb-b918eb64d761.png)

If you want to use `appsetting.json`,  please replace **dbconfig** with only `Configuration` section at this time, here is a sample.

```JSON
 "easycaching": {
    "redis1": {
       "MaxRdSecond": 120,
       "EnableLogging": false,
       "LockMs": 5000,
       "SleepMs": 300,
       "dbconfig": {
        "Configuration": "127.0.0.1:6379,allowAdmin=False,connectTimeout=5000,ssl=False,abortConnect=False,defaultDatabase=1"
      }
    }   
 }
```
And configure in Startup

```cs
services.AddEasyCaching(option =>
{
    option.UseRedis(configuration: Configuration, name: "myredisname1", sectionName: "easycaching:redis1");
});
```

I will try to fix this bug ASAP when I have time later. If you can solve this bug, PR welcome! 😄

**Comment by catcherwong** [comment]
@QPRocky I fell so sorry for this mistake!

>But I'm getting error when trying to set key:
`{"No connection is active/available to service this operation: SETEX TestKey123; UnableToConnect on localhost:6739/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 2s ago, v: 2.1.28.64774, mc: 1/1/0, mgr: 10 of 10 available, clientName: DESKTOP-0QN6K7H, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=1,Free=32766,Min=12,Max=32767), v: 2.1.28.64774"}`

This connection is `localhost:6739` not `localhost:6379`, maybe you can try to modify the endpoint and test it one more time.

And I will modify the document ASAP to avoid this port problem.

**Comment by QPRocky** [comment]
Ah, right. :) Thanks for checking it out.

**Comment by catcherwong** [comment]
Closed!

If you also have question for this problem, reopen it or open a new one.
