### ISSUE TITLE
asp.net core3.1使用aspectcore2.1,EasyCachingAble的问题

### ISSUE THREAD

**Issue by yangjie955330** [dotnetcore/EasyCaching#214]
配置了
services.AddEasyCaching(option =>
            {
                //option.UseRedis(Configuration, "redis1");
                option.UseInMemory("m1");
            });
和
services.ConfigureAspectCoreInterceptor(options =>
            {
                options.CacheProviderName = "m1";
            });

但使用EasyCachingAble未生效

**Comment by yangjie955330** [comment]
update

**Comment by catcherwong** [comment]
@yangjie955330 Thanks for your interest in this project.

Could you please provide more information for this issue?

**Comment by yangjie955330** [comment]
https://gitee.com/yangjie955330/PrivilegeManagement 这里有代码

**Comment by catcherwong** [comment]
OK, I will take a look ASAP.

**Comment by catcherwong** [comment]
Combine Autofac with AspectCore, you can following https://github.com/yrinleung/EasyCaching.Extensions
