### ISSUE TITLE
RabbitMQ dependency upgrade to 6.0.0

### ISSUE THREAD

**Issue by dthanasopoulos** [dotnetcore/EasyCaching#216]
Hi 
I love the project and find it very useful. One Minor request : 
Can you upgrade the nuget dependency in EasyCaching.Bus.RabbitMQ  for RabbitMQ to the latest version? 

Many thanks

**Comment by catcherwong** [comment]
@dthanasopoulos  Thanks for your interest in this project.

Sure, I will upgrade the nuget dependency ASAP.

**Comment by catcherwong** [comment]
release 0.8.9.1 for this issue. 😄

**Comment by dthanasopoulos** [comment]
Ty for the ultra fast turnaround
