### ISSUE TITLE
error on EasyCachingProvider.GetByPrefix<string>(prefixKey)

### ISSUE THREAD

**Issue by Calx-Takeno** [dotnetcore/EasyCaching#218]
EasyCaching.CSRedis 0.6.1
Newtonsoft.Json 12.0.3

EasyCachingProvider.GetByPrefix<string>(prefixKey) get an error

prefixKey="useragent:unknown"

some example value:
Mozilla/5.0 (iPhone; CPU iPhone OS 13_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/7.0.12(0x17000c2f) NetType/WIFI Language/en

exception message:
The input stream is not a valid binary format. The starting contents (in bytes) are: 50-6F-73-74-6D-61-6E-52-75-6E-74-69-6D-65-2F-37-2E ...

exception trace:
at System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.Read(BinaryParser input)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadSerializationHeaderRecord()
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at EasyCaching.Core.Serialization.DefaultBinaryFormatterSerializer.Deserialize[T](Byte[] bytes)
   at EasyCaching.CSRedis.DefaultCSRedisCachingProvider.BaseGetByPrefix[T](String prefix)
   at EasyCaching.Core.EasyCachingAbstractProvider.GetByPrefix[T](String prefix)

**Comment by catcherwong** [comment]
@Calx-Takeno Thanks for your interest in this project.

The value in Redis is a raw string? It can not be deserialized by **BinaryFormatter**.

Which serializer do you use?  Could you please show the configuration of EasyCaching?

**Comment by Calx-Takeno** [comment]
Yes，I use IRedisCachingProvider.StringSet(string cacheKey, string cacheValue, TimeSpan? expiration = null) to store values.

And I try IEasyCachingProvider.GetByPrefix<T>(string prefix) to get values of prefix key. 

The value of Redis is 
'Mozilla/5.0 (iPhone; CPU iPhone OS 13_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/7.0.12(0x17000c2f) NetType/WIFI Language/en'

I use the default serializer of .NET CORE 2.2
EasyCaching.CSRedis 0.6.1

System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize

I think it depends on EasyCaching.Core.Serialization.DefaultBinaryFormatterSerializer by error logs.
I haven't add any serializer library in my project
Could I chang this to another serializer? 

My configuration of EasyCaching is
# code
services.AddEasyCaching(option =>
            {
                option.UseCSRedis(config =>
                {
                    config.DBConfig = new CSRedisDBOptions() { ConnectionStrings = new List<string>() { LaunchSetting.RedisSetting.DefaultInstance } };
                });
            });
# endcode

LaunchSetting.RedisSetting.DefaultInstance is string value.
127.0.0.1:6379,password=xxxx,poolsize=20,connectTimeout=3600,tryit=1,defaultDatabase=0,preheat=5;autoDispose=true

**Comment by Calx-Takeno** [comment]
Update:
I change IRedisCachingProvider.StringSet to IEasyCachingProvider.Set<string>

Then IEasyCachingProvider.GetByPrefix works.

 IRedisCachingProvider.StringSet is plain text.

 IEasyCachingProvider.Set<string> is CacheValue<T> object.

How to get values of prefix key by  IRedisCachingProvider?

**Comment by catcherwong** [comment]
**IRedisCachingProvider** and **IEasyCachingProvider** are different things, they should not be mixed.

**IRedisCachingProvider** is designed for Redis only, it contains of some basic commands. If you want to get values of prefix key, it do not support at this time.  Adding `scan` or `keys` command can help you out.
