### ISSUE TITLE
Base interface for IHybridCachingProvider and IEasyCachingProvider

### ISSUE THREAD

**Issue by Youkai-no-nii-chan** [dotnetcore/EasyCaching#219]
## Description

I am making some wrappers and helpers for CachingProvider in my project and would like to reuse them for InMemory and HybridCache. But `IEasyCachingProvider` and `IHybridCachingProvider` have no common ansector and any code written for `IEasyCachingProvider` cannot be reused with `IHybridCachingProvider` without additional wrapping.
IEasyCachingProvider have same methods and properties as IHybridCachingProvider plus some additional. So it is easy to make base interface for both of them.

### Related code

Wrapper example (simplified)
```
	public class StaticCache<TItem> where TItem : class
	{
		private readonly IEasyCachingProviderBase provider;
		private readonly TimeSpan expirationPeriod;

		public StaticCache(IEasyCachingProviderBase provider, TimeSpan expirationPeriod)
		{
			this.provider = provider;
			this.expirationPeriod = expirationPeriod;
		}

		public void AddOrUpdate(string key, TItem item) => provider.Set(key, item, expirationPeriod);
	}
```

**Expected behavior:** HybridCache can be easily replaced with other caches without rewriting all usages.

**Actual behavior:** HybridCache and other caches have no common interface and can't be easily replaced.

**Comment by catcherwong** [comment]
@Youkai-no-nii-chan   Thanks for your interest in this project.

`IEasyCachingProvider` and `IHybridCachingProvider` really have some common methods and properties.

Here are the reasons why I make them separation.

1. At the beginning of EasyCaching, it only contains `IEasyCachingProvider` which is the core of this project.
2. `IHybridCachingProvider` should use two or more `IEasyCachingProvider`  to complete hybird caching or muilt-level caching.
3. The methods of `IHybridCachingProvider` do not need to the same as `IEasyCachingProvider`, just contains some useful methods.

**Comment by Youkai-no-nii-chan** [comment]
I understand why they are different interfaces. But do extracting base interface for them has any downsides?
The only problem I could think of - if in future some common parts of IHybridCachingProvider and IEasyCachingProvider will change only in one of them. But it seems unlikely.

**Comment by catcherwong** [comment]
> But do extracting base interface for them has any downsides?

No.

> if in future some common parts of IHybridCachingProvider and IEasyCachingProvider will change only in one of them

Most of time, it will be unlikely!

And I will take a look on how to merge those two interfaces. If you already have some ideas, PR welcome 😄

**Comment by Youkai-no-nii-chan** [comment]
@catcherwong I already have it locally. Could you give me permissions to make pull requests?

**Comment by Youkai-no-nii-chan** [comment]
I have 403 error, when I try to push new branch to this repository.
![image](https://user-images.githubusercontent.com/8893554/85000241-ccd67080-b15a-11ea-989c-481357f29efd.png)

I think I should be [invited as collaborator](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository) to be able to push branches here.
Is there another way to create pull requests? I haven't worked with open source repositories yet and not sure.

**Comment by Youkai-no-nii-chan** [comment]
Made it.
For my use case it is enough to extract base interface without any additional refactoring.
