### ISSUE TITLE
connect to aws redis server with Encryption in-transit, using TLS

### ISSUE THREAD

**Issue by Jaafar-abusair** [dotnetcore/EasyCaching#220]
It's not a bug, I'm just asking how to connect to aws redis server with Encryption in-transit, using TLS

I'm using options.UseRedis without Encryption in-transit enabled at aws server, but i want to change the server to enable Encryption in-transit

**Comment by catcherwong** [comment]
@Jaafar-abusair  Thanks for your interest in this project.

I feel so sorry that I don't have experience about AWS Redis.

But if you are using `UseRedis`, the provider is based on [StackExchange/StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis). You can take a look on its' issues or documents about the feature.

**Comment by catcherwong** [comment]
Maybe this one can help you out.

https://stackoverflow.com/questions/58846169/how-can-i-disable-certificate-validation-with-stackexchange-redis
