### ISSUE TITLE
Allow to cache nulls

### ISSUE THREAD

**Issue by Youkai-no-nii-chan** [dotnetcore/EasyCaching#222]
## Problem description
I saw comment about nulls caching https://github.com/dotnetcore/EasyCaching/issues/43#issuecomment-397132874, but we have important case when it is necessary.

We develop a low code platform, where our clients can set up some handlers for processing some requests from there websites. 
1. Each handler is entity in database, that is cached in memory. 
2. Some handlers could process up to 100 messages per second. 
3. If handler is deleted by client, all requests with that handler are discarded at the begining of processing.
4. In many cases clients could send request for handler for some time after it was deleted. And we want to discard them with least possible impact on system performance.

If we will try to get handler from databse 100 times per second for a long time, it will lead to some performace degradation. So we need to cache infromation, that there is no such handler. Implemeting NullHandler is inconvenient for several reasons:
1. There is some infrastructure code between getting handler and calling it. So we would need to check if handler is null explicitly.
2. Handler is database entity and to make NullHandler we should extract interface.
3. We have several microservices that implements such pattern, so we would need to implement NullValue pattern several times.

So it would be most convenient for us to cache null values.

## Proposition
Because caching nulls may be undesirable in some cases, I would like to add settings that allows nulls caching to CachingProvider.
I've already made some draft (see pull request bellow).

What do you think about it?

**Comment by catcherwong** [comment]
@Youkai-no-nii-chan  Thanks for your interest in this project.

It sounds great! 

There are some scenarios really need NULL value. If adding a setting to do this one, it may help some of us to handle some problems.

**Comment by Youkai-no-nii-chan** [comment]
PR is ready https://github.com/dotnetcore/EasyCaching/pull/223
