### ISSUE TITLE
在.net core 3.1中用什么替换AspectCoreServiceProviderFactory

### ISSUE THREAD

**Issue by totoo1024** [dotnetcore/EasyCaching#232]
`public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder `=>`
            {
                webBuilder.UseStartup<Startup>();
            })
            // for aspcectcore
            .UseServiceProviderFactory(new AspectCoreServiceProviderFactory())
        ;`
在.net core 3.1中无法使用UseServiceProviderFactory(new AspectCoreServiceProviderFactory())

**Comment by catcherwong** [comment]
@totoo1024  Thanks for your interest in this project.

Take a look on the sample.

https://github.com/dotnetcore/EasyCaching/blob/ec25dea9eddeb8d4d1b04289b2287517fe8efdc0/sample/EasyCaching.Demo.Interceptors/Program.cs#L16-L25
