### ISSUE TITLE
请问在.net core 3.1中怎么使用Caching Intercept

### ISSUE THREAD

**Issue by totoo1024** [dotnetcore/EasyCaching#235]
## 请问在.net core 3.1中怎么使用Caching Intercept
在3.1中Caching Intercept是否和3.0的用法一致，我按3.0的文档使用Caching Intercept并没有效果
能否提供3.1的Caching Intercept的用法或示例，谢谢

**Comment by catcherwong** [comment]
@totoo1024  Thanks for your interest in this project.

Take a look on [EasyCaching.Demo.Interceptors](https://github.com/dotnetcore/EasyCaching/tree/master/sample/EasyCaching.Demo.Interceptors).

Modify targetframework from `netcoreapp3.0` to `netcoreapp3.1` can also run well.

**Comment by totoo1024** [comment]
如果使用Autofac应该怎么接入Caching Intercept？

**Comment by catcherwong** [comment]
Take a look on this repo.

https://github.com/yrinleung/EasyCaching.Extensions

**Comment by totoo1024** [comment]
非常你的耐心指导
