### ISSUE TITLE
expiration not work?

### ISSUE THREAD

**Issue by broad-m** [dotnetcore/EasyCaching#239]
## Description
I used redis server downloaded from :
https://github.com/microsoftarchive/redis/releases
Redis-x64-3.2.100.zip
![image](https://user-images.githubusercontent.com/15180367/91658449-c0777800-eafa-11ea-924a-f1a364fb5ce3.png)

in my test code, Actual expiration is longer 

### Steps to Reproduce

insert short code snippets here
![image](https://user-images.githubusercontent.com/15180367/91658348-0f70dd80-eafa-11ea-8bb7-5dcc865f24c3.png)

**Actual behavior:** [What actually happened]
![image](https://user-images.githubusercontent.com/15180367/91658360-29122500-eafa-11ea-9956-29d7e462dbfe.png)

## Specifications
- Provider    : EasyCaching.Redis (version 0.8.10)
- Interceptor : AspectCore Console APP (version 3.1)
- System      : windows 10

**Comment by catcherwong** [comment]
@broad-m  Thanks for your interest in this project.

Have you modify the `MaxRdSecond`? 

https://github.com/dotnetcore/EasyCaching/blob/19354812a4288d17e65e084f335996b36f356120/src/EasyCaching.Core/Configurations/BaseProviderOptions.cs#L8-L16

**Comment by broad-m** [comment]
Thank you for your answer,this is really the problem

**Comment by broad-m** [comment]
I copied it from the document,  lol
![image](https://user-images.githubusercontent.com/15180367/91661934-b319b800-eb11-11ea-8f4c-18f650305904.png)

**Comment by catcherwong** [comment]
If you do need this feature, you can set a value less or equal than 0, it will be disabled.
