### ISSUE TITLE
Subscriber is not receiving the message - Redis.Bus / HybridProvider

### ISSUE THREAD

**Issue by natrajsr** [dotnetcore/EasyCaching#241]
## Description

I have two applications acting as 2 redis clients. **Client 1** is resopnsible for evicting the cache for set of keys, **Client 2** is supposed to receive the message and clear the local cache for the ser of keys.

Unfortunately, Client 2 is still continue to serve the data from local cache. I am unable to synchronize the local caches across apps.

### Steps to Reproduce

1. Evict the cache for set of keys from - Application 1 - Client 1
2. Access the same data from API -  Client 2
3. API still returns the stale data

### Related code

My startup code looks like this

```
            services.AddEasyCaching(options =>
            {
                options.UseInMemory("nsCacheMem");
                options.UseRedis(options =>
                {
                    options.DBConfig.Endpoints.Add(
                        new ServerEndPoint("{AzureRedisHostName}", 6380));
                    options.DBConfig.IsSsl = true;
                    options.DBConfig.Password = "{Password}";
                }, "nsCacheRedis");

                options.UseHybrid(options =>
                {
                    options.TopicName = "nsAPI";
                    options.EnableLogging = true;

                    options.LocalCacheProviderName = "nsCacheMem";
                    options.DistributedCacheProviderName = "nsCacheRedis";
                }, "hybridProvider")
                .WithRedisBus(busConf =>
                {
                    busConf.Endpoints.Add(new ServerEndPoint("{AzureRedisHostName}", 6380));
                    busConf.IsSsl = true;
                    busConf.Password = "{Password}";
                });

                // with a default name [proto]
                options.WithProtobuf();
            });
```

**Expected behavior:** [What you expected to happen]

API should be fetchig the data from redis cache / load from the database

**Actual behavior:** [What actually happened]

API fetches the data from local cache

## Specifications

- Provider    : EasyCaching.HybridCache (version 0.8.11)
- Provider    : EasyCaching.Redis (version 0.8.11)
- Provider    : EasyCaching.Bus.Redis (version 0.8.11)
- Provider    : EasyCaching.InMemory (version 0.8.11)
- Provider    : EasyCaching.Core (version 0.8.11)
- Serializer  : not use
- System      : Windows 10 Pro

**Comment by catcherwong** [comment]
@natrajsr  Thanks for your interest in this project.

We will take a look ASAP.

**Comment by catcherwong** [comment]
@natrajsr  I tested it with version 0.8.11, but it runs well.   Here is the sample repo 

https://github.com/catcherwong-archive/EasyCachingHybridDemo

Could you please take a look on the above sample or provide more information for your issue?

**Comment by natrajsr** [comment]
@catcherwong Thanks for looking into this.

Unfortunately, I couldn't find the issue yet. 

As I mentioned, 

- App 1 loads the data into cache using Hybrid provider
- App 2 removes the data from Hybrid provider

I am getting only the following logs

**App1 Logs**
dbug: EasyCaching.HybridCache.HybridCachingProvider[0]
      local cache can not get the value of 12a4024d-1fcd-4559-81c9-c46a89fcde88
dbug: EasyCaching.HybridCache.HybridCachingProvider[0]
      distributed cache can not get the value of 12a4024d-1fcd-4559-81c9-c46a89fcde88

**App2 Logs**
dbug: EasyCaching.HybridCache.HybridCachingProvider[0]
      local cache can not get the value of 12a4024d-1fcd-4559-81c9-c46a89fcde88


**Remove Cache Code**
`public static async Task EvictCacheValueAsync(this IHybridCachingProvider cache, string key, ILoggerFactory loggerFactory)
    {
        ILogger<IHybridCachingProvider> logger = loggerFactory.CreateLogger<IHybridCachingProvider>();
        if (string.IsNullOrEmpty(key))
        {                
            throw new ArgumentNullException(nameof(key));
        }

        var cachedValue = await cache.GetCacheValueAsync<dynamic>(key, logger);
        if (cachedValue != null)
        {
            try
            {
                await cache.RemoveAsync(key).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Redis Exception - EvictCacheValueAsync - key- {@key}", key);
            }
        }
    }`

App1 is not getting any message post removal of cache, I can confirm that entry is removed from redis cache.

Am I missing anything?

Thanks.

**Comment by natrajsr** [comment]
I figured out the issue.

It is the following configuration which was causing the trouble. After commenting out the protobuf serialization, it started working. 

```
  // with a default name [proto]
  // options.WithProtobuf();
```

When it was not working, i tried to find out whether there are any subscribers on the topic with the following command
`PUBSUB numsub <topic-name>`

The result was zero which means either there is something missing in my configuration along with protobuf, or there could be an unknown issue when they are used in combination.

If possible, will spend sometime into the EasyCaching code and contribute towards it
