### ISSUE TITLE
Adding "EasyCaching.Extensions.EasyCompressor"

### ISSUE THREAD

**Issue by mjebrahimi** [dotnetcore/EasyCaching#243]
This [EasyCaching.Extensions.EasyCompressor](https://github.com/mjebrahimi/EasyCompressor/blob/master/src/EasyCaching.Extensions.EasyCompressor/README.md) might be worth a mention under the extensions section fo its README.

**Comment by catcherwong** [comment]
@mjebrahimi  Thanks for your interest in this project.

Awesome project!!  

I will add it to README or you can submit a PR by yourself.

**Comment by mjebrahimi** [comment]
Thanks, PR #244 submitted.

**Comment by catcherwong** [comment]
Merged!
