### ISSUE TITLE
请问哨兵模式的ip是什么？

### ISSUE THREAD

**Issue by mswinner** [dotnetcore/EasyCaching#247]
ConnectionStrings = new System.Collections.Generic.List<string>
                    {
                        "127.0.0.1:6388,defaultDatabase=13,poolsize=10"
                    },
                    // the sentinels settings
                    Sentinels = new System.Collections.Generic.List<string>
                    {
                        "192.169.1.10:26379", "192.169.1.11:26379", "192.169.1.12:26379"
                    },
                    // the read write setting for sentinel mode
                    ReadOnly = false

你好，我是在k8s 用helm部署的redis-ha  1主2从3哨兵，   你们这127.0.0.1:6388  我配置master的ip？ 对吗？

**Comment by catcherwong** [comment]
@mswinner  Thanks for your interest in this project.

Sorry for slow to response.  You can take a look on the following URL to find more information.

https://github.com/2881099/csredis#redis-sentinel

**Comment by mswinner** [comment]
"127.0.0.1:6388,defaultDatabase=13,poolsize=10"
你就不能直接告诉我 这个ip 该配置什么吗？

我配置masterip  还是提示easycaching Redis Sentinel Master is switching：Connection was not opened
