### ISSUE TITLE
LiteDB调用Get获取缓存缺少超时控制

### ISSUE THREAD

**Issue by lable** [dotnetcore/EasyCaching#248]
LiteDB调用Get获取缓存缺少超时控制

**Comment by catcherwong** [comment]
@lable  Thanks for your interest in this project.

We will take a look ASAP.

**Comment by maikebing** [comment]
I've fixed the problem and passed the unit test!

**Comment by catcherwong** [comment]
@lable please have a try with version 1.1.0-alpha20201010130916.

**Comment by lable** [comment]
谢谢！
