### ISSUE TITLE
EasyCatching not working with redis 3.0 greater

### ISSUE THREAD

**Issue by lamthanhphat98** [dotnetcore/EasyCaching#250]
I just tested asp.net core 3.1 with redis 2.4.5 it worked perfectly but when I changed to redis 3.2.100 , my server cannot connect to redis like same way connect to 2.4.5.

**Comment by catcherwong** [comment]
@lamthanhphat98 Thanks for your interest in this project.

Could you please let us know more details about this problem? such as the error message and the StackTrace.

**Comment by lamthanhphat98** [comment]
Oh I am sorry for forgetting my issue. I will be back for more infor on Monday because now I am off. Sorry about that

**Comment by catcherwong** [comment]
Any feedback for this issue?

**Comment by lamthanhphat98** [comment]
it worked perfectly now, Thanks you ^^.

**Comment by lamthanhphat98** [comment]
I don't know why but after restarting laptop it works.
