### ISSUE TITLE
AspectInvocationException

### ISSUE THREAD

**Issue by antcore** [dotnetcore/EasyCaching#252]
## Description

AspectCore.DynamicProxy.AspectInvocationException: Exception has been thrown by the aspect of an invocation. ---> Type '<>f__AnonymousType2`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' in Assembly 'Tx.Lims.Service.SqlServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable..

## 返回类型为弱类型  
 
```
using EasyCaching.Core.Interceptor;

public interface ITestService 
 {
        [EasyCachingAble(CacheKeyPrefix = "AUTH_FUNC2", Expiration = 1000 * 60)]
        object GetData();
}

public class TestService :ITestService
{
      public object GetData()
      {
          return new { x = 0 };
      }
}
```
这里是否必须为弱类型，弱类型的话怎么解决

**Comment by catcherwong** [comment]
@antcore  Thanks for your interest in this project.

We will take a look ASAP.

**Comment by catcherwong** [comment]
I have tested this problem with memory cache. But I can not reproduce your issue with memory cache.

> is not marked as serializable

Based on your description, it seems that you don't use memory cache, can use please show us more information about this issue?
