### ISSUE TITLE
 Is there any way to specify [serializable] globally or not

### ISSUE THREAD

**Issue by MartinYl** [dotnetcore/EasyCaching#253]
我是使用EasyCaching.Serialization.Json包，照样要求[Serializable]，每个类都写，很麻烦呀

**Comment by catcherwong** [comment]
@MartinYl Thanks for your interest in this project.

When using `EasyCaching.Serialization.Json` , `[Serializable]`  is optional.

Take a look on the UTs of it.

https://github.com/dotnetcore/EasyCaching/blob/1f6424fe4583501462826ba34432513492ddf89e/test/EasyCaching.UnitTests/SerializerTests/JsonSerializerTest.cs#L27-L52

**Comment by MartinYl** [comment]
我的Startup
```            
            services.AddEasyCaching(option =>
            {
                option.WithJson("rayjson");

                // 添加Redis缓存
                option.UseCSRedis(config =>
                {
                    config.DBConfig.ConnectionStrings = new List<string>() { Configuration.GetConnectionString("RedisConnStr") };
                }, "rayredis");
            });
```

我使用AOP(AspectCore),  [EasyCachingAble(Expiration = 10)]放在我的接口上, 报错信息如下, 添加[Serializable]后正常

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
AspectCore.DynamicProxy.AspectInvocationException: Exception has been thrown by the aspect of an invocation. ---> Sequence contains no matching element.
```

我应该怎么做才能不使用[Serializable], 同时还能序列化成功, 不管是否使用EasyCaching.Serialization.Json或者默认的二进制序列化

**Comment by catcherwong** [comment]
Can you please tell us the version of EasyCaching? So that we can take a look on how to reproduce, or  you can provide a sample to reproduce this issue is more better here.

-------

可以告诉我们您正常使用EasyCaching的版本吗？这样便于我们重现问题，或者您可以提供一个简单的例子可以重现这个问题。

**Comment by MartinYl** [comment]
我提交了一个测试版本，使用的版本都是最新测试版1.1.0-alpha20201010130916
https://github.com/MartinYl/EasyCachingIssues253

**Comment by MartinYl** [comment]
The problem has been solved.

Don't use it like this

> option.UseCSRedis(config =>
{
            config.DBConfig.ConnectionStrings = new List<string>() { Configuration.GetConnectionString("RedisConnStr") + ",defaultDatabase=5" };
}, "rayredis")`.WithJson()`;

or
>option.WithJson("rayjson");
>
>option.UseCSRedis(config =>
{
    config.DBConfig.ConnectionStrings = new List<string>() { Configuration.GetConnectionString("RedisConnStr") + ",defaultDatabase=5" };
}, "rayredis");

The correct way：

>option.WithJson("rayjson");
>
>option.UseCSRedis(config =>
{
    config.DBConfig.ConnectionStrings = new List<string>() { Configuration.GetConnectionString("RedisConnStr") + ",defaultDatabase=5" };
    `config.SerializerName = "rayjson";`
}, "rayredis");


The document I read is old, I didn’t read the [github WIKI](https://github.com/dotnetcore/EasyCaching/wiki/%E7%BC%93%E5%AD%98%E7%9A%84%E5%BA%8F%E5%88%97%E5%8C%96)

**Comment by catcherwong** [comment]
Sorry for the delayed update of the document, I will try to fix it later the week.
