### ISSUE TITLE
Please upgrade csredis reference from 3.2.0 to the latest version(>3.4.0)

### ISSUE THREAD

**Issue by MartinYl** [dotnetcore/EasyCaching#254]
less than 3.4.0 possible throw exception `Exception: 发送数据长度 45369 大于 异步写入缓冲块大小 10240，请设置连接串参数：writeBuffer`

[look this link : csredis/issues/247](https://github.com/2881099/csredis/issues/247#issuecomment-584474515)

**Comment by catcherwong** [comment]
There are some breaking changes of csredis, 

We need to do some type adaptation to upgrade smoothly.
