### ISSUE TITLE
EasyCaching.CSRedis 发送数据长度 10271 大于 异步写入缓冲块大小 10240，请设置连接串参数：writeBuffe 

### ISSUE THREAD

**Issue by AjuPrince** [dotnetcore/EasyCaching#259]
## Description
使用EasyCaching.CSRedis 最新版本（0.9.0）后出现如下图问题：

![image](https://user-images.githubusercontent.com/16829343/98328186-14896600-2030-11eb-8d99-913cabbf8c53.png)
解决方案
https://github.com/2881099/csredis/issues/247
需要将CsRedis升级到最新的3.4.0 
目前采用的是3.2.0
![image](https://user-images.githubusercontent.com/16829343/98328403-a3967e00-2030-11eb-9f5a-3082035ef9a5.png)

希望能尽快解决下这个问题（马上要在生产环境中使用了）谢谢！

**Comment by catcherwong** [comment]
@AjuPrince Thanks for your interest in this project.

We have upgraded it, see #255 

You can have a try with the newest preview version.

**Comment by AjuPrince** [comment]
Thank you for your reply.
