### ISSUE TITLE
LiteDb and SqliteDb problems

### ISSUE THREAD

**Issue by haiduong87** [dotnetcore/EasyCaching#260]
## Description
I've encountered concurrency problem when using LiteDb or SqliteDb

### Steps to Reproduce

1. Use any of two mentions caches
2. Deploy in IIS Web garden model (many workers)

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Provider    : Latest LiteDb or SqliteDb
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : Windows 10 64bit, latest IIS

Problem with LiteDb
- https://github.com/mbdavid/LiteDB/issues/1863
- https://github.com/mbdavid/LiteDB/issues/1546
- Actually we can't handle this...

Problem with SqliteDb
- https://github.com/dotnet/efcore/issues/22756
- https://github.com/dotnet/efcore/issues/20651
- It's about multi threads share one SqliteDbConnection
- My fix

`    
    public class SQLiteDatabaseProvider : ISQLiteDatabaseProvider
    {
        private static ConcurrentDictionary<int, SqliteConnection> _conns;

        /// <summary>
        ///     The builder
        /// </summary>
        private static SqliteConnectionStringBuilder _builder;
        /// <summary>
        ///     The conn.
        /// </summary>
        private static SqliteConnection _conn;

        /// <summary>
        ///     The options.
        /// </summary>
        private readonly SQLiteDBOptions _options;

        public SQLiteDatabaseProvider(string name, SQLiteOptions options)
        {
            DBProviderName = name;
            _options = options.DBConfig;
            _builder = new SqliteConnectionStringBuilder
            {
                DataSource = _options.DataSource,
                Mode = _options.OpenMode,
                Cache = _options.CacheMode
            };

            _conns = new ConcurrentDictionary<int, SqliteConnection>();
        }

        public string DBProviderName { get; } = EasyCachingConstValue.DefaultSQLiteName;

        /// <summary>
        ///     Gets the connection.
        /// </summary>
        /// <returns>The connection.</returns>
        public SqliteConnection GetConnection_Original()
        {
            if (_conn == null)
            {
                _conn = new SqliteConnection(_builder.ToString());
            }

            return _conn;
        }

        /// <summary>
        ///     Get or create the connection from pool (For thread safe)
        /// </summary>
        /// <returns></returns>
        public SqliteConnection GetConnection()
        {
            var threadId = Thread.CurrentThread.ManagedThreadId;
            var con = _conns.GetOrAdd(threadId, CreateNewConnection());
            Task.Run(async () =>
            {
                await Task.Delay(5000).ConfigureAwait(false);
                _conns.TryRemove(threadId, out var removingConn);
                if (removingConn?.State == ConnectionState.Closed)
                {
                    removingConn.Dispose();
                }
            });
            return con;
        }

        private SqliteConnection CreateNewConnection()
        {
            return new SqliteConnection(_builder.ToString());
        }
    }

    /// <summary>
    /// SQLiteCaching provider.
    /// </summary>
    public partial class DefaultSQLiteCachingProvider : EasyCachingAbstractProvider
    {
        /// <summary>
        /// The cache.
        /// </summary>
        private ISQLiteDatabaseProvider _dbProvider;

        /// <summary>
        /// The options.
        /// </summary>
        private readonly SQLiteOptions _options;

        /// <summary>
        /// The logger.
        /// </summary>
        private readonly ILogger _logger;

        /// <summary>
        /// The cache.
        /// </summary>
        private SqliteConnection _cache => _dbProvider.GetConnection();
    }    
`

**Comment by catcherwong** [comment]
@haiduong87  Thanks for your interest in this project.

We will take a look ASAP.

**Comment by catcherwong** [comment]
Based on your sqlite fixed code.

Some Unit tests do not pass yet.

![image](https://user-images.githubusercontent.com/8394988/99742533-a7390300-2b0e-11eb-8c60-bb12b38db78b.png)

**Comment by haiduong87** [comment]
Hi,

I'm not sure the test is stable :(
Just download master branch and try.

![image](https://user-images.githubusercontent.com/22165935/99816404-36c9ca80-2b7e-11eb-91f2-15d774f91593.png)

Note:
- I do several times
- With and without the fix
- Then delete the folder and try again with the original source (the captured picture is the original code)

**Comment by catcherwong** [comment]
When running the unit tests in a single class, all the tests can pass, but running together with 4 classes will not pass.

**Comment by catcherwong** [comment]
I have committed the code, and the unit tests of SQLite runs well in the CI environment.

It seems that there are some difference between using `dotnet test`  and `visual studio`

A preview version was published for this issue.

BTW, PR is welcome, if you find out some problems, you can submit a PR to fix it. 😄

**Comment by haiduong87** [comment]
Hi,

I'm trying to fix the provider https://github.com/dotnetcore/EasyCaching/pull/264

But it does not pass all tests

**Comment by haiduong87** [comment]
Hi @catcherwong 

I think I found the problem,

![image](https://user-images.githubusercontent.com/22165935/100257487-8c381a00-2f78-11eb-834d-efd1ef1d8dfe.png)

This static field is not good for "many providers" case.

And so the latest code has bug too.

I will make change and test again.
