### ISSUE TITLE
BinaryFormatter serialization and deserialization are disabled within this application (.net 5.0 Redis)

### ISSUE THREAD

**Issue by fenglui** [dotnetcore/EasyCaching#261]
## Description

BinaryFormatter serialization and deserialization are disabled within this application (.net 5.0 Redis) 

### Steps to Reproduce

1. Create a new project with .net 5.0
2. Set options.UseRedis

### Related code
in Startup.cs , method ConfigureServices
```
            services.AddEasyCaching(options =>
            {
                options.UseRedis(configure =>
                {
                    configure.DBConfig.Endpoints.Add(
                        new EasyCaching.Core.Configurations.ServerEndPoint("127.0.0.1", 6379)
                    );
                    configure.DBConfig.AllowAdmin = false;
                    configure.EnableLogging = false;
                }, "default");
            });
```

Add a action to test controller 
```
        [HttpGet]
        [ActionName("cacheSet")]
        public object cacheSet()
        {
            cachingProvider.Set(cacheKey, "hi", TimeSpan.FromSeconds(25));

            return Content("ok");
        }
```

visit this url:  /test/cacheGet

**Expected behavior:** [What you expected to happen]
Everythings's ok as same as app under .net core 3.1

**Actual behavior:** [What actually happened]
an error throw:
BinaryFormatter serialization and deserialization are disabled within this application

## Specifications

- Provider    : Redis(version 0.2.0)
- Interceptor : AspectCore (version 5.0.0)
- Serializer  : not use

**Comment by catcherwong** [comment]
@fenglui Thanks for your interest in this project.

We will take a look ASAP.

**Comment by catcherwong** [comment]
In .NET 5 BinaryFormatter was not support.

Take a look on the following information.

https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryFormatter.Core.cs#L14-L17

https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide

**Comment by catcherwong** [comment]
The solution is to use another Serializer to replace the default one.
