### ISSUE TITLE
BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.

### ISSUE THREAD

**Issue by AjuPrince** [dotnetcore/EasyCaching#265]
将EasyCaching.Core 升级到最新的1.1.0 版本后，开始报错
报错信息：BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
项目整体从.Net Core 3.1 升级到 .Net 5.0

**Comment by AjuPrince** [comment]
序列化，尝试使用了WithJson 和 WithSystemTextJson 都报同样的错误

**Comment by alexinea** [comment]
你看一下 #261 是否对你有帮助。

**Comment by AjuPrince** [comment]
#261  
提供的解决方案： The solution is to use another Serializer to replace the default one.
我尝试了官方提供的所有的序列化，都报同样的错误！

**Comment by catcherwong** [comment]
@AjuPrince Thanks for your interest in this project.

> BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.

出现这个错，是因为用到了BinaryFormatter 。

> 序列化，尝试使用了WithJson、 WithSystemTextJson、WithMessagePack 都报同样的错误

如果说您已经尝试过其他序列化方法还是报这个错的话，有可能是序列化的配置没有配置好。

方便的话，贴一下配置那部分的代码，让我们这边好排查问题。

**Comment by AjuPrince** [comment]
![image](https://user-images.githubusercontent.com/16829343/100297120-f5e01480-2fc8-11eb-94c8-d0266869f3a5.png)
目前配置使用的是CsRedis

**Comment by catcherwong** [comment]
少了 `SerializerName` 的配置。

参考下面的文档。

https://github.com/dotnetcore/EasyCaching/wiki/%E7%BC%93%E5%AD%98%E7%9A%84%E5%BA%8F%E5%88%97%E5%8C%96#%E7%A4%BA%E4%BE%8B3

**Comment by AjuPrince** [comment]
有无正确使用的Demo？
