### ISSUE TITLE
NOAUTH Authentication required. Verify if the Redis password provided is correct

### ISSUE THREAD

**Issue by adnan-kamili** [dotnetcore/EasyCaching#267]
## Description

When I use EasyCaching with Redis instance having no username/password set it works fine. But when I use it with any Redis instance with username/password, it gives the following error, even though username/password are correct:

NOAUTH Authentication required. Verify if the Redis password provided is correct

I tried this using Heroku Redis.

```
services.AddEasyCaching(option =>
                {
                    option.UseRedis(config =>
                    {
                        config.DBConfig.AllowAdmin = true;
                        config.DBConfig.Username = Configuration.Get<AppOptions>().Redis.Username;
                        config.DBConfig.Password = Configuration.Get<AppOptions>().Redis.Password;
                        config.DBConfig.Endpoints.Add(new EasyCaching.Core.Configurations.ServerEndPoint(Configuration.Get<AppOptions>().Redis.Host, Configuration.Get<AppOptions>().Redis.Port));
                    }, providerName);
                });
```

For the same Redis instance passing the same Redis URL to StackExchangeRedis works fine:

```
services.AddStackExchangeRedisCache(options =>
                {
                    options.Configuration = Configuration.Get<AppOptions>().Redis.Url;
                    options.InstanceName = "redis-cache";
                });
```

**Comment by catcherwong** [comment]
@adnan-kamili Thanks for your interest in this project.

Which version are you using? 

If you want to use Redis URL, you can use `DBConfig.Configuration`.

Here is a sample.

```
option.UseRedis(config =>
{
    config.DBConfig.Configuration = "myDNS:myPort,password=myPassword,connectRetry=3,connectTimeout=15000,syncTimeout=15000,defaultDatabase=0,abortConnect=false";
    config.SerializerName = "mymsgpack";
}, "redis1");
```

**Comment by adnan-kamili** [comment]
Thanks, it worked now.

I have another question regarding hybrid cache, does it require two separate redis instances or even one would suffice, what are the pros and cons of using two redis instances vs single redis instance.

**Comment by catcherwong** [comment]
> I have another question regarding hybrid cache, does it require two separate redis instances or even one would suffice.

One instance can work well.

> what are the pros and cons of using two redis instances vs single redis instance.

- When two instances are used, one is used to cache data and one is used to cache the bus, and the responsibilities between them are separated.
- When using an instance, the cache data and the cache bus are not separated, but this effect does not affect the operation of hybrid cache.

**Comment by adnan-kamili** [comment]
Thanks, is there any performance gain in using a single instance vs two instances.

**Comment by catcherwong** [comment]
The performance of the two instances may be better, but we did not conduct performance tests for this scenario.

**Comment by adnan-kamili** [comment]
Hi,

When using redis bus there is no option to configure the connection string using:

config.DBConfig.Configuration

So, how should I proceed?

**Comment by catcherwong** [comment]
Following this one.

```cs
option.WithRedisBus(config =>
{
    config.Configuration = "";
});
```

**Comment by adnan-kamili** [comment]
Thanks
