### ISSUE TITLE
DefaultJsonSerializer会添加 UTF-8 BOM到系列化后数据中

### ISSUE THREAD

**Issue by SunGram** [dotnetcore/EasyCaching#272]
## Description
使用System.Text.Json系列化会产生 System.Text.Json.JsonReaderException: '0xEF' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0

https://github.com/Particular/NServiceBus.Newtonsoft.Json/issues/53

**Comment by catcherwong** [comment]
@SunGram  Thanks for your interest in this project.

Have you use both `System.Text.Json` and `Newtonsoft.Json`? 

When this exception will be throw?

**Comment by SunGram** [comment]
是的，使用封装DefaultJsonSerializer读取正常，切换到System.Text.Json封装不正常。单独使用db.StringGet获取文件，然后采用常规的NewtonJson 反系列化报错，采用easycaching中DefaultJsonSerializer的反系列化方法正常，但System.Text.Json封装的方法也报错。(由于redis一些值只有采用easycaching的项目产生的)
采用以下方式可以解析
var json = await _provider.Database.StringGetAsync(      
using (Stream stream = new MemoryStream(json))
{
      var data = await _serializer.DeserializeAsync<UserTokenDto>(stream);
}

**Comment by catcherwong** [comment]
你这边的场景是一个地方写入用 NewtonJson ，另一个地方读取用 System.Text.Json，或者是反过来？

**Comment by SunGram** [comment]
早期服务使用easycaching的newtonjson，新建服务采用 System.Text.Json。

**Comment by catcherwong** [comment]
试了一下，目前EasyCaching中， `System.Text.Json` 不能成功反序列化 `NewtonJson` 的结果， `NewtonJson`可以反序列化 `System.Text.Json` 的结果。

原因在于`NewtonJson` 序列化时，指定了 `Encoding.UTF8`，这个时候，`encoderShouldEmitUTF8Identifier`默认是true，而`System.Text.Json`指定的都是false，也就是 `new System.Text.UTF8Encoding(false)`

https://github.com/dotnetcore/EasyCaching/blob/61f1bd77a822dca7c1e8ee29249000482aa146f2/serialization/EasyCaching.Serialization.Json/DefaultJsonSerializer.cs#L84

测试结果

-  `NewtonJson with UTF8Encoding(true)`   可以反序列化  `NewtonJson with UTF8Encoding(false)` 和`System.Text.Json` 
-  `NewtonJson with UTF8Encoding(false)`   可以反序列化  `NewtonJson with UTF8Encoding(true)` 和`System.Text.Json` 
-  `System.Text.Json`  可以反序列化  `NewtonJson with UTF8Encoding(false)` ，不能反序列化  `NewtonJson with UTF8Encoding(true)`

这个要调整一下EasyCahing里面的Encoding。

**Comment by catcherwong** [comment]
We released `1.2.0-alpha20201224002623` at MyGet to fix this issue.

You can have a try with this version. The MyGet url is https://www.myget.org/F/ncc/api/v3/index.json
