### ISSUE TITLE
Does EasyCaching support redis cluster mode

### ISSUE THREAD

**Issue by lipw2019** [dotnetcore/EasyCaching#276]
The only thing related to redis cluster i found is below
https://github.com/dotnetcore/EasyCaching/blob/1f6424fe4583501462826ba34432513492ddf89e/tools/RedisConfigs/start-cluster.cmd
Just want to confirm if EasyCaching support redis cluster.
If yes, is there any configuration documentation?
Thanks.

**Comment by catcherwong** [comment]
@lipw2019 Thanks for your interest in this project.

It depends on whether the redis clients EasyCaching used can support redis cluster mode or not.

Both of  StackExchange.Redis and CsRedis support redis cluster mode.

**Comment by lipw2019** [comment]
Thanks @catcherwong, 
https://github.com/dotnetcore/EasyCaching/blob/master/src/EasyCaching.Redis/EasyCaching.Redis.csproj
StackExchange.Reids was referenced by EasyCahcing.Redis.  if my project has reference on EasyCaching.Redis, then my project should be support cluster mode. 
If yes, the configuration code is simply add more end points as following, right?
`public class Startup
{
    //...

    public void ConfigureServices(IServiceCollection services)
    {
        //other services.

        //Important step for Redis Caching       
        services.AddEasyCaching(option =>
        {
            option.UseRedis(config => 
            {
                config.DBConfig.Endpoints.Add(new ServerEndPoint("127.0.0.1", 6379));
               config.DBConfig.Endpoints.Add(new ServerEndPoint("127.0.0.1", 7000));
            }, "redis1");
        });
    }
}`

**Comment by catcherwong** [comment]
Yes, just following `StackExchange.Redis`'s Configuration.

https://stackexchange.github.io/StackExchange.Redis/Configuration

**Comment by lipw2019** [comment]
Thanks @catcherwong, i think i had got the point now.
