### ISSUE TITLE
Caching provider decorators for circuit breaker and fallbacks

### ISSUE THREAD

**Issue by Youkai-no-nii-chan** [dotnetcore/EasyCaching#278]
## Problem description

When we are using distributed cache and cache server is down there are several desired options to handle it in different usecases:

1. Hybrid cache (InMemory + Distributed): use InMemory caching provider until cache server will be available.
2. Simple distributed cache: Cache nothing until cache server will be available.
	
If we have big workload, curcuit breaker is required in all of this cases.

Now if redis is down during application start, it crashes here https://github.com/dotnetcore/EasyCaching/blob/master/src/EasyCaching.Redis/DefaultRedisCachingProvider.cs#L80-L81
To handle this, we need circuit breaker and fallback not only for caching provider methods, but although for its initilaliztion. 

## Proposal
- Add configured decorators to caching providers.
- Decorators can be wrapped in each other.
- Add fallback decorator.
- Add curcuit breaker decorator using Polly.

## Configuration example

Redis with circuit breaker (for using with hybrid cache in case 1).
```
services.AddEasyCaching(x =>
	x.UseRedis(options =>
	{
		options.DBConfig.Configuration = "127.0.0.1:9999,allowAdmin=false,defaultdatabase=9,connectTimeout=100";

		var initCircuitBreakerParameters =
			new CircuitBreakerParameters(
				exceptionsAllowedBeforeBreaking: 1,
				durationOfBreak: TimeSpan.FromMinutes(1));
		var executeCircuitBreakerParameters =
			new AdvancedCircuitBreakerParameters(
				failureThreshold: 0.1,
				samplingDuration: TimeSpan.FromSeconds(15),
				minimumThroughput: 10,
				durationOfBreak: TimeSpan.FromSeconds(60));

		options
			.DecorateWithCircuitBreaker(
				exception => exception is RedisException,
				initCircuitBreakerParameters,
				executeCircuitBreakerParameters)
		);
	}, 
	ProviderName)
);
```
When redis is fully down and we fail on creating caching provider, we would like to break circuit faster and advanced circuit breaker is badly suited for this. Thats why it's good to have option to make different circuit breakers for initialization and execution. 

Redis with circuit breaker and fallback to cache nothing (case 2) 
```
services.AddEasyCaching(x =>
	x.UseRedis(options =>
	{
		options.DBConfig.Configuration = "127.0.0.1:9999,allowAdmin=false,defaultdatabase=9,connectTimeout=100";

		var initCircuitBreakerParameters =
			new CircuitBreakerParameters(
				exceptionsAllowedBeforeBreaking: 1,
				durationOfBreak: TimeSpan.FromMinutes(1));
		var executeCircuitBreakerParameters =
			new AdvancedCircuitBreakerParameters(
				failureThreshold: 0.1,
				samplingDuration: TimeSpan.FromSeconds(15),
				minimumThroughput: 10,
				durationOfBreak: TimeSpan.FromSeconds(60));
            
		options
			.DecorateWithCircuitBreaker(
				exception => exception is RedisException,
				initCircuitBreakerParameters,
				executeCircuitBreakerParameters)
			.DecorateWithWithFallback(
				exception => exception is RedisException,
				(name, serviceProvider) => new NullCachingProvider(name, options))
		);
	}, 
	ProviderName)
);
 ```

**Comment by Youkai-no-nii-chan** [comment]
Added Circuit breaker for bus https://github.com/dotnetcore/EasyCaching/pull/284/files/18040e54225f06834ba11ad237ec31453e464b00..3be305782377f7fe4a9646c4ca7f26a2e00b9dab

Although we've had a problem when subscription for redis topic fails during initialization and application crashes. So I've added infnite async retry, when Bus Circuit breaker is enabled.

Typical resilent bus settings:
```
busOptions
                            .DecorateWithCircuitBreaker(
                                initParameters: circuitBreakerParameters,
                                executeParameters: circuitBreakerParameters,
                                subscribeRetryInterval: TimeSpan.FromMinutes(1))
                            .DecorateWithRetry(3)
                            .DecorateWithPublishFallback();
```

Policy wrappers for bus moved from HybridCachingProvider to bus decorators. There is still 3 retries and publish fallback by default, but to change it you should set decoratros inBusOptions instead of simple BusRetryCount in HybridCachingOptions:
```
 busOptions
                            .DecorateWithRetry(6)
                            .DecorateWithPublishFallback();
```

**Comment by Youkai-no-nii-chan** [comment]
@catcherwong when will you have opportunity to review these PRs?
I'm planning to add some other small enchantments and bug fixes and soon it will become a problem that my fork is many commits ahead.

**Comment by catcherwong** [comment]
@Youkai-no-nii-chan  I'm a little busy these days.  I will review these PRs after this week.

**Comment by catcherwong** [comment]
I took another look at this question. I think the better solution for this problem is to customize the corresponding provider and bus instead of directly adjusting the provider and bus provided by default.

EasyCaching is a caching abstraction layer that provides a relatively flexible extension mechanism. All methods are interface-oriented. If the default implementation cannot meet the business requirements, you can completely replace the default implementation with a custom implementation.

**Comment by catcherwong** [comment]
Add a new provider that support circuit breaker and fallback.

```cs
public class CircuitBreakerAndFallbackProvider : IEasyCachingProvider
{
//  custom implementation
}
```

And use this new provider to replace the default one.

```diff
            services.AddEasyCaching(option =>
            {
--               option.UseXxx("default");
++               option.UseXxxWithCircuitBreakerAndFallback("cus");
            });
```

**Comment by shamiz01** [comment]
liwa music
tehran 
https://liwa.ir/
Listening to music is the most enjoyable thing in the world

**Comment by catcherwong** [comment]
Close due to inactive.
