### ISSUE TITLE
EasyCaching.Disk; when the cache expired, it tries to overwrite the existing file and thrown "File Exists" error.

### ISSUE THREAD

**Issue by muskara** [dotnetcore/EasyCaching#280]
## Description

Provider    : EasyCaching.Disk
When I try to add the expired key again, it throws an error stating that the file already exists. When I review the code, the file of the expired key is still on the disk. When I continue to examine it with the idea of maybe overwriting it, I see that it is trying to create a new file. Since a file already exists, it cannot create a new one and the file throws the already existing error.

My expectation; overwriting the key file or deleting the expired key file.

DefaultDiskCachingProvider.Async.cs:
```
 public override async Task<bool> BaseTrySetAsync<T>(string cacheKey, T cacheValue, TimeSpan expiration)
        {
            ArgumentCheck.NotNullOrWhiteSpace(cacheKey, nameof(cacheKey));
            ArgumentCheck.NotNull(cacheValue, nameof(cacheValue), _options.CacheNulls);
            ArgumentCheck.NotNegativeOrZero(expiration, nameof(expiration));

            var (path, fileName) = GetFilePath(cacheKey);

            if (File.Exists(path))
            {
                var cached = await GetDiskCacheValueAsync(path);

                if (cached.Expiration.Subtract(DateTimeOffset.UtcNow) > TimeSpan.Zero)
                {
                    return false;
                }
            }

            var bytes = BuildDiskCacheValue(cacheValue, expiration);

**//Throws an error if the file exists**
            using (FileStream stream = new FileStream(path, FileMode.CreateNew, FileAccess.Write, FileShare.None))
            {
                await stream.WriteAsync(bytes, 0, bytes.Length);
                AppendKey(cacheKey, fileName);
                return true;
            }
        }
```

## Specifications

- Provider    : EasyCaching.Disk
- Interceptor : AspectCore (version 3.1)
- Serializer  : not use
- System      :  Windows

**Comment by catcherwong** [comment]
@muskara Thanks for your interest in this project.

You are right!

Can you submit a RP to fixed this issue?

**Comment by catcherwong** [comment]
Done it. Please have a try with the newest version.
