### ISSUE TITLE
Suggestion : Implementation of EasyCaching for Redis: expose SyncTimeout and AsyncTimeout setting

### ISSUE THREAD

**Issue by JadaVonRuth** [dotnetcore/EasyCaching#282]
## Description

Hi, I noticed that currently its not possible to pass these settings when adding to DI because these properties are not exposed (but StackExchange.Redis does). These are sometimes necessary to modify due to sync timeout errors (storing larger objects to redis)

### Steps to Reproduce

1.  Try to initialize redis using EasyCaching with SyncTimeout set to 10s
2.  Try to initialize redis using EasyCaching with AsyncTimeout set to 10s

### Related code

```
services.AddEasyCaching(options =>
              {
                  options.WithJson();
                  options.UseRedis(config =>
                  {
                      config.DBConfig.Endpoints.Add(new ServerEndPoint(cachingOptions.RedisServer.Host, cachingOptions.RedisServer.Port));
                      config.SerializerName = "json";
                      // config.SyncTimeout = mycustomvalue; // this is missing
                      // config.AsyncTimeout = mycustomvalue; // this is missing
                      config.DBConfig.ConnectionTimeout = 3000;
                  }, cachingOptions.RedisServer.Name);
              });
```

**Expected behavior:** Able to configure these properties in strongly typed way

**Actual behavior:** Unable to configure these properties in strongly typed way

## Specifications

- Provider    : Redis
- Serializer  :  json
- System      : debian

**Comment by catcherwong** [comment]
@JadaVonRuth Thanks for your interest in this project.

You can use DBConfig.Configuration.

Here is a sample.

```cs
option.UseRedis(config =>
{
    config.DBConfig.Configuration = "myDNS:myPort,password=myPassword,connectRetry=3,connectTimeout=15000,syncTimeout=15000,defaultDatabase=0,abortConnect=false";
    config.SerializerName = "mymsgpack";
}, "redis1");
```

**Comment by JadaVonRuth** [comment]
I am aware of this option, but this is more of a dirty workaround to me, its not strongly typed - its just bunch of settings in one string, therefore its not validatable before passing values from another options object coming from higher level library on startup, its not handy this way and who knows how it gets messed up when combined with other strongly typed configuration  you have there and thats why I suggested it, they are important  (I dont see a good reason why not expose those explicitly) Would it be a problem to expose those please? Thank you

**Comment by catcherwong** [comment]
PR is welcome. 

You can make some changes to improve this issue, and submit a PR to `dev` branch. 

We will have someone to follow up and review the PR.

**Comment by catcherwong** [comment]
Done it. Please have a try with the newest version.

**Comment by JadaVonRuth** [comment]
Thanks much, will try tomorrow
