### ISSUE TITLE
EasyCachingAble 特性 不支持异步方法吗

### ISSUE THREAD

**Issue by Robinloveyou** [dotnetcore/EasyCaching#287]
贴在接口的异步方法上不起作用, 运行到await后无反应,也不报错.

**Comment by catcherwong** [comment]
@Robinloveyou  谢谢您对这个项目感兴趣。

支持异步方法的，您可以看看这个sample.

 https://github.com/dotnetcore/EasyCaching/tree/master/sample/EasyCaching.Demo.Interceptors/

**Comment by Robinloveyou** [comment]
好的,十分感谢.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/EasyCaching"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月23日(星期二) 晚上10:16
收件人:&nbsp;"dotnetcore/EasyCaching"<EasyCaching@noreply.github.com&gt;;
抄送:&nbsp;"Robin"<20521097@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dotnetcore/EasyCaching] EasyCachingAble 特性 不支持异步方法吗 (#287)





 
@Robinloveyou  谢谢您对这个项目感兴趣。
 
支持异步方法的，您可以看看这个sample.
 
https://github.com/dotnetcore/EasyCaching/tree/master/sample/EasyCaching.Demo.Interceptors/
