### ISSUE TITLE
InMemory and RedisBus ONLY, not Redis cache lookup

### ISSUE THREAD

**Issue by jasenf** [dotnetcore/EasyCaching#288]
Hi,

Is it possible to configure EasyCaching to use ONLY in-memory for caching, and RedisBus as the communication mechanism across servers. What I do NOT want to do is use Redis as a secondary cache. We are having performance problems when the cache has to go back to Redis, so we only want Redis as the invalidation and synchronization bus, not to actually be used to look up cached data.

We have the Hybrid cache already configured but would like to stop Redis from being used as the cache lookup.

Can someone provide a configuration example for this?## Description

**Comment by catcherwong** [comment]
@jasenf  Thanks for your interest in this project.

You can add your own implementation for a fake Redis provider following `EasyCaching.Redis` that all the method do nothing, just skip or return some empty values..

So that you can replace it.

```cs
            services.AddEasyCaching(option =>
            {
                option.UseInMemory("m1");

                // your own provider
                option.UseFakeRedis(config =>
                {
                }, "myredis");

                option.UseHybrid(config =>
                {//....
                });

                option.WithRedisBus(config =>
                {//.....
                });
            });
```

**Comment by jasenf** [comment]
So with that scenario Redis will still be used as the backchannel for invalidating local memory caches?

**Comment by catcherwong** [comment]
Yes.

**Comment by adnan-kamili** [comment]
This method sounds a bit hacky. Is there a better alternative?

**Comment by jasenf** [comment]
I did build the provider and it does work.  I would love to see a native "Redis as back-plane only" solution though.
