### ISSUE TITLE
在存取string字符串的时候，使用的是redis和json序列化

### ISSUE THREAD

**Issue by quan01994** [dotnetcore/EasyCaching#29]
出现错误。
![image](https://user-images.githubusercontent.com/20533465/37944559-a6621734-31ae-11e8-9cec-278631bc1f71.png)
![image](https://user-images.githubusercontent.com/20533465/37944567-af98b20e-31ae-11e8-8ac6-53b7e1ea4c15.png)

**Comment by catcherwong** [comment]
@quan01994 

Could you please provide me a sample string that `WeChatHelper.GetAccessToken(AppId, AppSecret)` generate ?

**Comment by quan01994** [comment]
应该是我的错，我忘记加 await 导致反序列化的时候出现了异常。
