### ISSUE TITLE
多层缓存链路更新问题

### ISSUE THREAD

**Issue by hu372197979** [dotnetcore/EasyCaching#296]
在实际业务开发中 有直接在接口的出口做单次缓存情况，EasyCache 在这种场景能解决问题。
同时调用链路上的其他缓存也存在缓存，怎么优雅的去设计一套机制，在整个链路上的向下依赖的缓存发生改变触发链路之上的其他缓存更新。
例如 ControllerA -> cache1 -> cache2 -> cache3 -> cache4
当 cache4 发生改变时 应该触发 cache1，cache2，cache3 失效，当访问时重新计算缓存。
当 cache3 发生改变时 应该触发 cache1，cache2 失效。
这里需要解决的是如何通过框架收集到整个缓存链路关系，通过关系完成缓存的更新，希望高人指导！
@catcherwong

**Comment by catcherwong** [comment]
从你的描述来看，是缓存依赖问题，而且是 `多个key + 顺序` 的缓存依赖。

这个业务耦合有点大，这边只能提供一个**参考想法，不一定合适**。

你可以从 key 上面去做点文章，设计 key 的时候，可以分为3个部分：

1. 相依赖的，同一个前缀，如  `mycache` 
2. 有顺序的，指定对应的数字，如 `1`
3. 业务属性，如 `product`

这个时候，key 大概会是这个样子 `mycache:1:product`，`mycache:2:product`，`mycache:3:product`

假设 `mycache:2:product` 这个 key 发生了改变，通知出去了，订阅方收到这个通知，就**解析 key**，根据解析出来的顺序，**把小于当前顺序的移除掉**，也就是把 `mycache:1:product`移除掉。
