### ISSUE TITLE
Does it support the Task<T>？

### ISSUE THREAD

**Issue by l1044635791** [dotnetcore/EasyCaching#30]
[EasyCachingAble (Expiration = 100)]
        Task<PremiseTrans> GetPremise (int id);

        [EasyCachingAble (Expiration = 100)]
        Task<PremiseTrans> GetPremise (string letter);

        [EasyCachingAble (Expiration = 100)]
        Task<IEnumerable<PremiseSimple>> GetPremises (string search, string sort, string order);

        [EasyCachingAble (Expiration = 1000)]
        Task<IEnumerable<PremiseTrans>> GetPremises (string search, string area, string price, string houseType, string special, string type, string sort, string order, string query, int limit = 10, int pageIndex = 1, int skip = 0);

        [EasyCachingAble (Expiration = 1000, CacheKeyPrefix = "Premise")]
        Task<long> GetCountAsync (string search, string area, string price, string houseType, string special, string type, string sort, string order, string query);

**Comment by l1044635791** [comment]
Does it support the Task<T>？

**Comment by catcherwong** [comment]
@l1044635791 Thanks for your interest in the project.

The interceptors support `Task<T>` ! I will add some unit tests and samples for this later! :smile:

**Comment by l1044635791** [comment]
Thank you very much!

**Comment by catcherwong** [comment]
1. Add a simple method for this

- AspectCore [IDatetimeServices](https://github.com/dotnetcore/EasyCaching/blob/dev/sample/EasyCaching.Demo.Interceptor.AspectCore/Services/IDatetimeServices.cs) 
- Castle [IDatetimeServices](https://github.com/dotnetcore/EasyCaching/blob/dev/sample/EasyCaching.Demo.Interceptor.Castle/Services/IDatetimeServices.cs)

2 .Add some Unit tests here 

[InterceptorTests](https://github.com/dotnetcore/EasyCaching/tree/dev/test/EasyCaching.UnitTests/InterceptorTests)

**Comment by catcherwong** [comment]
If you met some problems for this, open a new issue and I will answer and fix it ASAP.
