### ISSUE TITLE
序列化不起作用

### ISSUE THREAD

**Issue by zenglei286** [dotnetcore/EasyCaching#300]
services.AddEasyCaching(option =>
            {

                //// 读取配置文件
                option.UseInMemory(Configuration, "statics", "easycaching:statics");

                option.UseRedis(Configuration, "dynamic", "easycaching:dynamic").WithSystemTextJson();

            });
我查看到的dynamic这个redis的缓存库，用的还是默认的二进制的序列化，而不是JSON

**Comment by catcherwong** [comment]
@zenglei286  Thanks for your interest in this project.

Please take a look on this documents.

https://github.com/dotnetcore/EasyCaching/wiki/%E7%BC%93%E5%AD%98%E7%9A%84%E5%BA%8F%E5%88%97%E5%8C%96
