### ISSUE TITLE
HybridCaching 二级缓存,WithJson 没效果

### ISSUE THREAD

**Issue by suichuan** [dotnetcore/EasyCaching#304]
历史原因,redis上存储的序列化都是使用Newtonsoft.Json, 今天使用HybridCaching 二级缓存,发现set 使用的是二进制,即使使用了Serializer覆盖(WithJson ) 也没用

**Comment by catcherwong** [comment]
@suichuan 谢谢您对这个项目感兴趣。

序列化这一块都是使用的二进制。

如果之前使用的`Newtonsoft.Json`也是基于二进制的，那么可以无缝切换，如果用的是字符串，这样是没办法直接切换的，存储的格式已经不一样了。

**Comment by suichuan** [comment]
谢谢回复,其它Provider都有注入IEasyCachingSerializer ,为什么HybridCachingProvider不实现,出于什么考虑不解...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/EasyCaching"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 中午1:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/EasyCaching] HybridCaching 二级缓存,WithJson 没效果 (#304)





 
@suichuan 谢谢您对这个项目感兴趣。
 
序列化这一块都是使用的二进制。
 
如果之前使用的Newtonsoft.Json也是基于二进制的，那么可以无缝切换，如果用的是字符串，这样是没办法直接切换的，存储的格式已经不一样了。

**Comment by catcherwong** [comment]
`HybridCachingProvider` 严格意义上是基于其他 Provider 的组合，所以对Hybrid来说，`IEasyCachingSerializer ` 并不是必须的。
