### ISSUE TITLE
Error in RemoveByPrefixAsync

### ISSUE THREAD

**Issue by julianodev** [dotnetcore/EasyCaching#316]
## Description

Hello friends, I'm trying to delete some redis keys, using a removeByPrefix but this error is popping all the time. My Application is on a server, and redis on another server.

Can you help me?

### Related code

```

Example:   await _easyCachingProvider.RemoveByPrefixAsync("chat.system.id.1.user");
```

**Expected behavior:** 
The other methods work normally, below is the reported error

**Actual behavior:** 

Error in RemoveByPrefixAsync, message:StackExchange.Redis.RedisTimeoutException: Timeout performing SCAN (5000ms), next: SCAN, inst: 2246, qu: 0, qs: 50, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: 194.163.145.82:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: vmi601680, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=52,Free=32715,Min=4,Max=32767), v: 2.1.58.34321 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

## Specifications

- Provider    : InMemory (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : CentOS 7.2

**Comment by catcherwong** [comment]
@julianodev Thanks for your interest in this project.

For this issue, you should following https://stackexchange.github.io/StackExchange.Redis/Timeouts to adjust.

**Comment by julianodev** [comment]
It wasn't too obvious, do I have to install this package? StackExchange.Redis

And change any settings on my server? Can you give me a light?

**Comment by catcherwong** [comment]
Based on your description, the provider you are using is `EasyCaching.Redis`.  

This provider depends on `StackExchange.Redis` to communicate with Redis server, and you do not need to install it.

For this timeout exception of `StackExchange.Redis`, there are many posts you can find via Google.

Maybe you can have a try to modify the value of min threads based on  https://stackexchange.github.io/StackExchange.Redis/Timeouts
