### ISSUE TITLE
cachingProvider.RemoveAll() without parameter

### ISSUE THREAD

**Issue by azhe403** [dotnetcore/EasyCaching#320]
Seem we need RemoveAll cache with out parameter, or can called by remove everything for invalidate all cache.

For now I use following code

```
var listPrefix = new List<string>
{
    "foo",
    "bar",
    "another-foo"
};

listPrefix.ForEach(prefix => {
   cachingProvider.RemoveByPrefix(prefix);
});
```

Instead of write above code, we may can write single like below

` cachingProvider.RemoveAllAsync()`

 Would you consider to add this feature?

**Comment by catcherwong** [comment]
@azhe403 Thanks for your interest in this project.

Remove all cache without parameters will put lots of pressure on the cache server, which is a very dangerous operation!

Keep this issue open, and see if others need this feature as well.

**Comment by catcherwong** [comment]
Close due to inactive.
