### ISSUE TITLE
Multiple cache drivers use

### ISSUE THREAD

**Issue by jianxuanbing** [dotnetcore/EasyCaching#33]
Need to use In-Memory and redis , How to use multiple cache source? Two level cache?

**Comment by catcherwong** [comment]
@jianxuanbing  Thanks for your interest in the project.

If you want to use 2-level cache, you can use HybirdCachingProvider. Please following this [document](http://easycaching.readthedocs.io/en/latest/Hybrid/).

But it's not convenient to use at this time for hybrid, I'm refactoring now.

**Comment by catcherwong** [comment]
The [document](http://easycaching.readthedocs.io/en/latest/Hybrid/) of HybridCachingProvider was updated.

**Comment by naveedahmed1** [comment]
Just a quick question related to this. Can we use InMemory caching and Disk caching together. I mean if the value exist in Memory, its returned from there; otherwise read from the Disk.
