### ISSUE TITLE
high availibility support in easycahing.redis

### ISSUE THREAD

**Issue by alisadri1993** [dotnetcore/EasyCaching#332]
hi guys recently im using easycaching.redis. i have problem with high availibility option on redis with stachexchange provider there is such support for high availibility in easycaching.redis version

**Comment by alisadri1993** [comment]
is ther any option to using redis sentinel
in bellow config

`
 services.AddEasyCaching(option =>
        {
            option.UseRedis(config => 
            {
                config.DBConfig.Endpoints.Add(new ServerEndPoint("127.0.0.1", 6379));
            }, "redis1");
        });
`

**Comment by catcherwong** [comment]
@alisadri1993  Thanks for your interest in this project , and I'm very sorry to reply to you for so long.

> is ther any option to using redis sentinel

Yes, the following code demonstrate it.

```cs
option.UseRedis(config =>
{
    config.DBConfig.Configuration = "localhost,serviceName=mymaster";
    config.SerializerName = "mymsgpack";
}, "redis1")
.WithMessagePack("mymsgpack");
```

You also can find more information in https://stackexchange.github.io/StackExchange.Redis/Configuration#basic-configuration-strings

**Comment by alisadri1993** [comment]
Thank you about your response
i run my redis instances on linux and what you mean about serviceName in connection configuration?

**Comment by alisadri1993** [comment]
i get this error 

> "The ConnectionMultiplexer is not a Sentinel connection."

**Comment by catcherwong** [comment]
Please following https://stackexchange.github.io/StackExchange.Redis/Configuration

![image](https://user-images.githubusercontent.com/8394988/145677389-b5792c75-21d6-4ac0-9ed9-823e818998d1.png)

**Comment by alisadri1993** [comment]
Thank you @catcherwong
