### ISSUE TITLE
有LRU淘汰算法的支持计划吗?

### ISSUE THREAD

**Issue by BigDream324** [dotnetcore/EasyCaching#336]
目前在寻找高效的LRU淘汰算法支持的Cache库,请问EasyCaching有这个计划支持吗

**Comment by catcherwong** [comment]
@BigDream324   Thanks for your interest in this project.

LRU is only implemented in memory cache, but the current implementation is not very efficient. For distributed cache, it is determined by the corresponding product.

------

LRU，只在 Memory 缓存这一块有实现，不过现在的实现并不会说很高效。对于 Distributed 缓存的话，还是由对应产品决定的。
