### ISSUE TITLE
abortConnect in Sentinel connection 

### ISSUE THREAD

**Issue by alisadri1993** [dotnetcore/EasyCaching#337]
I using easycaching in hybrid mdoe and i hava an issue when i set connection to sentinel in correct way every thing is ok but when redis server is inaccesible i expect that easycaching ignore redis and just use inmemory mode. but in reality it throw an exception. is there any config to achive that goal  i use stackexchange version

**Comment by alisadri1993** [comment]
`config.DBConfig.Configuration = $"localhost:26379,serviceName=mymaster";`
This is my connection string and  i got this exception "It was not possible to connect to the redis server(s). UnableToConnect on localhost:26379/Interactive, Initializing/NotStarted"

**Comment by catcherwong** [comment]
@alisadri1993 Thanks for your interest in this project.

Could you show us the StackTrace of this exception.

When the redis server is inaccessible, your application will run well if you are using hybrid.

How do you use hybird provider?  `IHybridCachingProvider ` or `IEasyCachingProvider `?

**Comment by alisadri1993** [comment]
> @alisadri1993 Thanks for your interest in this project.
> 
> Could you show us the StackTrace of this exception.
> 
> When the redis server is inaccessible, your application will run well if you are using hybrid.
> 
> How do you use hybird provider? `IHybridCachingProvider ` or `IEasyCachingProvider `?

`private readonly IHybridCachingProvider _hybridCachingProvider;

        public CacheService(IHybridCachingProvider hybridCachingPtovider)
        {
            this._hybridCachingProvider = hybridCachingPtovider;
        }`

`services.AddEasyCaching(option =>
            {
                //local in memory cache
                option.UseInMemory(redisConfig.LocalCacheProviderName);

                //distributed cach
                option.UseRedis(config =>
                {
                    //redisConfig.RedisList.ForEach(r => config.DBConfig.Endpoints.Add(new ServerEndPoint(r.Host, r.Port)));                    
                    config.DBConfig.Configuration = $"192.168.106.210:26379,serviceName=mymaster";

                    //config.DBConfig.AbortOnConnectFail = true;
                    config.DBConfig.Database = redisConfig.DefaultDatabase;
                    config.DBConfig.AsyncTimeout = 5000;
                    config.DBConfig.SyncTimeout = 5000;

                }, redisConfig.DistributedCacheProviderName);

                option.UseHybrid(config =>
                {
                    config.TopicName = "topic";
                    //config.EnableLogging = true;
                    // specify the local cache provider name
                    config.LocalCacheProviderName = redisConfig.LocalCacheProviderName;

                    // specify the distributed cache provider name
                    config.DistributedCacheProviderName = redisConfig.DistributedCacheProviderName;
                })
                .WithRedisBus(busCfg =>
                {
                    busCfg.Endpoints.Add(new ServerEndPoint(redisConfig.Host, redisConfig.Port));
                });

            });`


`   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1169
   at StackExchange.Redis.ConnectionMultiplexer.SentinelConnect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1070
   at StackExchange.Redis.ConnectionMultiplexer.SentinelMasterConnect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1103
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1037
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at EasyCaching.Redis.RedisDatabaseProvider.GetDatabase()
   at EasyCaching.Redis.DefaultRedisCachingProvider..ctor(String name, IEnumerable`1 dbProviders, IEnumerable`1 serializers, RedisOptions options, RedisLockFactory factory, ILoggerFactory loggerFactory)`

**Comment by alisadri1993** [comment]
this exception occured when i set sentinel mode on redis configuration

**Comment by alisadri1993** [comment]
dear @catcherwong  can u help me on above question?

**Comment by catcherwong** [comment]
Please provide a simple demo.

**Comment by alisadri1993** [comment]
> Please provide a simple demo.

I created demo api app here [https://github.com/alisadri1993/Easycaching.Hybrid.Sentinel.Demo](url)

**Comment by alisadri1993** [comment]
> Please provide a simple demo.

I created demo api app here https://github.com/alisadri1993/Easycaching.Hybrid.Sentinel.Demo

**Comment by alisadri1993** [comment]
@catcherwong Did you check demo api?

**Comment by catcherwong** [comment]
I have checked your sample yet.

>  but when redis server is inaccesible i expect that easycaching ignore redis and just use inmemory mode.

Before running the App, if the redis server is not running, it will throw the exception you met.

After running the App, if the redis server is down, it will work well.

**Comment by alisadri1993** [comment]
Thank you  @catcherwong.
 How can I prevent this Problem ?

> Before running the App, if the redis server is not running, it will throw the exception you met.

**Comment by alisadri1993** [comment]
@catcherwong  is there any solution to avoid distributed cache when redis is inaccessible in easycaching hybrid mode?

**Comment by catcherwong** [comment]
At this time, we can not avoid it.
