### ISSUE TITLE
Issue with RemoveByPrefix(Async)

### ISSUE THREAD

**Issue by marklonquist** [dotnetcore/EasyCaching#343]
## Description

In `DefaultRedisCachingProvider` the method `BaseRemoveByPrefixAsync` does not handle `_options.DBConfig.KeyPrefix` correctly.

The `SearchRedisKeys` calls the server directly using `server.Keys` method, which does NOT use KeyPrefix from config.

### Steps to Reproduce

1. Add a key to redis (which uses KeyPrefix)
2. Try and remove using RemoveByPrefix
3. Notice that it is NOT deleted

### Related code
This code handles it, but maybe you need to refactor it.

We need to add the KeyPrefix before we search, and remove it again after before deleting the keys as the _cache object DOES handle KeyPrefix.
```
public override async Task BaseRemoveByPrefixAsync(string prefix)
      {
          ArgumentCheck.NotNullOrWhiteSpace(prefix, nameof(prefix));

          prefix = this.HandlePrefix(prefix);

          if (!string.IsNullOrWhiteSpace(_options.DBConfig.KeyPrefix))
          {
              prefix = _options.DBConfig.KeyPrefix + prefix;
          }

          if (_options.EnableLogging)
              _logger?.LogInformation($"RemoveByPrefixAsync : prefix = {prefix}");

          var redisKeys = this.SearchRedisKeys(prefix);

          if (!string.IsNullOrWhiteSpace(_options.DBConfig.KeyPrefix))
          {
              var prefixLength = _options.DBConfig.KeyPrefix.Length;

              for (var i = 0; i < redisKeys.Length; i++)
              {
                  var key = redisKeys[i];
                  var keyString = key.ToString();
                  if (!keyString.StartsWith(_options.DBConfig.KeyPrefix))
                      continue;

                  redisKeys[i] = new RedisKey(keyString.Remove(0, prefixLength));
              }
          }

          await _cache.KeyDeleteAsync(redisKeys);
      }
```

I also got a suggestion to keep fetching keys until there is no more matches:
```
private RedisKey[] SearchRedisKeys(string pattern)
        {
            var keys = new List<RedisKey>();

            foreach (var server in _servers)
            {
                // the default pageSize is 10, if there are too many keys here, it will hurt performance
                // see https://github.com/dotnetcore/EasyCaching/pull/199 for more information
                // from this redis dev specification, https://yq.aliyun.com/articles/531067 , maybe the appropriate scope is 100~500, using 200 here.
                var foundKeys = server.Keys(pattern: pattern, database: _cache.Database, pageSize: 200).ToList();
                keys.AddRange(foundKeys);

                while (foundKeys.Count >= 200)
                {
                    foundKeys = server.Keys(pattern: pattern, database: _cache.Database, pageSize: 200).ToList();
                    keys.AddRange(foundKeys);
                }
            }

            return keys.Distinct().ToArray();

            //var keys = new HashSet<RedisKey>();

            //int nextCursor = 0;
            //do
            //{
            //    RedisResult redisResult = _cache.Execute("SCAN", nextCursor.ToString(), "MATCH", pattern, "COUNT", "1000");
            //    var innerResult = (RedisResult[])redisResult;

            //    nextCursor = int.Parse((string)innerResult[0]);

            //    List<RedisKey> resultLines = ((RedisKey[])innerResult[1]).ToList();

            //    keys.UnionWith(resultLines);
            //}
            //while (nextCursor != 0);

            //return keys.ToArray();
        }
```

**Expected behavior:**
The key should be removed

**Actual behavior:**
Is not removed

## Specifications
- Provider    : Redis (newest)

**Comment by catcherwong** [comment]
@marklonquist   Thanks for your interest in this project.

> This code handles it, but maybe you need to refactor it.

Could you send a PR for this one?

BTW, the operation of  prefix should in **HandlePrefix** method

https://github.com/dotnetcore/EasyCaching/blob/f657a7e2545a9e170a23b5f3e692fb17c930aa21/src/EasyCaching.Redis/DefaultRedisCachingProvider.cs#L333-L347

> I also got a suggestion to keep fetching keys until there is no more matches:

This is not a good idea, maybe can find more information about `SCAN` command of redis.

**Comment by marklonquist** [comment]
We will have to also handle removing the `keyPrefix` again once we found the keys in the "SearchRedisKeys". I'll make a PR.

I understand the reasoning behind why we shouldn't keep looking at keys in the server.Keys method. But it's not a very reliable to only remove 200 if there is more. I would expect ALL keys with the prefix would be removed.

Will look into a better way.
