### ISSUE TITLE
Best way to export IConnectionMultiplexer  from EasyCaching

### ISSUE THREAD

**Issue by feritzcan2** [dotnetcore/EasyCaching#347]
Hello, I'm using easycaching for simple cache functionalities.  But now, I'm required to use redis PUB/SUB too which I cant do using easy caching.  In need IConnectionMultiplexer.

I dont think it would be best way If I create another instance of IConnectionMultiplexer and inject as singleton again.  Is there a way I can access IConnectionMultiplexer that EasyCaching uses?  

Would it be best practice if I create another instance of IConnectionMultiplexer?  Or maybe would you suggest me to just quit using easycaching and use IConnectionMultiplexer on my own?

Thank you...

**Comment by catcherwong** [comment]
@feritzcan2 Thanks for your interest in this project.

We only export ** IDatabase** for users, you can use it to get the **Multiplexer**.

The following code demonstrate how to do.

```cs
private readonly IEasyCachingProvider _provider;

public void SomeMethod()
{
    // ensure the instance of _provider is using StackExchange.Redis
    var db = (StackExchange.Redis.IDatabase)_provider.Database;
    var multiplexer = db.Multiplexer;
}
```
