### ISSUE TITLE
Unable to get updates into redis using Hybrid

### ISSUE THREAD

**Issue by Dispersia** [dotnetcore/EasyCaching#348]
## Description

Using Hybrid, I'm unable to get two apps to communicate using Redis to update cache

### Steps to Reproduce

```
using EasyCaching.Core;

var builder = WebApplication.CreateBuilder(args);

var services = builder.Services;

services
        .AddEasyCaching(opt =>
        {
                opt.UseInMemory("local");

                opt.UseRedis(config =>
                {
                        config.EnableLogging = true;
                        config.DBConfig.Endpoints.Add(new EasyCaching.Core.Configurations.ServerEndPoint("127.0.0.1", 6379));
                }, "redis");

                opt.UseHybrid(config =>
                {
                        config.TopicName = "a-topic";

                        config.LocalCacheProviderName = "local";
                        config.DistributedCacheProviderName = "redis";
                }, "hybrid")
                .WithRedisBus(bus =>
                {
                        bus.Endpoints.Add(new EasyCaching.Core.Configurations.ServerEndPoint("127.0.0.1", 6379));
                });
        });

var app = builder.Build();

var env = Environment.GetEnvironmentVariable("ASPNET_PORT");
app.Urls.Add("http://127.0.0.1:" + int.Parse(env!));

app.MapGet("/hybrid", async (IHybridProviderFactory provider) =>
        await provider.GetHybridCachingProvider("hybrid").GetAsync<string>("test"));

app.MapGet("/hybrid/{value}", async (string value, IHybridProviderFactory provider) =>
        await provider.GetHybridCachingProvider("hybrid").SetAsync("test", value, TimeSpan.FromMinutes(5)));

app.MapGet("/evict", async (IHybridCachingProvider provider) =>
        await provider.RemoveAsync("test"));

app.Run();
```

1. run it twice with ASPNET_PORT set to different ports, I'm using a local instance of redis.
2. hit /hybrid/{value} on one, then just /hybrid on the second

**Expected behavior:**

 Redis and in memory should update in both apps when running together

**Actual behavior:**

 It appears only the in memory cache gets updated, and the change is never pushed to Redis.

## Specifications

- Provider    : InMemory latest, Hybrid latest, Redis latest, Bus.Redis latest
- Interceptor : .net 6
- Serializer  : not use
- System      : Ubuntu 18.04

## Extra details:

- When submitting using the IRedisCachingProvider, it's able to connect and save/pull the key correctly, using the same configuration (so it's not that it can't find the redis instance)
- If I manually add a key to redis (using hybrid client), then query for it I get back that it was found, but it returns null for its value, even though I'm able to pull it back using other redis clients (including directly with IRedisCachingProvider)
- When using the Hybrid client and the above code, adding/removing a key takes ~5-10 seconds, although retrieving is near instant (even when it logs back a redis cache miss)

and sorry, I know this is vague, I just don't know how to search for more information for what's going wrong, I don't see any logging that would state what's happening

**Comment by catcherwong** [comment]
@Dispersia  Thanks for your interest in this project.

> 1. run it twice with ASPNET_PORT set to different ports, I'm using a local instance of redis.
> 2. hit /hybrid/{value} on one, then just /hybrid on the second

Assuming ports are 8000 and 9000, when hitting `/hybrid/{value}` on 8000, 

At first, redis and memory(8000) should update, then memory(9000) should update as well.

Take a look on this sample for hybrid 

https://github.com/catcherwong-archive/EasyCachingHybridDemo

> It appears only the in memory cache gets updated, and the change is never pushed to Redis

When calling **SetAsync** of **IHybridCachingProvider**, it will both set the value to memory and redis.

**Comment by catcherwong** [comment]
> When submitting using the IRedisCachingProvider, it's able to connect and save/pull the key correctly, using the same configuration (so it's not that it can't find the redis instance)

Hybird caching provider only support multiple `IEasyCachingProvider`,  `IRedisCachingProvider` is mainly for some operation that `IEasyCachingProvider` can not handle, such as redis list, redis set , etc.

**Comment by Dispersia** [comment]
Thanks for the replies, so after running that example (just upgrading it to .net 6), I get the same error as my original post, it does not actually grab the correct values:
![values](https://user-images.githubusercontent.com/7254623/159412889-ba803c83-e10f-4e00-a1af-6a856ae72dbb.png)

however, I now actually get an error when running that example (though I don't know why it doesn't happen on my test app)
```
fail: EasyCaching.HybridCache.HybridCachingProvider[0]
      set cache key [cacheKey] error
      System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
         at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
         at EasyCaching.Core.Serialization.DefaultBinaryFormatterSerializer.Serialize[T](T value)
         at EasyCaching.Redis.DefaultRedisCachingProvider.BaseSet[T](String cacheKey, T cacheValue, TimeSpan expiration)
         at EasyCaching.Core.EasyCachingAbstractProvider.Set[T](String cacheKey, T cacheValue, TimeSpan expiration)
         at EasyCaching.HybridCache.HybridCachingProvider.Set[T](String cacheKey, T cacheValue, TimeSpan expiration)
```

in reading up on it, it sounds like it's a vulnerability in BinaryFormatter that can make a service be DoS'd, and I assume it's the reason I am unable to upgrade it. I attempted to change it to use MessagePack, but unfortunately still get the above error

**Comment by catcherwong** [comment]
After .net5, using **BinaryFormatter**  will throw **System.NotSupportedException**.

>  but unfortunately still get the above error (is it not changing the serializer?)

It seems that your configuration is not right. You should specify the SerializerName. Take a look on #334

**Comment by Dispersia** [comment]
Updated to using the SerializerName and that seems to at least partially work now, there is no error however I'm getting inconsistant results:
a link to the commit: https://github.com/Dispersia/EasyCachingHybridDemo/commit/a341bd8b4f20b12bfff8a307416f304c59af135f

![Screenshot 2022-03-22 085645](https://user-images.githubusercontent.com/7254623/159523400-c699a737-9e34-47e1-bd08-7000545c90fe.png)

if i rerun the app, it correctly pulls from redis the first time, however app1 only updates itself, and app2 only updates itself and neither get the update until i again restart it, it seems after it gets set to a value it no longer attempts to stay up to date

**Comment by Dispersia** [comment]
Github is having issues this morning, I don't know if the above is updating for you but it's not for me, so the edit is this (i'll delete this message when it's done)

<s>Updated to using the SerializerName and that seems to at least partially work now, there is no error however I'm getting inconsistant results:
a link to the commit: https://github.com/Dispersia/EasyCachingHybridDemo/commit/a341bd8b4f20b12bfff8a307416f304c59af135f

if i rerun the app, it correctly pulls from redis the first time (saying app2 | app2 for the first messages), however app1 only updates itself, and app2 only updates itself and neither get the update until i again restart it, it seems after it gets set to a value it no longer attempts to stay up to date</s>

I needed to set the serializer on the bus as well, and now it seems to be working correctly. Should the default serializer be changed off of BinaryFormatter? This would be a breaking change, but it would prevent anyone upgrading from failing at runtime

**Comment by catcherwong** [comment]
> Should the default serializer be changed off of BinaryFormatter?

No, NET Core 3.1 is still an LTS, BinaryFormatter will not be considered to be removed until .NET Core it exceeds the time of LTS.

> This would be a breaking change, but it would prevent anyone upgrading from failing at runtime

This is a well-known breaking change due to runtime/SDK upgrades.
