### ISSUE TITLE
can we control not to cache default values such "[]" and "{}" at framework level

### ISSUE THREAD

**Issue by mohanavamsiTakeda** [dotnetcore/EasyCaching#349]
## Task<CacheValue<T>> GetAsync<T>(string cacheKey, Func<Task<T>> dataRetriever, TimeSpan expiration) is caching default values . if we dont need them to happen, can we control

[Description of the bug or feature]

### Steps to Reproduce

1.  GetAsync<T>(cacheKey, ()=>{ return new object(); }, expiration)
2. 

### Related code

```
insert short code snippets here
```

**Expected behavior:** default values need not to be cached

**Actual behavior:** default values are being cached

## Specifications

- Provider    : Redis (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : CentOS 7.2

**Comment by catcherwong** [comment]
@mohanavamsiTakeda  Thanks for your interest in this project.

No. An empty value also has special significance in caching in some business scenarios, EasyCaching will not control this one.
