### ISSUE TITLE
Some questions when using EasyCachingEvictAttribute to remove cached item.

### ISSUE THREAD

**Issue by jianxuanbing** [dotnetcore/EasyCaching#35]
```
public interface IAspectCoreService : EasyCaching.Core.Internal.IEasyCaching
    {
        [EasyCachingAble(Expiration = 10)]
        string GetCurrentUtcTime();

        [EasyCachingPut(CacheKeyPrefix = "AspectCore")]
        string PutSomething(string str);

        [EasyCachingEvict(IsBefore = true)]
        void DeleteSomething(int id);

        [EasyCachingAble(Expiration = 10)]
        Task<string> GetUtcTimeAsync();
    }
```
我看你这边是获取方法名的，那么 我在DeleteSomething这个方法里面要触发 移除 PutSomething 这个缓存的信息，那么这里会有个问题，是无法移除的

**Comment by catcherwong** [comment]
@jianxuanbing Thanks for your interest in the project.

EasyCachingEvictAttribute is based on method's name by default! And you can replace it via **CacheKeyPrefix** that you can specify the prefix of cache key.

For example,  

```cs
[EasyCachingEvict(IsBefore = true, CacheKeyPrefix = "MyPrefix")]
void DeleteSomething(int id);
```

In this time, the cache key will be `MyPrefix:id`, and it will remove by this cache key.

For your description, do you want to remove the cached item via a new way?

**Comment by jianxuanbing** [comment]
3Q. This is OK.But I find `StackExchange.Redis`  Async Action is Blocking.I test WebApi has async action is no response.

**Comment by catcherwong** [comment]
Do you mean there are some bugs when using `StackExchange.Redis` ?
