### ISSUE TITLE
DefaultRedisCachingProvider.SearchKeys() method always throw exception if the optional count parameter is not set.

### ISSUE THREAD

**Issue by mjebrahimi** [dotnetcore/EasyCaching#350]
`count.HasValue?250: count.Value` must change to `count ?? 250`

https://github.com/dotnetcore/EasyCaching/blob/aa7185100b2c3f515f51d5fa132e8a55c6be8ad9/src/EasyCaching.Redis/DefaultRedisCachingProvider.Keys.cs#L138

**Comment by mjebrahimi** [comment]
Also, the SearchKeys method is not Async and only search keys on the first server, not all of the servers!

**Comment by catcherwong** [comment]
@mjebrahimi  Thanks for your interest in this project.

There are some bugs here. 

Could you please submit a PR to fix this issue?
