### ISSUE TITLE
Support for Flush method in IHybridCachingProvider

### ISSUE THREAD

**Issue by mjebrahimi** [dotnetcore/EasyCaching#351]
`IEasyCachingProvider` has the `Flush` method, we should add the Flush method to `IRedisCachingProvider` (already SE.Redis and CSRedis implementation has Flush method), and add a property (eg. `IsFlush`) is `EasyCachingMessage` class to indicate flush has occurred.
So we can implement the Flush method in `IHybridCachingProvider` that calls flush of local and distributed providers, and then publish the flush message to other instances.

**Comment by catcherwong** [comment]
@mjebrahimi  Thanks for your interest in this project.

`Flush` is a very dangerous operation for both in memory and distributed cache. 

It was decided not to join this method at the beginning of design.
