### ISSUE TITLE
NotSupportedException being thrown when using Bus or Compressors with .NET 5/6

### ISSUE THREAD

**Issue by brutaldev** [dotnetcore/EasyCaching#352]
## Description

Cross process synching does not work in .NET 5/6. If you enable logging you will see `NotSupportedException` being thrown but swallowed so cache changes do not sync. This is due to the fact the default serilaizer is the `DefaultBinaryFormatterSerializer` and [binary formatting is now disabled in .NET 5/6 projects by default](https://docs.telerik.com/reporting/knowledge-base/binaryformatter-exception-after-upgrade-to-net5)

![image](https://user-images.githubusercontent.com/1929531/161749384-7807c40e-6a1c-4f49-a1e8-622cb82f4d99.png)

### Steps to Reproduce

Use any `.WithCompressor` or `.WithRedisBus` extensions on your Redis or Hybrid cache configuration.

### Related code

```
services.TryAddSingleton<IEasyCachingSerializer, DefaultBinaryFormatterSerializer>();
```

**Expected behavior:** [What you expected to happen]
Default serialization should work and processes should get a bus message to update/clear cache keys.

**Actual behavior:** [What actually happened]
Caches are not synchronized. Cannot easily unit test because the local cache is cleared fine but as soon as another process has to deal with the binary data from the bus then it doesn't work.

### Temp Solution
Applications targeting .NET 5.0 or .NET 6.0 should add `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>`  to their `.csproj` file.

## Specifications

- Provider    : All (version 1.5.1)
- Serializer  : Binary (or none which falls back to binary)
- System      : All

**Comment by catcherwong** [comment]
@brutaldev Thanks for your interest in this project.

After .net5, using **BinaryFormatter** will throw **System.NotSupportedException**.

Although this can be handled with a temporary solution, we do not recommend this action very much. We prefer to switch to other serialization methods, like msgpack, json.

**Comment by brutaldev** [comment]
@catcherwong I've uploaded a sample app to demonstrate this: https://brutaldev.com/download/EasyCachingBroken_352.zip

It contains two projects, both use the exact same caching configuration with MessagePack serialization and GZip compression. The `Microsoft.NET.Sdk.Worker` project works perfectly. But the `Microsoft.NET.Sdk.Web`  app does not work despite having identical caching setup.

In `EasyCachingBroken_352_Broken.csproj` you can enable `<EnableUnsafeBinaryFormatterSerialization>` to see it actually work and sync when you run both apps together. If you disable EasyCaching logging then there is no indication that it does not work and the two applications simply do not sync the cache making this a completely invisible problem that uses will not easily notice.

**Comment by catcherwong** [comment]
> Even when using a different serializer this still happens (we use MessagePack with GZip). Take this stack trace for example when the compressor breaks because internally it uses the binary formatter:

When using `Hybird`, do not forget to set `SerializerName ` as well.

https://easycaching.readthedocs.io/en/latest/Hybrid/

```cs
// use redis bus
.WithRedisBus(busConf => 
{
    busConf.Endpoints.Add(new ServerEndPoint("127.0.0.1", 6380));

    // do not forget to set the SerializerName for the bus here !!
    busConf.SerializerName = "myjson";
});
```

**Comment by catcherwong** [comment]
Take a look on your sample.

```
fail: EasyCaching.HybridCache.HybridCachingProvider[0]
      set cache key [InvalidationTest] error
      System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
         at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
         at EasyCaching.Core.Serialization.DefaultBinaryFormatterSerializer.Serialize[T](T value)
         at EasyCompressor.EasyCachingSerializerDecorator.Serialize[T](T value) in C:\Users\admin\Downloads\EasyCompressor-master\src\EasyCaching.Extensions.EasyCompressor\EasyCachingSerializerDecorator.cs:line 60
         at EasyCaching.Redis.DefaultRedisCachingProvider.BaseSetAsync[T](String cacheKey, T cacheValue, TimeSpan expiration)
         at EasyCaching.Core.EasyCachingAbstractProvider.SetAsync[T](String cacheKey, T cacheValue, TimeSpan expiration)
         at EasyCaching.HybridCache.HybridCachingProvider.SetAsync[T](String cacheKey, T cacheValue, TimeSpan expiration)
```

It seems that **EasyCompressor** can not get the correct `IEasyCachingSerializer`.

**Comment by brutaldev** [comment]
Hi,

I have applied the serializer name in `.WithRedisBus` as suggested but the problem still remains:

```
fail: EasyCaching.HybridCache.HybridCachingProvider[0]
      set cache key [InvalidationTest] error
      System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
         at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
         at EasyCaching.Core.Serialization.DefaultBinaryFormatterSerializer.Serialize[T](T value)
         at EasyCompressor.EasyCachingSerializerDecorator.Serialize[T](T value) in /_/src/EasyCaching.Extensions.EasyCompressor/EasyCachingSerializerDecorator.cs:line 58
         at EasyCaching.Redis.DefaultRedisCachingProvider.BaseSetAsync[T](String cacheKey, T cacheValue, TimeSpan expiration)
         at EasyCaching.Core.EasyCachingAbstractProvider.SetAsync[T](String cacheKey, T cacheValue, TimeSpan expiration)
         at EasyCaching.HybridCache.HybridCachingProvider.SetAsync[T](String cacheKey, T cacheValue, TimeSpan expiration)
```

You can download the sample code with the updates here: https://brutaldev.com/download/EasyCachingBroken_352_v2.zip

So how can the compressor be updated?

**Comment by catcherwong** [comment]
You should check the configuration at first.

**Comment by brutaldev** [comment]
@catcherwong That works!

Applied the fix and everything is working, Didn't realise you can also change it in the config builder because it's usually in the extension method. Appreciate your help.
