### ISSUE TITLE
[Memcached] Returns null instead of throwing an exception when not had a connection

### ISSUE THREAD

**Issue by macalbert** [dotnetcore/EasyCaching#357]
## Description
I guess that this is unexpected behaviour, but if it is not I think that it should need a different approach.

We should be expecting an exception when the provider can not connect to the server.

[Description of the bug or feature]

On version 1.4.1, when we want to get a value when the server is down (for example) we are getting null, the same happens when we want to check if exists some key and always returns false. 
The expected behaviour instead should be to throw an exception indicating that it cannot access the server.

### Steps to Reproduce

1. config.DBConfig.AddServer("127.11.22.33", 22822); // Unexisting IP and PORT.
2. await _provider.GetAsync<string>("demo"") // Should throw exception instead of return null

### Related code

```
    using EasyCaching.Core;
    using FluentAssertions;
    using Microsoft.Extensions.DependencyInjection;
    using System;
    using System.Threading.Tasks;
    using Xunit;

    public class EasyCachingTests
    {
        private readonly IEasyCachingProvider _provider;

        public EasyCachingTests()
        {
            var services = new ServiceCollection();
            services.AddLogging();
            services.AddEasyCaching(option =>
            {
                option.UseMemcached(config =>
                {
                    config.DBConfig.AddServer("127.11.22.33", 22822);
                });
            });

            var serviceProvider = services.BuildServiceProvider();

            _provider = serviceProvider.GetService<IEasyCachingProvider>();
        }

        [Fact]
        public async void Should_GetThrowsAnException_When_CanNotConnectToHost()
        {
            // Arrange          
            var key = "demo";

            //Act
            Func<Task> action = async () => await _provider.GetAsync<string>(key);

            // Assert            
            await action.Should().ThrowAsync<Exception>();
        }

        [Fact]
        public async void Should_ExistsThrowsAnException_When_CanNotConnectToHost()
        {
            // Arrange          
            var key = "demo";

            //Act
            Func<Task> action = async () => await _provider.ExistsAsync(key);

            // Assert            
            await action.Should().ThrowAsync<Exception>();
        }
```

**Expected behavior:** Throw an Exception

**Actual behavior:** Returns `null` or `false`

## Specifications

- Provider    : Memcached (version 1.4.1)

**Comment by catcherwong** [comment]
@macalbert Thanks for your interest in this project.

We will take a look ASAP.

**Comment by catcherwong** [comment]
At this time, EasyCaching using some high level APIs of **EnyimMemcachedCore** that will not throw exception.

If we need this feature, throw exception instead of  empty value when we can not connect to the server, we should change to the lower level APIs.

**Comment by macalbert** [comment]
Great! Thank you so much!

\<img src="https://media3.giphy.com/media/Od0QRnzwRBYmDU3eEO/giphy.gif"/\>
