### ISSUE TITLE
when i set a error configuration,i get a confuse exception

### ISSUE THREAD

**Issue by AiSY-Yang** [dotnetcore/EasyCaching#359]
# version
EasyCaching.Redis 1.5.0
EasyCaching.Serialization.SystemTextJson1.5.1

我开始的时候把日志写错了 注意SerializerName的位置
i set a error configuration ,look out the section `SerializerName` ,the location is wrong
```
  "Sync": {
    "MaxRdSecond": 0,
    "EnableLogging": false,
    "dbconfig": {
      "SerializerName": "json",
      "AbortOnConnectFail": false,
      "Password": "",
      "Endpoints": [
        {
          "Host": "localhost",
          "Port": 6379
        }
      ],
      "Database": 2
    }
  }
```
在运行时报错 Sequence contains no matching element
when i inject IEasyCachingProviderFactory and call `cachingProviderFactory.GetRedisProvider("Sync")` i got Sequence contains no matching element

in my startup.cs
```
services.AddEasyCaching(op =>
	{
		op.WithSystemTextJson();
		op.UseRedis(Configuration, "Sync", "Redis:Sync");
	});
```
问题如下
1.是否应该在进行配置绑定的时候检查配置文件是否错误或者无效
2.如果只能在运行时第一次初始化redis的时候再检查错误,能否优化报错说明
Can check for errors during binding configuration
Can you modify the error description

This issue has been changed because only Chinese was used before

**Comment by catcherwong** [comment]
@AiSY-Yang Thanks for your interest in this project.

At present, most of the configuration options have default values, and there is no particularly clear error or invalid judgment condition, do you have a better suggestion for this piece?

Does the optimization error description refer to the exception information? If that's the case, it's okay.

-------

目前配置选项大多都有默认值，且没有特别明确的错误或无效判断条件，对这一块你是否有比较好的建议呢？

优化报错说明指的是异常信息吗？如果是这个的话，是可以的。

**Comment by catcherwong** [comment]
> EasyCachingNotFoundException: Can not find the matched serializer instance, serializer name is xxxx.

When not match, will throw this exception message now.
