### ISSUE TITLE
Error connection when AddEasyCaching load redis info from settings

### ISSUE THREAD

**Issue by huanbd** [dotnetcore/EasyCaching#361]
## Description

Hi, when I initialize AddEasyCaching with loading redis info from settings, redis can't connect to server
But when I set constant value redis connect success
I don't know why

### Related code
Code when loading redis info from settings
   ```
 var host = builder.Configuration["Redis:Host"].ToString();
    var port = int.Parse(builder.Configuration["Redis:Port"]);
    var database = int.Parse(builder.Configuration["Redis:Database"]);

    var endpoint = new EasyCaching.Core.Configurations.ServerEndPoint(host, port);

    builder.Services.AddEasyCaching(options =>
    {
        options.WithJson("json");
        options.UseRedis(config =>
        {
            config.DBConfig.Endpoints.Add(endpoint);
            config.DBConfig.Database = database;
            config.SerializerName = "json";
        }, "default");
    });
```
Code when set constant value

    var host = "localhost";
    var port=6379;
    var database = 0;

    var endpoint = new EasyCaching.Core.Configurations.ServerEndPoint(host, port);

    builder.Services.AddEasyCaching(options =>
    {
        options.WithJson("json");
        options.UseRedis(config =>
        {
            config.DBConfig.Endpoints.Add(endpoint);
            config.DBConfig.Database = database;
            config.SerializerName = "json";
        }, "default");
    });

```
Expected behavior:  Want to load info from settings

## Specifications

EasyCaching.Core (version 1.5.1)
EasyCaching.Redis (version 1.5.1)
NET 6

**Comment by catcherwong** [comment]
@huanbd Thanks for your interest in this project.

Could you please provide more information for this issue?

Such as the exception message and stack trace

**Comment by huanbd** [comment]
Dear @catcherwong, sorry for the inconvenience, today when I run again to get the error stacktrace but I can't see the error, It works fine. It took me a day to try the ways :( . I think It's because of my environment. Sorry for waste your time
