### ISSUE TITLE
Add method Redis SortedSet get range by score

### ISSUE THREAD

**Issue by huanbd** [dotnetcore/EasyCaching#363]
Hi, I see that current has not exists method Sorted Set get range by score, hope update into the next release.

**Comment by catcherwong** [comment]
@huanbd  Thanks for your interest in this project.

If you really need this function now, you can try the following solution.

Using **IEasyCachingProvider.Database** to get the object of redis client, and force the object into the corresponding redis client.

And I will try to add this function to **IRedisCachingProvider** later.
