### ISSUE TITLE
Can not find the matched serializer instance, serializer name is redis1

### ISSUE THREAD

**Issue by ysq5202121** [dotnetcore/EasyCaching#370]
![image](https://user-images.githubusercontent.com/8586973/167100983-8901c2a1-198c-4d61-9f2d-cc9887d44c7e.png)

![image](https://user-images.githubusercontent.com/8586973/167100667-880bc7c1-0da9-4542-9fe3-86858177f69d.png)

**Comment by catcherwong** [comment]
@ysq5202121 Thanks for your interest in this project.

The default serializer's implementation of EasyCaching  is **BinaryFormatter**, but after version .net 5 , it will no longer support, and we will remove it in next two release.

So we decided to upgrade for users to have a transitional period, let users adapt to the provider should specify the **SerializerName**.

Take a look on the following example.

```cs
option.UseRedis(config =>
{
    config.DBConfig.Endpoints.Add(new ServerEndPoint("127.0.0.1", 6379));
    
    // specify the SerializerName 
    config.SerializerName = "mymsgpack";
}, "redis1")

// using MessagePack to serialize caching data.
.WithMessagePack("mymsgpack");
```

**Comment by joer33304** [comment]
The online docs are outdated, It does not mention this at :https://easycaching.readthedocs.io/

**Comment by alam248** [comment]
I am facing this same issue. I upgraded solution from .Net Core 3.1 to .Net 6. 



<img width="551" alt="image" src="https://user-images.githubusercontent.com/4697550/209657627-70fe6fa4-4e6c-40e5-89ae-2a48bf695f05.png">

Following is my configuration:

```
var providerName = "EasyCacheProvider";
                services.AddEFSecondLevelCache(options =>
                {
                    options.UseEasyCachingCoreProvider(providerName, false).DisableLogging(false);
                });

                services.AddEasyCaching(options =>
                {
                    if (!appConfig.Caching.UseRedis)
                    {
                        options.UseInMemory(providerName);
                    }
                    else
                    {
                        options.UseRedis(config =>
                        {
                            config.DBConfig.Endpoints.Add(new ServerEndPoint(appConfig.Caching.RedisHost, appConfig.Caching.RedisPort));
                            config.DBConfig.Database = appConfig.Caching.Database;
                            config.SerializerName = providerName;
                        }, providerName).WithJson()
                        ;
                    }
                });
```
Following is my nuget situation: 
<img width="577" alt="image" src="https://user-images.githubusercontent.com/4697550/209658148-46432d23-8679-4b5b-abc0-d8a0e5092f62.png">

Would be be great help if you guys can suggest me what should I do. I tried to change formatter name, I tried different versions of nuget packages. But keep getting same error.
