### ISSUE TITLE
关于 IEasyCachingProvider 默认实现问题 （IEasyCachingProvider default implementation）

### ISSUE THREAD

**Issue by sundakai** [dotnetcore/EasyCaching#371]
我运行示例代码时（When I run the sample code），
<img width="385" alt="企业微信截图_16538985043990" src="https://user-images.githubusercontent.com/21995250/170948517-a452e365-11c8-47e1-b42d-8095aeb23174.png">
这里的 IEasyCachingProvider  实现为 Memcached 即最后一个注入的，这是特意的，之后版本也会保持这样么（The IEasyCachingProvider implementation here is Memcached, which is the last one injected，This is intentional, will the future version also keep this way）
有没有 方式可以显式设置实现（Is there a way to explicitly set this up）
注入逻辑
```
 services.AddEasyCaching(option =>
            {
                //use memory cache
                option.UseInMemory("default");

                //use memory cache
                option.UseInMemory("cus");

                //use redis cache
                option.UseRedis(config =>
                {
                    config.DBConfig.Endpoints.Add(new ServerEndPoint("127.0.0.1", 6379));
                    config.DBConfig.SyncTimeout = 10000;
                    config.DBConfig.AsyncTimeout = 10000;
                    config.SerializerName = "mymsgpack";
                }, "redis1")
                .WithMessagePack("mymsgpack")//with messagepack serialization
                ;

                //use redis cache
                option.UseRedis(config =>
                {
                    config.DBConfig.Endpoints.Add(new ServerEndPoint("127.0.0.1", 6380));
                }, "redis2");

                //use sqlite cache
                option.UseSQLite(config =>
                {
                    config.DBConfig = new SQLiteDBOptions { FileName = "my.db" };
                });

                //use memcached cached
                option.UseMemcached(config =>
                {
                    config.DBConfig.AddServer("127.0.0.1", 11211);
                });

                option.UseMemcached(Configuration);
            });
```

**Comment by catcherwong** [comment]
@sundakai  Thanks for your interest in this project.

This example show how to use different provider in EasyCaching, not all of them you will use, but you need.

BTW, when you use more than one provider, **IEasyCachingProviderFactory**  is recommended.

---------

这个示例是演示了在 EasyCaching 中，不同类型的 provider 的使用，你只需要选择你需要的 provider 即可。

另外，如果你需要使用到多个provider的时候，推荐使用 **IEasyCachingProviderFactory**

**Comment by sundakai** [comment]
> @sundakai Thanks for your interest in this project.
> 
> This example show how to use different provider in EasyCaching, not all of them you will use, but you need.
> 
> BTW, when you use more than one provider, **IEasyCachingProviderFactory** is recommended.
> 
> 这个示例是演示了在 EasyCaching 中，不同类型的 provider 的使用，你只需要选择你需要的 provider 即可。
> 
> 另外，如果你需要使用到多个provider的时候，推荐使用 **IEasyCachingProviderFactory**

是不是就是说 IEasyCachingProvider 的实现恰好是最后添加进容器的实现这个不是特殊设计的，只是现在微软的依赖注入逻辑就是这样。之后如果微软修改不能保证这个 逻辑。像示例中的这种多个provider 的，就应该从一开始就使用 IEasyCachingProviderFactory 去显示的指明要用哪个 provider 的实现

**Comment by catcherwong** [comment]
Yes, you are right.

**Comment by sundakai** [comment]
> Yes, you are right.
Thanks a lot
