### ISSUE TITLE
Force every publish to execute ExchangeDeclare produce lacks of performance

### ISSUE THREAD

**Issue by luizcarlosfaria** [dotnetcore/EasyCaching#375]
When the code calls ExchangeDeclare, client send a command to server to ensure that exchange exists with these parameters.

As a library do you don't know if the exchange must be a Alternative Exchange or anything else.

https://github.com/dotnetcore/EasyCaching/blob/bc4a0177cf2cc9c220afbee6aafc6065770af239/bus/EasyCaching.Bus.RabbitMQ/DefaultRabbitMQBus.cs#L93

**Comment by catcherwong** [comment]
@luizcarlosfaria Thanks for your interest in this project.

Sorry for this mistake.

We will improve this in the next version, or can you submit a PR to help us improve this
