### ISSUE TITLE
Publish without basicproperties

### ISSUE THREAD

**Issue by luizcarlosfaria** [dotnetcore/EasyCaching#376]
BasicProperties is a fundamental mechanism to define behaviors of the message, like if the message is transient or durable.

https://github.com/dotnetcore/EasyCaching/blob/bc4a0177cf2cc9c220afbee6aafc6065770af239/bus/EasyCaching.Bus.RabbitMQ/DefaultRabbitMQBus.cs#L94

**Comment by catcherwong** [comment]
@luizcarlosfaria Thanks for your interest in this project.

Should we must add basicproperties ?

**Comment by luizcarlosfaria** [comment]
> Should we must add basicproperties ?

Is you think about resilience, if you decide if the message stay on memory or will persisted on disc, it's a concern.
