### ISSUE TITLE
Exception handling if redis is not available

### ISSUE THREAD

**Issue by mahdipc** [dotnetcore/EasyCaching#380]
## Description
I'm using redis(EasyCachingProvider) to cache and use some data. In case of redis failure (for any reason), I want my program to be able to continue and ignore the set and return null for get.
I appreciate any tips or help
## Sample Code
```
var model= (await _cacheManager.GetAsync<IList<Rmodel>>(key)).Value;//model->null
        if (model== null)
        {
            model= await _dbContext.GetData();
            await _cacheManager.SetAsync(key, model, TimeSpan.FromHours(1)); //ignore
        }
        return model;

```

**Comment by catcherwong** [comment]
@mahdipc Thanks for your interest in this project.

After the application is started, the redis failure will not affect the application.

If redis has failed before the application is started, the problem of redis failure should be solved first
