### ISSUE TITLE
期望对接Freeredis

### ISSUE THREAD

**Issue by bebestmaple** [dotnetcore/EasyCaching#385]

**Comment by Robinloveyou** [comment]
+1

**Comment by catcherwong** [comment]
@bebestmaple  @Robinloveyou   Thanks for your interest in this project.

This issue is planned.

**Comment by bebestmaple** [comment]
Is there any progress now?

**Comment by catcherwong** [comment]
> Is there any progress now?

We work this on https://github.com/easycaching-contrib/ec-freeredis

If you are interested in this project, PRs are welcome!!

**Comment by bebestmaple** [comment]
Thanks.but why in another project,i feel very strange.
No other meaning, simply curious. Is it because of compatibility issues?

**Comment by xubinhua888** [comment]
Neget did not find the easyCaching.FreeRedis
