### ISSUE TITLE
Redis Eval Command and  GetAll SetAll  problem

### ISSUE THREAD

**Issue by sundakai** [dotnetcore/EasyCaching#386]
consult

1.Why is the Redis Eval Command Keys parameter an array but EasyCaching has only one key?
I need to pass an array when I'm working on multiple keys at once
---------------------------------------------------------------------------------------------
为什么 Redis Eval command  keys 参数 是个数组 但是EasyCaching 只有一个 key？
我同时操作多个key 时需要传递数组

2.It is hoped that the operation of Redis GetAll SetAll can be encapsulated with MGet MSet, so that under the condition of high concurrency, the Cpu consumption of client programs and Redis server brought by network IO can be reduced and the performance can be optimized
------------------------------------------------------------------------------------------
.希望 redis GetAll SetAll 的操作可以用 MGet MSet 封装，这样在高并发下 可以减少 网络IO 带来的 客户端程序 和 redis服务端 的Cpu 占用，优化性能

**Comment by catcherwong** [comment]
@sundakai Thanks for your interest in this project.

> 1.Why is the Redis Eval Command Keys parameter an array but EasyCaching has only one key?

EasyCaching support multiple redis clients, but some of which do not support multiple keys, temporarily shrink the function of this piece.

> 2. It is hoped that the operation of Redis GetAll SetAll can be encapsulated with MGet MSet, so that under the condition of high concurrency, the Cpu consumption of client programs and Redis server brought by network IO can be reduced and the performance can be optimized

GetAll and SetAll are based on string, not hash, and the key of Get/Set  operation is also common, so this will not be implemented with MGet and MSet.

In addition, when redis is deployed in the cluster, the key will fall into different slots.

**Comment by sundakai** [comment]
> GetAll and SetAll are based on string, not hash, and the key of Get/Set operation is also common, so this will not be implemented with MGet and MSet.  

 [MGet](https://redis.io/commands/mget/) and [MSet](https://redis.io/commands/mset/)  is operate string
HMGet and HMSet is operate Hash,also As of Redis version 4.0.0,  HMSet is regarded as deprecated.It can be replaced by [HSET](https://redis.io/commands/hset) with multiple field-value pairs when migrating or writing new code.
@catcherwong

**Comment by catcherwong** [comment]
What about expiration for different field in a hash?

**Comment by sundakai** [comment]
> 
You misunderstand me , MGet MSet not operate Hash
[MGet](https://redis.io/commands/mget/) and [MSet](https://redis.io/commands/mset/) is operate string
so Each key has own expiration date

**Comment by catcherwong** [comment]
Sorry to mislead you.

First of all, command [mset](https://redis.io/commands/mset/)  seems not support expiration for each key. If using this command, we should call command [expire](https://redis.io/commands/expire/) as well. network IO can not be reduced for this one.

BTW, both of those two commands will meet **CROSSSLOT Keys in request don’t hash to the same slot** issue in cluster mode. Althought we can hashtag to avoid this issue, but it breaks the naming of cache keys.Maybe it's not a good choose.

**Comment by sundakai** [comment]
> 

Thanks a lot, You are right. @catcherwong
