### ISSUE TITLE
Set data to redis by IRedisCachingProvider，IHybridCachingProvider can not get the data

### ISSUE THREAD

**Issue by roy-ming** [dotnetcore/EasyCaching#391]
## Description

When set data to redis by IRedisCachingProvider，IHybridCachingProvider can not get the data, but when set data by IEasyCachingProvider，IHybridCachingProvider can get the data, is this normal?

### Related code

```
private readonly IRedisCachingProvider _redisCachingProvider;
private readonly IEasyCachingProvider  _easyCachingProvider;
private readonly IHybridCachingProvider _hybridProvider;
```

**Expected behavior:** IRedisCachingProvider set data, and IHybridCachingProvider can get

**Actual behavior:**  IRedisCachingProvider set data, but IHybridCachingProvider can not get

## Specifications

- Provider    : Hybrid(version 1.6.0)

**Comment by catcherwong** [comment]
@roy-ming Thanks for your interest in this project.

> is this normal?

Yes! 

**IHybridCachingProvider** should work with **IEasyCachingProvider**.

**IEasyCachingProvider** is an abstraction provider, which contains general cache operations.

**IRedisCachingProvider** is a special provider for REDIS only, that contains some special methods.

**Comment by roy-ming** [comment]
@catcherwong Okay, thanks.
