### ISSUE TITLE
EasyCaching.Serialization.SystemTextJson 1.6.1 里的EasyCachingJsonSerializerOptions 属性都是只读的，无法设置值

### ISSUE THREAD

**Issue by DeliciousExtra** [dotnetcore/EasyCaching#396]
## Description

EasyCaching.Serialization.SystemTextJson 1.6.1 里的EasyCachingJsonSerializerOptions 属性都是只读的，无法设置值

### Steps to Reproduce

1.  option.WithSystemTextJson((EasyCachingJsonSerializerOptions opt) => { },"Json");
2. the EasyCachingJsonSerializerOptions all properties are readonly，can`t set value;

**Comment by catcherwong** [comment]
@DeliciousExtra Thanks for your interest in this project.

The properties of **EasyCachingJsonSerializerOptions** was designed to readonly.

You should use `WithSystemTextJson(this EasyCachingOptions options, Action<JsonSerializerOptions> jsonSerializerSettingsConfigure, string name)` to replace.

**Comment by DeliciousExtra** [comment]
I didn`t find the usage in the document, thx  for your  reply,it`s very helpful
