### ISSUE TITLE
How we can get all cache keys for example in InMemory?

### ISSUE THREAD

**Issue by meysamhadeli** [dotnetcore/EasyCaching#397]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1. 
2. 

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Provider    : InMemory (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : CentOS 7.2

**Comment by catcherwong** [comment]
@meysamhadeli  Thanks for your interest in this project.

We don't support get all cache keys for Memory provider.

Why did you need this one?

**Comment by meysamhadeli** [comment]
> @meysamhadeli Thanks for your interest in this project.
> 
> We don't support get all cache keys for Memory provider.
> 
> Why did you need this one?

Thanks for response.
I will check all active key in my system.
