### ISSUE TITLE
Do you support reading IP and port from appsettings.config file?

### ISSUE THREAD

**Issue by jiangjun0817** [dotnetcore/EasyCaching#41]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1. 
2. 

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Provider    : InMemory (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : CentOS 7.2

**Comment by catcherwong** [comment]
@jiangjun0817 Thanks for your interest in this project.

Not Support yet! I will make some changes for this ASAP. Or you can submit a PR to change this.

**Comment by jiangjun0817** [comment]
@catcherwong Thank you for your answer.
