### ISSUE TITLE
Cache SizeLimit(int) range pretty small

### ISSUE THREAD

**Issue by orangeagain** [dotnetcore/EasyCaching#425]
## Description
I need store all ipv4, so it need uint.MaxValue=4294967295, but EasyCaching limit it in int.MaxValue=2147483647
Don't worry about memory usage, store all ipv4 only need: 1byte*4*4294967295=1.6GB memory 
Question
1.Is possiable change size limit to long?
2.If the cache size is not limited, is SizeLimit set to 0?

### Steps to Reproduce
```
config.DBConfig = new InMemoryCachingOptions
{
    SizeLimit = int.MaxValue// <= here
};
```

**Comment by catcherwong** [comment]
> 1.Is possiable change size limit to long?

Yes.

> 2.If the cache size is not limited, is SizeLimit set to 0?

Default is not limited!
