### ISSUE TITLE
New serializer: MemoryPack

### ISSUE THREAD

**Issue by jasenf** [dotnetcore/EasyCaching#433]
Hi there,

This serializer is getting a lot of recent attention.   

https://neuecc.medium.com/how-to-make-the-fastest-net-serializer-with-net-7-c-11-case-of-memorypack-ad28c0366516

Before I decide to to tackle a customer serializer for EasyCaching, is anyone else investigating this?

**Comment by catcherwong** [comment]
@jasenf   Thanks for your interest in this project.

Welcome to submit a PR 😄

**Comment by jasenf** [comment]
I was asking if anyone else had worked on it before I take on the project, but yes.

**Comment by amiru3f** [comment]
@jasenf I can help you with this, I'm also interested

**Comment by amiru3f** [comment]
Hi there,
Dear friends, @jasenf  @catcherwong
Please review https://github.com/dotnetcore/EasyCaching/pull/438

**Comment by amiru3f** [comment]
This issue can be closed due to this pull request 
https://github.com/dotnetcore/EasyCaching/pull/438

**Comment by catcherwong** [comment]
Release v1.8.0 for this issue
