### ISSUE TITLE
Can't change serializer or compress files in EasyCaching.Disk

### ISSUE THREAD

**Issue by shlomiw** [dotnetcore/EasyCaching#437]
## Description

The disk cache files are too big, I tried to change serializer and compress using EasyCompressor, but they don't change.

### Steps to Reproduce

1. Use EasyCaching.Disk sink.
2. Try to change serializer - i.e. MessagePack.
3. Add EasyCompressor.
4. Set cache
5. View local files

### Related code

```
      services.AddLZ4Compressor();
      services.AddEasyCaching(options =>
          {
                  options.UseDisk(cfg =>
                  {
                      cfg.DBConfig = new DiskDbOptions { BasePath = Path.Combine(cachePath, "Cache") };
                  }, "disk")                    
                  .WithMessagePack()
                  .WithCompressor();
          });
```
-- or --

```
      services.AddLZ4Compressor("lz4");
      services.AddEasyCaching(options =>
          {
                  options.UseDisk(cfg =>
                  {
                      cfg.DBConfig = new DiskDbOptions { BasePath = Path.Combine(cachePath, "Cache") };
                      cfg.SerializerName = "msgpack";
                  }, "disk")                    
                  .WithMessagePack("msgpack")
                  .WithCompressor("msgpack", "lz4");
          });
```

**Expected behavior:**
The cached files should be compressed.

**Actual behavior:** 
The cached files are the same without adding the compressor.

## Specifications

- Provider    : Disk
- Interceptor : AspectCore 
- Serializer  : MessagePack

Thanks in advance for your help.

**Comment by catcherwong** [comment]
@shlomiw Thanks for your interest in this project.

> I tried to change serializer and compress using EasyCompressor, but they don't change.

The disk cache provider includes a serializer based on MessagePack and does not support replacement, which is not an option.

> The disk cache files are too big.

If you need to compress the data, there are two ways that you can follow:

1. Update EasyCaching and use the compressor in namespace `System.IO.Compression`.
2. Redesign the serializer of disk cache provider to support different serializer and compressor.

**Comment by shlomiw** [comment]
@catcherwong - thanks for your quick reply!

First I want to say that I really like EasyCaching, very helpful lib.

Second, sorry but I didn't understand. 
> Update EasyCaching and use the compressor in namespace System.IO.Compression.

Something I can do right now? or you mean should I compress that data in-memory before using EasyCaching to write it on the disk?

> Redesign the serializer of disk cache provider to support different serializer and compressor.

This is something you'll consider at the future?

Thanks again!

**Comment by catcherwong** [comment]
> Something I can do right now? or you mean should I compress that data in-memory before using EasyCaching to write it on the disk?

 EasyCaching needs to be updated and compressed before writing data. 

> This is something you'll consider at the future?

Yes. 


BTW, if you have time, you can submit PRs to optimize this issue. 😄

**Comment by shlomiw** [comment]
Well now I'm serializing and compressing my objects before saving to disk. The problem is with large data, that instead of using streams to directly save to the disk, I need to use MemoryStream in the middle before SetAsync the compressed byte[] to EasyCaching-Disk. Now I'm getting `MemoryStream IOException Stream was too long` :disappointed:

This should be done by EasyCaching. 

btw - in order to compress the object I need to serialize it first to binary. BinaryFormatter isn't supported anymore (from security reasons), so I found `ObjectSerialization-Net` for the job. Then I'm compressing using normal GZipStream.
I tried MessagePack with LZ4 but it wasn't small enough.
It would be nice to support ObjectSerialization-Net as a serializer.

I'm sorry I don't have time to PR yet. But if it's something that you can do quick, I'd really appreciate. Many thanks.

**Comment by catcherwong** [comment]
> Redesign the serializer of disk cache provider to support different serializer and compressor.

#450  has done this feature.

After new version released, you can use it with **EasyCompressor**.

**Comment by catcherwong** [comment]
release 1.9.0 for this issue.
