### ISSUE TITLE
Please add support for Redis connection strings

### ISSUE THREAD

**Issue by dmarlow** [dotnetcore/EasyCaching#45]
We should be able to supply connection strings that contain all information rather than having to split everything up to pass along separately.

StackExchange.Redis has support for it.

**Comment by catcherwong** [comment]
@dmarlow  Thanks for your interest in this project.

It's a good idea and I will take a look ASAP!

**Comment by catcherwong** [comment]
version 0.2.3 has supported connection string.

Two way you can use the connection string.

1. Set value with Action.

```cs
services.AddDefaultRedisCache(options=>
{
    options.DBConfig.Configuration = "locahost:6379"; 
});
```

2. Read from `appsettings.json`

```cs
services.AddDefaultRedisCache(Configuration);
```

```JSON
"easycaching": {      
        "redis": {
            "dbconfig": {
                "Configuration": "localhost:6379"
            }
        }
}
```
