### ISSUE TITLE
Fix warning xUnit1013

### ISSUE THREAD

**Issue by catcherwong** [dotnetcore/EasyCaching#457]
## Description

When run `dotnet build`, there are some warning message of `xUnit1013`.

![image](https://user-images.githubusercontent.com/8394988/220805821-cc1a4b90-5b3e-415a-a882-5c518df66c4f.png)

### Steps to Reproduce

```
dotnet build EasyCaching.sln
```

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

Fixed the warning of xUnit1013.

**Actual behavior:** [What actually happened]

## Specifications

- Provider    : InMemory (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : CentOS 7.2

**Comment by Memoyu** [comment]
Hello, I can fix it.
