### ISSUE TITLE
Custom cache key generator?

### ISSUE THREAD

**Issue by tietoevry-johan** [dotnetcore/EasyCaching#464]
## Description

Hi, is there any way override the cache key generator?

It's a similar use case to https://github.com/dotnetcore/EasyCaching/issues/445, but I would just like to inject my tenant context in to the cache key generator and add the tenant ID as a prefix.

## Specifications

- Provider    : InMemory (version 1.9.0)

**Comment by catcherwong** [comment]
@tietoevry-johan  Thanks for your interest in this project.

In EasyCaching, only interceptor contains cache key generator `IEasyCachingKeyGenerator`.

When you call method `Set(Async)` or `Get(Async)`, the cache key was defined by yourself.

**Comment by tietoevry-johan** [comment]
@catcherwong alright, thanks for the update and a nice library :)
