### ISSUE TITLE
can add caching provider based on freeredis?

### ISSUE THREAD

**Issue by xubinhua888** [dotnetcore/EasyCaching#465]
can add caching provider based on freeredis?

**Comment by catcherwong** [comment]
@xubinhua888  Thanks for your interest in this project.

We are working on it.

**Comment by Memoyu** [comment]
completed, repo: [ec-freeredis](https://github.com/easycaching-contrib/ec-freeredis)

**Comment by xubinhua888** [comment]
> completed, repo: [ec-freeredis](https://github.com/easycaching-contrib/ec-freeredis)
Can upload to nuget?

**Comment by catcherwong** [comment]
https://www.nuget.org/packages/EasyCaching.FreeRedis/1.9.0

**Comment by xubinhua888** [comment]
> https://www.nuget.org/packages/EasyCaching.FreeRedis/1.9.0

Are there plans for EasyCaching.Bus.FreeRedis?
