### ISSUE TITLE
不是core项目能使用吗，怎么注册？谢谢

### ISSUE THREAD

**Issue by jlcool** [dotnetcore/EasyCaching#47]
## Description

不是core项目能使用吗，怎么注册？谢谢

### Steps to Reproduce

1. 
2. 

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Provider    : InMemory (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : CentOS 7.2

**Comment by catcherwong** [comment]
以InMemory 为例

1. 先安装**EasyCaching.InMemory**
2. 在**ConfigureServices**方法中添加下面的代码
```cs
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        //....
        //添加下面这行代码
        services.AddDefaultInMemoryCache();
    }
}
```
3. 在调用的地方使用**IEasyCachingProvider**进行依赖注入即可。

更多信息可以看文档：[docs](http://easycaching.readthedocs.io/en/latest/)

**Comment by jlcool** [comment]
你好，没有Startup ，没有services 只有Global.asax

**Comment by catcherwong** [comment]
@jlcool 不好意思，不支持非Core的项目！
