### ISSUE TITLE
完善一下 该组件的特性 以供大家使用前进行选择。

### ISSUE THREAD

**Issue by sgf** [dotnetcore/EasyCaching#475]
## Description
完善一下 该组件的特性 以供大家使用前进行选择。

例如很多项目，都会列出项目或者组件，或者类库的特性，比如线程安全。比如平台支持情况。等等。

另外我看了一下案例。感觉Api设计有点问题。不够简单。上手麻烦。似乎必须要用微软ServiceCollection那一套？
 总之用的时候，一堆样板代码，感觉不太友好。

**Comment by catcherwong** [comment]
> 例如很多项目，都会列出项目或者组件，或者类库的特性，比如线程安全。比如平台支持情况。等等。

Readme 和 文档 的介绍应该已经可以满足了。

> 似乎必须要用微软ServiceCollection那一套？

用 ServiceCollection，你可以更容易切换 provider 的实现，当然你也可以直接 new 对应的 provider。

**Comment by sgf** [comment]
> > 例如很多项目，都会列出项目或者组件，或者类库的特性，比如线程安全。比如平台支持情况。等等。
> 
> Readme 和 文档 的介绍应该已经可以满足了。
> 
> > 似乎必须要用微软ServiceCollection那一套？
> 
> 用 ServiceCollection，你可以更容易切换 provider 的实现，当然你也可以直接 new 对应的 provider。

看下  这个你就知道,没有对比.就没有....
这个介绍里面涵盖了用户最关心的几个关键点.

![图片](https://user-images.githubusercontent.com/2557696/234038132-8283b86b-7aaa-4ad1-8e91-d74c5cf6b946.png)
