### ISSUE TITLE
遇到超时问题：Next recovery time: 2023-07-20 10:52:25  (Connect to server timeout)

### ISSUE THREAD

**Issue by mowangzhang** [dotnetcore/EasyCaching#482]
## Description

最近项目使用中遇到超时问题，进程被卡住，找不到问题原因，源码也拿下来调试复现了  是使用CSRedis包
![image](https://github.com/dotnetcore/EasyCaching/assets/46166610/4c7982c0-a0d9-4077-9c34-9ce4cd917f6f)
![image](https://github.com/dotnetcore/EasyCaching/assets/46166610/0b2de165-b642-4af5-8bac-e7270a7a70f1)

**Comment by catcherwong** [comment]
连接超时这种一般是网络问题，可以参考 csredis 的解决方案，调整连接字符串上面的一些参数配置
