### ISSUE TITLE
Count计数错误

### ISSUE THREAD

**Issue by wujunchengman** [dotnetcore/EasyCaching#497]
## Description

写入缓存后

### Steps to Reproduce

写入缓存，更新缓存，缓存自然过期后，Count得到的值错误，在生产环境中是值少了，测试的时候值多了，不是正确的值

### Related code

```csharp
            // 添加10条缓存，等待缓存过期
            var z = _cachingProvider.GetAllKeysByPrefix("DeviceRunningInfo_");
            var c = await _cachingProvider.GetCountAsync("DeviceRunningInfo_");
            // z=0 正确
            // c=10 错误
```

## Specifications

- Provider    : InMemory (version1.9.1)
- Interceptor : AspectCore (version 7.0.0)
- Serializer  : not use
- System      : Win11

**Comment by catcherwong** [comment]
@wujunchengman  Thanks for your interest in this project.

We will take a look ASAP.

cc @Memoyu
