### ISSUE TITLE
JSON serialization

### ISSUE THREAD

**Issue by neilgallagher** [dotnetcore/EasyCaching#50]
## Description

Configurable JSON serializer

### Steps to Reproduce

It would be good if the JSON serializer could be configured with some options. For example I need to ignore self referencing loops for one of my types. This is easily done with an option on the NewtonSoft JsonSerializer but cant use this functionality in the EasyCaching wrapper.

Thanks

### Related code

```
new JsonSerializer { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };
```

## Specifications

- Provider    : MemCached (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : CentOS 7.2

**Comment by catcherwong** [comment]
@neilgallagher Thanks for your interest in this project.

It's a good idea and I will take a look ASAP!

**Comment by catcherwong** [comment]
@neilgallagher  

Version **0.3.1** of **EasyCaching.Serialization.Json**  can help you work it out!

Usage here:

```cs
services.AddDefaultJsonSerializer(options =>
{
    options.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;   
});
```
