### ISSUE TITLE
FAQ: How to use EasyCaching to query and return array of (cached) objects?

### ISSUE THREAD

**Issue by hubert-associates** [dotnetcore/EasyCaching#512]
Hi, I didn't find this in the doc. I'm using EasyCache C# default RedisProvider with the protobuf "proto" serializer. Works fine. Now, I'd like to query my (EasyCaching) redis using a wildcard in the key and get the resulting list/array of hits back. How can I do this using EasyCaching "best practice"? Thanks for a tip!

**Comment by catcherwong** [comment]
@hubert-associates  Thanks for your interest in this project.

1. EasyCaching provides **GetByPrefix(Async)** that can use a wildcard with prefix to query some cacehd objects.
2. Using **.Database** to get the raw redis client instance, then you can do what you want.

**Comment by hubert-associates** [comment]
Thank you for the quick answer. I was unaware of the .Database to provide the instance reference. 
I looked at the src/ tests

For GetByPrefixAsync. Isn't the [prefix](https://github.com/dotnetcore/EasyCaching/blob/266bec0e6825231e4c99196c2395f02364367bd7/src/EasyCaching.Redis/DefaultRedisCachingProvider.cs#L492) just a REDIS [pattern](https://github.com/dotnetcore/EasyCaching/blob/266bec0e6825231e4c99196c2395f02364367bd7/src/EasyCaching.Redis/DefaultRedisCachingProvider.cs#L328C104-L328C104)? It uses [this](https://redis.io/commands/keys/) I believe? But they say there "Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using [SCAN](https://redis.io/commands/scan) or [sets](https://redis.io/topics/data-types#sets)."


To use .Database. Nice. it looks like a cast does the trick [here](https://github.com/dotnetcore/EasyCaching/blob/266bec0e6825231e4c99196c2395f02364367bd7/test/EasyCaching.UnitTests/CachingTests/RedisCachingProviderTest.cs#L132)

**Comment by hubert-associates** [comment]
I looked at the src and see that .Database returns the Redis DB Instance (int). How do I get the DB-handle (refernence) itself from this? What am I missing? Thanks!

[https://github.com/dotnetcore/EasyCaching/blob/266bec0e6825231e4c99196c2395f02364367bd7/test/EasyCaching.UnitTests/CachingTests/RedisCachingProviderTest.cs#L99](https://github.com/dotnetcore/EasyCaching/blob/266bec0e6825231e4c99196c2395f02364367bd7/test/EasyCaching.UnitTests/CachingTests/RedisCachingProviderTest.cs#L99 )

**Comment by catcherwong** [comment]
>For GetByPrefixAsync. Isn't the [prefix](https://github.com/dotnetcore/EasyCaching/blob/266bec0e6825231e4c99196c2395f02364367bd7/src/EasyCaching.Redis/DefaultRedisCachingProvider.cs#L492) just a REDIS [pattern](https://github.com/dotnetcore/EasyCaching/blob/266bec0e6825231e4c99196c2395f02364367bd7/src/EasyCaching.Redis/DefaultRedisCachingProvider.cs#L328C104-L328C104)? It uses [this](https://redis.io/commands/keys/) I believe? But they say there "Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using [SCAN](https://redis.io/commands/scan) or [sets](https://redis.io/topics/data-types#sets)."

The prefix use Redis pattern. It will use scan at first if the redis server supports this command, otherwise, it will use keys.

> To use .Database. Nice. it looks like a cast does the trick [here](https://github.com/dotnetcore/EasyCaching/blob/266bec0e6825231e4c99196c2395f02364367bd7/test/EasyCaching.UnitTests/CachingTests/RedisCachingProviderTest.cs#L132)

YES

**Comment by hubert-associates** [comment]
Perfect! Great solution. Thank you.
