### ISSUE TITLE
下载源码，运行EasyCaching.Demo.Interceptors示例，返回Task的方法缓存处理异常

### ISSUE THREAD

**Issue by fanpan26** [dotnetcore/EasyCaching#52]
## Description

SerializationException: Type 'System.Threading.Tasks.Task`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.
System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(Type type)

AspectInvocationException: Exception has been thrown by the aspect of an invocation. ---> Type 'System.Threading.Tasks.Task`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable..
AspectCore.DynamicProxy.AspectActivator.InvokeTask<TResult>(AspectActivatorContext activatorContext)
```
 if (!string.IsNullOrWhiteSpace(cacheKey) && context.ReturnValue != null)
                        await CacheProvider.SetAsync(cacheKey, context.ReturnValue, TimeSpan.FromSeconds(attribute.Expiration));
```

- Provider    : Redis (version 0.3.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : Win10

**Comment by catcherwong** [comment]
@fanpan26 Thanks for your interest in this project.

There are some problems when using async/await in Interceptors, I will have a look ASAP.

Happy to accept a PR if you fancy having a go yourself!

**Comment by fanpan26** [comment]
@catcherwong thanks,  I tried to solve that problem, but I didn't know how to get the return value type. so i use the `Task<object>` . for example:
` if (!string.IsNullOrWhiteSpace(cacheKey) && context.ReturnValue != null)
                    {
                        object result = null;
                        if (isAsync)
                        {
                            // here , 
                            result = (context.ReturnValue as Task<object>).Result;
                        }
                        else
                        {
                            result = context.ReturnValue;
                        }

                        if (result != null)
                        {
                            await CacheProvider.SetAsync(cacheKey, result, TimeSpan.FromSeconds(attribute.Expiration));
                        }
                    }`

Have I made a clear description?

**Comment by catcherwong** [comment]
You can follow this post  [Async Programming : Intercepting Asynchronous Methods Using Unity Interception](https://msdn.microsoft.com/en-us/magazine/dn574805.aspx?f=255&MSPPError=-2147217396).
And those two test class of AspectCore [AsyncAspectTests](https://github.com/dotnetcore/AspectCore-Framework/blob/master/core/test/AspectCore.Tests/DynamicProxy/AsyncAspectTests.cs) and [AsyncBlockTest](https://github.com/dotnetcore/AspectCore-Framework/blob/master/core/test/AspectCore.Tests/Injector/AsyncBlockTest.cs)

**Comment by catcherwong** [comment]
@fanpan26 

I made some changes in dev branch that can work it out with the default serialization for AspectCore.

https://github.com/dotnetcore/EasyCaching/blob/dev/src/EasyCaching.Interceptor.AspectCore/EasyCachingInterceptor.cs#L59

**Comment by catcherwong** [comment]
@Shinetaku 

Sorry for this bug! 😭 

I made some changes for this in dev branch,  you can have a try. 😄 

You can open a new issue or comment in this issue for what you met.

**Comment by fanpan26** [comment]
@catcherwong cool，thank you

**Comment by catcherwong** [comment]
@fanpan26  Publish version 0.3.1 of EasyCaching.Interceptor.AspectCore.
