### ISSUE TITLE
Redis中AOP切面的拦截器如何实现泛型

### ISSUE THREAD

**Issue by ghd258** [dotnetcore/EasyCaching#53]
AOP切面的拦截器中，第一次把List<T>序列化成字符串，或者数组存到Redis中，然后在有效期内，下一次访问的时候，把存下来的字符串或者数组通过反序列化成相应的泛型list 或者 实体类，，如何在AOP使用泛型

**Comment by catcherwong** [comment]
@ghd258   Thanks for your interest in this project.

The interceptors seem can not use generics straightly, but we can convert the object to the target type.

**Comment by catcherwong** [comment]
I also know that conversion is not smart, but I am not vary familiar with AOP in this scenario. Maybe I need to find some resources to learn.

**Comment by jonechenug** [comment]
这取决你的aop设计了，能想到的就是根据返回类型去构造泛型方法了，然后反射执行。

**Comment by xiaotupansy** [comment]
I can provide you some code:

1.CachingAttribute.cs

```
using System;

namespace YT.Core.DomainModel
{
    [AttributeUsage(AttributeTargets.Method, Inherited = true)]
    public class CachingAttribute : Attribute
    {
        public int Expiration { get; set; } = 100;
    }
}
```

2.CachingInterceptor.cs, note that I use IDistributedCache from Microsoft, you can change to use your own caching provider.

`using AspectCore.DynamicProxy;
using AspectCore.Injector;
using Microsoft.Extensions.Caching.Distributed;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.Serialization.Formatters.Binary;
using System.Text;
using System.Threading.Tasks;
using YT.Core.DomainModel;

namespace YT.Core.Attribute
{
    public class CachingInterceptor : AbstractInterceptor
    {
        [FromContainer]
        public IDistributedCache DistributedCache { get; set; }

        private char _linkChar = ':';

        public async override Task Invoke(AspectContext context, AspectDelegate next)
        {
            var cachingAttribute = GetCachingAttributeInfo(context.ServiceMethod);
            if (cachingAttribute != null)
            {
                await ProceedCaching(context, next, cachingAttribute);
            }
            else
            {
                await context.Invoke(next);
            }
        }

        private CachingAttribute GetCachingAttributeInfo(MethodInfo method)
        {
            return method.GetCustomAttributes(true).FirstOrDefault(x => x.GetType() == typeof(CachingAttribute)) as CachingAttribute;
        }

        private async Task ProceedCaching(AspectContext context, AspectDelegate next, CachingAttribute attribute)
        {
            var cacheKey = GenerateCacheKey(context);

            var cacheValue = await DistributedCache.GetAsync(cacheKey);
            if (cacheValue != null)
            {
                using (var ms = new MemoryStream(cacheValue))
                {
                    var formatter = new BinaryFormatter();
                    var result = formatter.Deserialize(ms);
                    if (context.IsAsync())
                    {
                        dynamic member = context.ServiceMethod.ReturnType.GetMember("Result")[0];
                        dynamic temp = System.Convert.ChangeType(result, member.PropertyType);
                        context.ReturnValue = System.Convert.ChangeType(Task.FromResult(temp), context.ServiceMethod.ReturnType);
                    }
                    else
                    {
                        context.ReturnValue = System.Convert.ChangeType(result, context.ServiceMethod.ReturnType);
                    }
                }
                return;
            }

            await context.Invoke(next);

            if (!string.IsNullOrWhiteSpace(cacheKey))

            {
                using (var ms = new MemoryStream())
                {
                    var formatter = new BinaryFormatter();
                    var serializeValue = context.ReturnValue;
                    if (context.IsAsync())
                    {
                        serializeValue = context.UnwrapAsyncReturnValue();
                    }
                    formatter.Serialize(ms, serializeValue);
                    await DistributedCache.SetAsync(cacheKey, ms.GetBuffer(), new DistributedCacheEntryOptions { AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(attribute.Expiration) });
                }
            }
        }

        private string GenerateCacheKey(AspectContext context)
        {
            var typeName = context.ServiceMethod.DeclaringType.Name;
            var methodName = context.ServiceMethod.Name;
            var methodArguments = this.FormatArgumentsToPartOfCacheKey(context.Parameters);

            return this.GenerateCacheKey(typeName, methodName, methodArguments);
        }

        private string GenerateCacheKey(string typeName, string methodName, IList<string> parameters)
        {
            var builder = new StringBuilder();

            builder.Append(typeName);
            builder.Append(_linkChar);

            builder.Append(methodName);
            builder.Append(_linkChar);

            foreach (var param in parameters)
            {
                builder.Append(param);
                builder.Append(_linkChar);
            }

            return builder.ToString().TrimEnd(_linkChar);
        }

        private IList<string> FormatArgumentsToPartOfCacheKey(object[] methodArguments)
        {
            return methodArguments.Select(this.GetArgumentValue).ToList();
        }

        private string GetArgumentValue(object arg)
        {
            if (arg is int || arg is long || arg is string)
                return arg.ToString();
            if (arg is Guid id)
                return id.ToString();
            if (arg is LambdaExpression express)
                return express.Body.ToString();
            return null;
        }
    }
}`


3.how to use those two in aspect core:

            services.AddDynamicProxy(config =>
            {
                config.Interceptors.AddTyped<CachingInterceptor>(method => 
                method.GetCustomAttributes(true).FirstOrDefault(x => x.GetType() == typeof(CachingAttribute)) as CachingAttribute != null);
            });


4.how to use in method:

`public interface IUserRepository
    {
        [Caching(Expiration = 10)]
        int Test();

        [Caching]
        Task<List<User>> GetAllAsync();

        [Caching]
        List<User> GetAll();
    }`

**Comment by catcherwong** [comment]
@xiaotupansy 

Thanks vary much! I have done something similar with your code in dev branch.

**Comment by xiaotupansy** [comment]
@catcherwong My pleasure.

Notice that in your branch, it's important to change this method in CachingInterceptor 

private string GetArgumentValue(object arg)
    {
        if (arg is int || arg is long || arg is string)
            return arg.ToString();
        if (arg is Guid id)
            return id.ToString();
        if (arg is LambdaExpression express)
            return express.Body.ToString();
        return null;
    }


It generates id for storage in cache provider.
So you need to change it's behavior to fit your solution.
