### ISSUE TITLE
Cancellation token not used for Redis operations

### ISSUE THREAD

**Issue by oskrabanek** [dotnetcore/EasyCaching#535]
Cancellation token is passed to the method but is not used while calling the Redis cache. In case of unavailable Redis instance the provider waits to fail on timeout even when the task is cancelled.

https://github.com/dotnetcore/EasyCaching/blob/c52c8f65591ece1e9821dcf77d28cc307bfa96b9/src/EasyCaching.CSRedis/DefaultCSRedisCachingProvider.Async.cs#L371

**Comment by catcherwong** [comment]
@oskrabanek Thanks for your interest in this project. We will take a look ASAP.

@Memoyu  Could you spare a moment to look at the issue?

**Comment by Memoyu** [comment]
In fact, if we support passing in cancellationToken, we have already passed it in. Maybe csredis does not support passing in.
https://github.com/2881099/csredis/blob/master/src/CSRedisCore/CSRedisClientAsync.cs#L2221
<br/>
However, we seem to be able to refer to the involvement of csredis.IDistributedCache, but it doesn't seem to work.
https://github.com/2881099/csredis/blob/master/src/Microsoft.Extensions.Caching.CSRedis/CSRedisCache.cs#L78
