### ISSUE TITLE
EasyCaching.Interceptor.AspectCore的用法对原有项目有代码侵入

### ISSUE THREAD

**Issue by ww198643** [dotnetcore/EasyCaching#58]
![image](https://user-images.githubusercontent.com/17895675/48926782-e9251380-ef0b-11e8-8db0-5cb9ac8d8d7c.png)
现有实现，是对实现了IEasyCaching接口的类进行拦截，这样做对代码有侵入，一个老的项目能不动代码最好不动，如果通过匹配表达式来拦截就可以做到代码的零侵入，这么做的缺点是灵活性降低了，我推荐做法是优先通过匹配表达式拦截，如果有个别方法有特殊需求再用自定义属性来定义。

**Comment by catcherwong** [comment]
@ww198643  Thanks for your interest in this project.

I will think over your suggestion!

**Comment by catcherwong** [comment]
@ww198643 

`IEasyCaching` is the default implementation of interceptor, I will make it Obsolete! Only the EasyCaching Attribute that mark in interface can effect interceptors.

If you want to customize by yourself, you can use the extension method that remove the default implementation.

Here is a sample.

```cs
Action<IServiceContainer> action = x =>
{
    x.AddType<IDateTimeService, DateTimeService>();
    x.Configure(config =>
    {
        //do what you want to do
        //config.Interceptors.AddTyped<EasyCachingInterceptor>(method => typeof(Core.Internal.IEasyCaching).IsAssignableFrom(method.DeclaringType));
    });
};

return services.ConfigureAspectCoreInterceptor(action, true);
```

**Comment by catcherwong** [comment]
Release version V0.3.2 of `EasyCaching.Interceptor.AspectCore`
