### ISSUE TITLE
Use EasyCaching with ASP.NET MVC 5 (not core)

### ISSUE THREAD

**Issue by advapiIT** [dotnetcore/EasyCaching#59]
Excuse me,
is it possible to run easycaching under a not Asp.Net core application? for example on MVC5?
Thanks

**Comment by catcherwong** [comment]
@advapiIT  Thanks for your interest in this project.

EasyCaching not support ASP.NET MVC 5, but support ASP.NET Core based on .NET Framework.

**Comment by advapiIT** [comment]
Thanks!
You've  done a really good job!
