### ISSUE TITLE
NOAUTH Authentication required

### ISSUE THREAD

**Issue by h0730303779** [dotnetcore/EasyCaching#62]
## Description
运行大概 20~40分钟 突然
Running for about 20~40 minutes, suddenly

StackExchange.Redis.RedisServerException: 'NOAUTH Authentication required.'
![image](https://user-images.githubusercontent.com/16299810/50536156-705d4b00-0b8c-11e9-8dd2-0528870a8649.png)

### Steps to Reproduce

1. 突然中断 缓存清空
2. 平时正常

### Related code

```
_provider.Get<List<Spideing>>("list").IsNull
```

**Expected behavior:** 12

**Actual behavior:** 1212

## Specifications
12

- System      : win10 docker

**Comment by catcherwong** [comment]
@h0730303779  Thanks for your interest in this project.

`NOAUTH Authentication required.` 

This error message shows that your redis servers need to enter a password.

If you met this problem suddenly, you can check whether the configuration of redis was modify!

**Comment by h0730303779** [comment]
感谢的的回复
这种情况 遇到了3次 大概执行40分钟左右  翻阅了很多资料 很多人都认为 是被中途修改密码  docker 重启后有正常
所以我更换了redis服务器 。 现在运行20分钟暂时未遇到这个问题

Thanks for the reply
This situation has encountered 3 times. It takes about 40 minutes to read. I read a lot of information. Many people think that it is changed midway.
So I replaced the redis server.
now ,it has been running for 20 minutes . has not encountered this problem for the time being.

**Comment by catcherwong** [comment]
All right, it sounds good. 😄 

If you have any other problems, please reopen this issue or open a new issue.
