### ISSUE TITLE
Redis 的实现一个CSredis的组件库

### ISSUE THREAD

**Issue by geffzhang** [dotnetcore/EasyCaching#72]
由于StackExchange.Redis 存在一些瑕疵，CSRedis 这个很不错，实现一个CSRedis的Provider

**Comment by catcherwong** [comment]
@geffzhang Thanks for your interest in this project.

Good idea! This is an awesome suggestion, I will add a new provider based on CSRedis.

**Comment by catcherwong** [comment]
Release v0.1.0
