### ISSUE TITLE
Object must implement IConvertible..

### ISSUE THREAD

**Issue by fanpan26** [dotnetcore/EasyCaching#74]
## Description

using  EasyCachingAbleAttribute,it throws an exception: Object must implement IConvertible.
### Related code

```
 [EasyCachingAble(CacheKeyPrefix = "prefix")]
 Task<IEnumerable<CountModuleViewModel>> GetModules();
```

## Specifications

- Provider    : Redis (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : Windows 64

**Comment by fanpan26** [comment]
methods can't return IEnumerable. so I use List instead.
```
Task<List<CountModuleViewModel>> GetModules();
```

**Comment by catcherwong** [comment]
Release a new version 0.3.3
