### ISSUE TITLE
增加绝对过期和过期方案

### ISSUE THREAD

**Issue by hu372197979** [dotnetcore/EasyCaching#78]
## Description

[Description of the bug or feature]

### Steps to Reproduce

1. 缓存数据增加统一包装 增加字段 【过期时间】 用于存储缓存过期时间
2. 命中缓存时 核对【过期时间】如果时间超过则执行更新委托。

### Related code

```
insert short code snippets here
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Specifications

- Provider    : InMemory (version 0.2.0)
- Interceptor : AspectCore (version 0.2.0)
- Serializer  : not use
- System      : CentOS 7.2

**Comment by hu372197979** [comment]
1.存在一个【绝对过期时间】 和 【过期时间】
2.数据中保存【过期时间】
3.缓存提供者保存【绝对过期时间】

**Comment by catcherwong** [comment]
@hu372197979 Thanks for your interest in this project.

I know what you mean. You idea is a good design of caching system.

The `CacheValue` of EasyCaching also contains this field named [ExpiresAt](https://github.com/dotnetcore/EasyCaching/blob/master/src/EasyCaching.Core/Internal/CacheValue.cs#L49).

But this change will be a breaking change of EasyCaching! This is also why I do not do this in #70 , but a simple solution that only use mutex key.

Maybe this feature will be considered in the next version.

**Comment by hu372197979** [comment]
`using EasyCaching.Core.Serialization;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace EasyCaching.Core
{
    public static class EasyCachingExtensions
    {

        /// <summary>
        /// 更新处理方法
        /// </summary>
        private static ConcurrentDictionary<string, Lazy<object>> updateMethods = new ConcurrentDictionary<string, Lazy<object>>();


        /// <summary>
        /// 更新处理任务
        /// </summary>
        private static ConcurrentDictionary<string, Lazy<Task>> updateTasks = new ConcurrentDictionary<string, Lazy<Task>>();


        /// <summary>
        /// 获取缓存到达过期时间执行更新数据（过度版本）
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="provider"></param>
        /// <param name="cacheKey"></param>
        /// <param name="dataRetriever"></param>
        /// <param name="expiration"></param>
        /// <param name="absoluteExpiration"></param>
        /// <returns></returns>
        public static T Get<T>(this IEasyCachingProvider provider, string cacheKey, Func<T> dataRetriever, TimeSpan expiration, TimeSpan absoluteExpiration)
        {
            var result = provider.Get<T>(cacheKey);
            if (!result.IsNull)
            {
                if (result.ExpiresAt <= DateTimeOffset.Now.Add(expiration))
                {
                    var _task = updateTasks.GetOrAdd(cacheKey, new Lazy<Task>(() =>
                    {
                         return new Task(() =>
                         {
                             var item = dataRetriever.Invoke();
                             if (item != null)
                             {
                                 provider.Set(cacheKey, new CacheValue<T>(item, false, expiration), absoluteExpiration);
                             }
                             updateTasks.TryRemove(cacheKey, out Lazy<Task> value);
                         });
                     }));
                    _task.Value.Start();
                }
                return result.Value;
            }
            else
            {
                var _locker = updateMethods.GetOrAdd(cacheKey, new Lazy<object>(() => {
                    return dataRetriever.Invoke();
                }));
                var item = (T)_locker.Value;
                if (item != null)
                {
                    provider.Set(cacheKey, new CacheValue<T>(item, false, expiration), absoluteExpiration);
                }
                updateMethods.TryRemove(cacheKey, out Lazy<object> value);
                return item;
            }
        }
    }
}`

**Comment by catcherwong** [comment]
The cached value is `T`, not `CacheValue<T>`!

All the cached value before this feature will broke if we change this value!

Before doing this, we should consider how to reduce the effect of existing projects.

**Comment by catcherwong** [comment]
@hu372197979 

After a long time of consideration, I  decide not to add this feature!

If you need this feature, I suggest you create a new class that contains the ExpiresAt field.

```cs
public class Demo<T>
{
    public T Obj { get; set; }
    public DateTimeOffset ExpiresAt { get; set; }
}
```

And use `Demo<T>` as `T` where EasyCaching needs.

At last, you need to rewrite the GetAsync method  similar with your commented above!

**Comment by hu372197979** [comment]
@catcherwong 
我知道你的意思，希望还是完善到框架中方便使用

using EasyCaching.Core.Serialization;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace EasyCaching.Core
{
    public static class EasyCachingExtensions
    {

        /// <summary>
        /// 更新处理方法
        /// </summary>
        private static ConcurrentDictionary<string, Lazy<object>> updateMethods = new ConcurrentDictionary<string, Lazy<object>>();


        /// <summary>
        /// 更新处理任务
        /// </summary>
        private static ConcurrentDictionary<string, Task> updateTasks = new ConcurrentDictionary<string, Task>();


        /// <summary>
        /// 获取缓存到达过期时间执行更新数据(支持空数据缓存)
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="provider"></param>
        /// <param name="cacheKey"></param>
        /// <param name="dataRetriever"></param>
        /// <param name="expiration"></param>
        /// <param name="absoluteExpiration"></param>
        /// <returns></returns>
        public static CacheValue<T> Get<T>(this IEasyCachingProvider provider, string cacheKey, Func<T> dataRetriever, TimeSpan expiration, TimeSpan absoluteExpiration)
        {
            var result = provider.Get<CacheValueFormat<T>>(cacheKey);
            if (result.HasValue)
            {
                if (result.Value.ExpiresAt <= DateTimeOffset.Now)
                {
                    var _task = updateTasks.GetOrAdd(cacheKey, new Task(() =>
                    {
                        var item = dataRetriever.Invoke();
                        provider.Set(cacheKey, new CacheValueFormat<T>(item, expiration), absoluteExpiration);
                        updateTasks.TryRemove(cacheKey, out Task value);
                    }));
                    if (_task.Status == TaskStatus.Created)
                    {
                        _task.Start();
                    }
                }
                return new CacheValue<T>(result.Value.Value, true);
            }
            else
            {
                var _methods = updateMethods.GetOrAdd(cacheKey, new Lazy<object>(() => {
                    var _item = dataRetriever.Invoke();
                    provider.Set(cacheKey, new CacheValueFormat<T>(_item, expiration), absoluteExpiration);
                    updateMethods.TryRemove(cacheKey, out Lazy<object> value);
                    return _item;
                }));
                return new CacheValue<T>((T)_methods.Value, true);
            }
        }
    }

    /// <summary>
    /// 缓存实际数据类型
    /// </summary>
    /// <typeparam name="T"></typeparam>
    [Serializable]
    public class CacheValueFormat<T>
    {

        public CacheValueFormat(T value, TimeSpan? ts = null)
        {
            Value = value;
            if (ts.HasValue)
            {
                ExpiresAt = DateTimeOffset.UtcNow.Add(ts.Value);
            }
        }

        public T Value { get; set; }
        public DateTimeOffset ExpiresAt { get; set; }
    }
}

**Comment by catcherwong** [comment]
Sorry, there are no plans at this time. I'll close this issue.
