### ISSUE TITLE
请问我使用 In-Memory 方式能设置永久时间的缓存么 没有过期时间

### ISSUE THREAD

**Issue by Skolley** [dotnetcore/EasyCaching#90]
void Set<T>(string cacheKey, T cacheValue, TimeSpan expiration);

目前我看了下 set 都是要设置过期时间的

**Comment by catcherwong** [comment]
@Skolley Thanks for your interest in this project.

Emm... You can not set a cached value without expiration!

All cached values should be `hot cache`, not `cold cache`.

If you really need this feature, I suggest you set the `expiration` to `TimeSpan.FromDays(365)`  😄

**Comment by Skolley** [comment]
理解 
请问下  设置的这个 expiration 是绝对过期时间 还是相对过期时间？
就是这一段时间没访问就过期,只要命中过一次就重新计算时间的那种

**Comment by catcherwong** [comment]
This is a `AbsoluteExpiration`
