### ISSUE TITLE
Can we set cache without expiration?

### ISSUE THREAD

**Issue by zjadmin** [dotnetcore/EasyCaching#91]
我在使用redis时候set值的必须要设置一个过期时间，但是我在实际中，这个值是不需要过期的，没有找到其它的方法

**Comment by Skolley** [comment]
博主，我问个问题啊。
我想执行数据库级别的 redis命令  
比如：EXISTS，DEL，KEYS  怎么做?

**Comment by catcherwong** [comment]
@zjadmin Thanks for your interest in this project.

You can set a `big` expiration, such as `TimeSpan.FromDays(365)`.

**Comment by Skolley** [comment]
额 不好意思我问题比较多.
我如何注入和使用多个 redis  
还有个问题
如果是简单类型 使用 IEasyCachingProvider 
如果是 复杂类型 使用 IRedisCachingProvider 
我如何 能2个同时使用呢  因为 IRedisCachingProvider 中目前没提供简单类型的 
操作 比如  string 类型的 SET

**Comment by zjadmin** [comment]
> @zjadmin Thanks for your interest in this project.
> 
> You can set a `big` expiration, such as `TimeSpan.FromDays(365)`.

大佬，这里能否改进一下真正意义上的不过期，而不是设置一个相对长的时间

**Comment by catcherwong** [comment]
@Skolley 

`IRedisCachingProvider ` contains some features of redis only, such as Hash etc.

But you can not straightly use the redis command.

**Comment by zjadmin** [comment]
> 额 不好意思我问题比较多.
> 我如何注入和使用多个 redis
> 还有个问题
> 如果是简单类型 使用 IEasyCachingProvider
> 如果是 复杂类型 使用 IRedisCachingProvider
> 我如何 能2个同时使用呢 因为 IRedisCachingProvider 中目前没提供简单类型的
> 操作 比如 string 类型的 SET

我这么操作多个redis的
![image](https://user-images.githubusercontent.com/11642533/54005816-dde1b500-4195-11e9-8394-f15435bc77d1.png)

**Comment by zjadmin** [comment]
> 额 不好意思我问题比较多.
> 我如何注入和使用多个 redis
> 还有个问题
> 如果是简单类型 使用 IEasyCachingProvider
> 如果是 复杂类型 使用 IRedisCachingProvider
> 我如何 能2个同时使用呢 因为 IRedisCachingProvider 中目前没提供简单类型的
> 操作 比如 string 类型的 SET
我是这么操作多个redis
有敏感信息，重新上传一张图
![image](https://user-images.githubusercontent.com/11642533/54005895-2600d780-4196-11e9-93f5-105d2ac97cd0.png)

**Comment by Skolley** [comment]
@zjadmin 你QQ多少我们交流下

**Comment by zjadmin** [comment]
> > 额 不好意思我问题比较多.
> > 我如何注入和使用多个 redis
> > 还有个问题
> > 如果是简单类型 使用 IEasyCachingProvider
> > 如果是 复杂类型 使用 IRedisCachingProvider
> > 我如何 能2个同时使用呢 因为 IRedisCachingProvider 中目前没提供简单类型的
> > 操作 比如 string 类型的 SET
> > 我是这么操作多个redis
> > 有敏感信息，重新上传一张图
> > ![image](https://user-images.githubusercontent.com/11642533/54005895-2600d780-4196-11e9-93f5-105d2ac97cd0.png)

var provider1 = _factory.GetCachingProvider("htredis0");
var provider2 = _factory.GetCachingProvider("htredis1");

**Comment by zjadmin** [comment]
> @zjadmin 你QQ多少我们交流下

我加你吧，我qq设置了权限

**Comment by Skolley** [comment]
@zjadmin 229480577

**Comment by catcherwong** [comment]
@Skolley  Sorry for `IRedisCachingProvider ` can not use the basic usages due to lastest modification.

I will make some changes for this this weekend.

**Comment by catcherwong** [comment]
@zjadmin  

As far as I am concerned, it's more better to set expiration than not to set!

Would you introduce what circumstances do you need a permanent cache? 

And whether this is a regular demand?

**Comment by zjadmin** [comment]
> @zjadmin
> 
> As far as I am concerned, it's more better to set expiration than not to set!
> 
> Would you introduce what circumstances do you need a permanent cache?
> 
> And whether this is a regular demand?

我们有个聊天机器人会频繁的读取配置信息，这个配置信息，我们初始化的时候是直接写进redis的，如果设置了过期时间，会导致机器人不聊天

**Comment by catcherwong** [comment]
> 我们有个聊天机器人会频繁的读取配置信息，这个配置信息，我们初始化的时候是直接写进redis的，如果设置了过期时间，会导致机器人不聊天

What about the configurations were changed? Is there has another task to reload?

**Comment by zjadmin** [comment]
> > 我们有个聊天机器人会频繁的读取配置信息，这个配置信息，我们初始化的时候是直接写进redis的，如果设置了过期时间，会导致机器人不聊天
> 
> What about the configurations were changed? Is there has another task to reload?

一个机器人对应一个配置信息。
配置信息变动的情况：
1.用户对机器人附加（勾选掉）了其它的功能，我们会将新的配置消息更新进去
2.特殊情况（基本不可能出现）
所以我们会将配置信息设置为不过期的状态

**Comment by catcherwong** [comment]
> 一个机器人对应一个配置信息。
配置信息变动的情况：
1.用户对机器人附加（勾选掉）了其它的功能，我们会将新的配置消息更新进去
2.特殊情况（基本不可能出现）
所以我们会将配置信息设置为不过期的状态

As for me, all cached values should be `hot cache`, not `cold cache`. 

Maybe I should keep this issue open to get others suggestion.

**Comment by zjadmin** [comment]
> > 一个机器人对应一个配置信息。
> > 配置信息变动的情况：
> > 1.用户对机器人附加（勾选掉）了其它的功能，我们会将新的配置消息更新进去
> > 2.特殊情况（基本不可能出现）
> > 所以我们会将配置信息设置为不过期的状态
> 
> As for me, all cached values should be `hot cache`, not `cold cache`.
> 
> Maybe I should keep this issue open to get others suggestion.

thanks

**Comment by h0730303779** [comment]
_provider.Set(Constant.CONST_LISTONCLIENT, _clientModels,TimeSpan.MaxValue);

我这设置  会不会 永不过期...

**Comment by h0730303779** [comment]
求 这里能否改进一下真正意义上的不过期，而不是设置一个相对长的时间

**Comment by catcherwong** [comment]
`IRedisCachingProvider` support this feature now.  But `IEasyCachingProvider` will not support it.

https://github.com/dotnetcore/EasyCaching/blob/4f599ac53a3b21f9e14cb1740bbaccf161874622/src/EasyCaching.Core/IRedisCachingProvider.cs#L99-L106

**Comment by Robinloveyou** [comment]
> 

+1
