### ISSUE TITLE
ETA on DIsk Caching?

### ISSUE THREAD

**Issue by VictorioBerra** [dotnetcore/EasyCaching#96]
I need disk caching for a simple desktop app. It has some OAuth tokens I need to save through app crashes and whatnot. All the other caching options are overkill. Any thoughts?

**Comment by catcherwong** [comment]
@VictorioBerra Thanks for your interest in this project.

Disk Caching will be the future feature due to not enough time. And I can't give you an accurate time about when the Disk Caching will be release.

SQLite Caching may be a choice at this time.

**Comment by catcherwong** [comment]
Release v0.6.0
